PowerShell/PowerShellEditorServices

src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs, test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershelleditorservices/207)
=> Fixes #206 - completion list for $env: now works.

CHANGELOG.md, appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershelleditorservices/231)
=> Prepare 0.6.1 release

src/PowerShellEditorServices.Protocol/Client/DebugAdapterClientBase.cs, src/PowerShellEditorServices.Protocol/DebugAdapter/LaunchRequest.cs, src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
See PR https://github.com/PowerShell/vscode-powershell/pull/324 for details.
=> PSES half of program -> script launch prop change.

src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
Resolves PowerShell/vscode-powershell#388
=> Show syntax markers even if analysis disabled

src/PowerShellEditorServices.Protocol/LanguageServer/GetPSHostProcessesRequest.cs, src/PowerShellEditorServices.Protocol/PowerShellEditorServices.Protocol.csproj, src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
I have a bit more confidence in this PR than I do the vscode-powershell (typescript) PR.
=> Implement getPSHostProcessesRequest.

src/PowerShellEditorServices.Protocol/LanguageServer/ScriptFileMarkersRequest.cs, src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
Resolves PowerShell/vscode-powershell#447
=> Change file path to uri in marker request

src/PowerShellEditorServices.Protocol/Client/DebugAdapterClientBase.cs, src/PowerShellEditorServices.Protocol/DebugAdapter/InitializeRequest.cs, src/PowerShellEditorServices/Debugging/BreakpointDetails.cs
In response to https://github.com/Microsoft/vscode/issues/14784
=> Enable column breakpoints.

appveyor.yml, src/PowerShellEditorServices/Session/SessionPSHostUserInterface.cs, test/PowerShellEditorServices.Test.Host/AssemblyInfo.cs, test/PowerShellEditorServices.Test/AssemblyInfo.cs, test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
=> Add SupportsVirtualTerminal property to ConsolePSHostUserInterface

src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs, src/PowerShellEditorServices/Language/LanguageService.cs, src/PowerShellEditorServices/Workspace/ScriptFile.cs, src/PowerShellEditorServices/Workspace/Workspace.cs, test/PowerShellEditorServices.Test.Shared/Definition/FindsFunctionDefinitionInWorkspace.cs, test/PowerShellEditorServices.Test.Shared/References/ReferenceFileD.ps1, test/PowerShellEditorServices.Test.Shared/References/ReferenceFileE.ps1, test/PowerShellEditorServices.Test/Language/LanguageServiceTests.cs
This PR adds the following two features:
* Enables looking up references in the entire workspace
* Enables looking up definitions in the entire workspace
=> Enable reference look up in entire workspace

README.md
Corrects issue with the case of the url.
=> Corrects the Travis CI build badge

README.md
Kapil's already been helping out a ton on editor features, and Patrick is coming on to help us out with our API efforts :)
=> Add Kapil Borle and Patrick Meinecke as maintainers

README.md
Thanks to @PowerSchill for pointing this out!
=> Update development instructions in README.md

src/PowerShellEditorServices.Protocol/Server/LanguageServerSettings.cs
I think folks are going to like this preset option.  Pretty slick @kapilmb !!
=> Add Stroustrup formatting style.

src/PowerShellEditorServices.Protocol/Server/LanguageServerSettings.cs
Resolves PowerShell/vscode-powershell#530
Related PR: PowerShell/PSScriptAnalyzer#790
=> Honor the insertSpaces parameter for formatting

src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
Should had this way in the first PR for this fix.
=> Better fix for the untitled working dir situation

src/PowerShellEditorServices/Session/Capabilities/DscBreakpointCapability.cs
Also, use env var for ProgramFiles location.
=> Don't attempt to import DSC module on PowerShell core

src/PowerShellEditorServices/Session/RemoteFileManager.cs
Resolves PowerShell/vscode-powershell#842
=> Fix issue where psedit cannot open empty files in remote sessions

.vscode/tasks.json
Thanks to @rkeithhill for the examples in vscode-powershell :)
=> Update tasks.json for latest VS Code

CHANGELOG.md, PowerShellEditorServices.Common.props, appveyor.yml, module/PowerShellEditorServices/PowerShellEditorServices.psd1
=> prep for 1.7.0 release 🎉

src/PowerShellEditorServices/Symbols/PesterDocumentSymbolProvider.cs
Fixes #660.
Just does a null check before we look something up in a dictionary.
=> Fix possible null dereference in PesterDocumentSymbolProvider

src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
Set DocumentRangeFormattingProvider value to false.
Fixes #692
=> Fixed #692

src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
This is required for VS support.
=> Add RenameProvider capability

module/PowerShellEditorServices/Start-EditorServices.ps1
I was going to refactor this file but then the security vuln came up and this sneaked in on accident. This fixes stdio again :)
=> fix stdio passing

src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/1488.
Just a small typo to fix.
=> Fix comment-based help snippet

CHANGELOG.md
Update the changelog for the 1.8.4 release
=> [Ignore] Update changelog for 1.8.4 release

CHANGELOG.md, PowerShellEditorServices.Common.props, appveyor.yml, module/PowerShellEditorServices/PowerShellEditorServices.psd1
=> [Ignore] Prepare 1.9.0 release

PowerShellEditorServices.Common.props, appveyor.yml, module/PowerShellEditorServices/PowerShellEditorServices.psd1
Increments the versions for the next post-release
=> [Ignore] Increment version

src/PowerShellEditorServices/PowerShellEditorServices.csproj, src/PowerShellEditorServices/Session/InvocationEventQueue.cs
Update our PSStandard dependency and remove the erroneous overload we no longer need.
=> Update PSStandard dependency

src/PowerShellEditorServices/Language/FindReferencesVisitor.cs, src/PowerShellEditorServices/Language/FindSymbolsVisitor.cs, src/PowerShellEditorServices/Language/FindSymbolsVisitor2.cs, src/PowerShellEditorServices/Language/GetDefinitionResult.cs, test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
Fix multiple occurrences of the same typo (defintion/definition)
Excuse the trivial PR, but I was working on something else and figured I would fix that.
=> Fix multiple occurrences of the same typo

CHANGELOG.md, PowerShellEditorServices.Common.props, appveyor.yml, module/PowerShellEditorServices/PowerShellEditorServices.psd1
Update versions/changelog for 1.10.0 release.
=> [Ignore] Update CHANGELOG for 1.10.0

PowerShellEditorServices.build.ps1
Release build agents don't have git on them...
=> check for git

CHANGELOG.md, PowerShellEditorServices.Common.props, appveyor.yml, module/PowerShellEditorServices/PowerShellEditorServices.psd1
Prep 1.11 release with Changelog
=> [Ignore] Prep 1.11 release with Changelog

PowerShellEditorServices.Common.props, appveyor.yml, module/PowerShellEditorServices/PowerShellEditorServices.psd1
=> Rev to version 1.12

CHANGELOG.md
No version updates are need here... it's already at the version it should be at.
=> prep for 2.0.0-preview.2 release

module/PowerShellEditorServices/Start-EditorServices.ps1
Add "Warning" to LogLevel parameter validation set of Start-EditorServices.ps1
=> Add warning to parameter validation set

.vsts-ci/misc-analysis.yml, .vsts-ci/templates/credscan.yml
Starts an Azure DevOps build that will fail if secrets are checked into code.
=> Add secret scan ymls

src/PowerShellEditorServices.Protocol/LanguageServer/Completion.cs, src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs, test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs, test/PowerShellEditorServices.Test.Host/TestFiles/CompleteFunctionName.ps1
* WIP: Improve path auto-completion
* Add comment to address PR feedback
* Address PR feedback
* Add tests for path completion, do not do snippet completion on files
* Fix incorrect macOS/Linxu path in completion test
=> Backport: Improve path auto-completion (#902)

module/PowerShellEditorServices/Commands/Public/CmdletInterface.ps1, src/PowerShellEditorServices.Protocol/Server/LanguageServerSettings.cs
Also see https://github.com/PowerShell/vscode-powershell/pull/1864
=> Backport for 1.12.1

CHANGELOG.md, PowerShellEditorServices.Common.props, appveyor.yml, module/PowerShellEditorServices/PowerShellEditorServices.psd1
WIP: We should do the changelog here as well
=> Increment version

README.md
because we need more badges obviously.
=> dependabot and Discord badges

.dependabot/config.yml
Too much...
Slowing down dependabot to weekly.
=> [Ignore] slow down dependabot

module/PowerShellEditorServices.VSCode/Public/HtmlContentView/New-VSCodeHtmlContentView.ps1, module/PowerShellEditorServices.VSCode/Public/HtmlContentView/Set-VSCodeHtmlContentView.ps1, module/PowerShellEditorServices.VSCode/Public/HtmlContentView/Write-VSCodeHtmlContentView.ps1
These were missed in #792 and have also rendered the CustomView cmdlets totally broken.
This fixes that piece and should go with https://github.com/PowerShell/vscode-powershell/pull/1919
=> rename to use async

src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
Backport of https://github.com/PowerShell/PowerShellEditorServices/pull/949
=> Add check for workspace path

src/PowerShellEditorServices.Protocol/DebugAdapter/AttachRequest.cs, src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
=> Allow passing RunspaceName (#951)

README.md
Resolves https://github.com/PowerShell/PowerShellEditorServices/issues/969
=> Add list of frontends to README

src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
=> Backport #974

NuGet.Config, PowerShellEditorServices.build.ps1, src/PowerShellEditorServices.Protocol/PowerShellEditorServices.Protocol.csproj, test/Pester/EditorServices.Integration.Tests.ps1, tools/PsesPsClient/PsesPsClient.csproj, tools/PsesPsClient/PsesPsClient.psd1, tools/PsesPsClient/PsesPsClient.psm1
For CI.
When we add xunit tests later, we'll include those in the test run
=> Test only pester

tools/releaseBuild/FileCatalogSigning.xml, tools/releaseBuild/signing.xml
=> [ignore] Changing signing type

src/PowerShellEditorServices.Protocol/MessageProtocol/MessageWriter.cs
=> BACKPORT: Catch stream exceptions for some Debug Adapter stability. (#1022)

PowerShellEditorServices.Common.props
=> rev version to 2.0.0-preview.5

src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
The apt state API was added back in in PowerShell 7.
=> apply apt state for PS7

src/PowerShellEditorServices/Services/TextDocument/Handlers/DocumentHighlightHandler.cs, test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2269.
=> Fix highlighting offset

modules.json
Update modules.json for PSRL to beta 6
I thought I already did this... but I guess not.
=> Update modules.json for PSRL to beta 6

.poshchan/settings.json
See https://github.com/PowerShell/PowerShellEditorServices/pull/1122#issuecomment-562947657
=> Add PoshChan rights for restarting CI to GitHub user 'bergmeister'

CHANGELOG.md
Updates the changelog for 2.0.0-preview8 to include PR #1158
=> Update CHANGELOG.md to include PR #1158

tools/releaseBuild/signing.xml
partially addresses https://github.com/PowerShell/vscode-powershell/issues/2536 signing `Clear-Host.ps1`
=> sign Clear-Host.ps1

src/PowerShellEditorServices/Services/PowerShellContext/EditorOperationsService.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2525
=> Don't warn user on Clear-Host

src/PowerShellEditorServices/PowerShellEditorServices.csproj, test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj, test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
call me dependabot just this time
=> Update omnisharp libs

src/PowerShellEditorServices/Services/TextDocument/ScriptFile.cs, test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
=> Fix IsUntitledPath logic

.vsts-ci/templates/ci-general.yml
I've opened this issue to track changing this back: https://github.com/PowerShell/PowerShellEditorServices/issues/1335
=> try to fix build

src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2965
=> Fix error when started in low .NET versions

.vsts-ci/templates/release-general.yml
The template allows us to always copy so we can depend on it for publish.
=> Fix publish step

CHANGELOG.md
=> Update CHANGELOG for v2.4.0-preview.1

module/PowerShellEditorServices/PowerShellEditorServices.psd1
This was missed, yet another reason we need to automate this process.
Fixes #1455.
=> Fix version in module definition file

.github/dependabot.yml, README.md
Also change 'assignee' to 'reviewer' and add Rob.
=> Remove deprecated badges

src/PowerShellEditorServices/PowerShellEditorServices.csproj, test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj, test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
This pulls in https://github.com/OmniSharp/csharp-language-server-protocol/pull/589 which fixes https://github.com/PowerShell/vscode-powershell/issues/3306!
=> Bump OmniSharp to `v0.19.2-beta0002`

CHANGELOG.md, PowerShellEditorServices.Common.props, module/PowerShellEditorServices/PowerShellEditorServices.psd1
=> Release `v2.4.2-preview.1`

CHANGELOG.md, PowerShellEditorServices.Common.props, module/PowerShellEditorServices/PowerShellEditorServices.psd1
Do we want to handwrite a changelog entry for this?
=> Release `v2.4.3`

CHANGELOG.md, PowerShellEditorServices.Common.props, module/PowerShellEditorServices/PowerShellEditorServices.psd1
=> Release v2.4.4

PowerShellEditorServices.build.ps1
=> Make `dotnet test` arguments configurable

README.md
=> Add Justin Grote as maintainer

modules.json
Picking up the latest beta for our preview.
=> Bump PSReadLine module to 2.2.0-beta5

.vsts-ci/azure-pipelines-release.yml
Per https://github.com/PowerShell/PowerShell/pull/16768
=> Update image for signing

src/PowerShellEditorServices.Hosting/PowerShellEditorServices.Hosting.csproj
=> Remove temporary `dotnet publish` workaround

test/PowerShellEditorServices.Test.E2E/DebugAdapterClientExtensions.cs, test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
Just applying automatic cleanups.
=> Clean up LSP message tests

src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
=> Handle edge case where `prompt` is undefined

modules.json
Fixes https://github.com/PowerShell/PowerShellEditorServices/issues/1709.
=> Update PSReadLine to 2.2.2

modules.json
This resolves https://github.com/PowerShell/vscode-powershell/issues/3937. Really!
=> Update to latest PSReadLine beta (with fix for race condition)

src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/3965
=> Wrap untitled script with newlines

test/PowerShellEditorServices.Test/Session/PsesInternalHostTests.cs
This adds a regression test for #1807.
=> Add regression test for no defined profiles

.github/workflows/codeql-analysis.yml, .github/workflows/emacs-test.yml, .vsts-ci/misc-analysis.yml, CHANGELOG.md, PowerShellEditorServices.Common.props, README.md, module/PowerShellEditorServices.VSCode/PowerShellEditorServices.VSCode.psd1, module/PowerShellEditorServices/Commands/PowerShellEditorServices.Commands.psd1, module/PowerShellEditorServices/PowerShellEditorServices.psd1, module/PowerShellEditorServices/Start-EditorServices.ps1, module/docs/ConvertFrom-ScriptExtent.md, module/docs/ConvertTo-ScriptExtent.md, module/docs/Find-Ast.md, module/docs/Get-Token.md, module/docs/Import-EditorCommand.md, module/docs/Join-ScriptExtent.md, module/docs/Out-CurrentFile.md, module/docs/Register-EditorCommand.md, module/docs/Set-ScriptExtent.md, module/docs/Test-ScriptExtent.md, module/docs/Unregister-EditorCommand.md
=> Find/replace of `master` to `main` for branch rename

modules.json
Resolves https://github.com/PowerShell/PowerShellEditorServices/issues/1844
=> Update PSReadLine to v2.2.6

.vsts-ci/templates/ci-general.yml, PowerShellEditorServices.build.ps1, tools/azurePipelinesBuild.ps1
=> Change CI build script to only build

test/emacs-test.el
The Eglot package updated and this is now a list.
=> Fix Emacs unit test

README.md, test/emacs-test.el
=> Update Andy's name

PowerShellEditorServices.build.ps1, src/PowerShellEditorServices/PowerShellEditorServices.csproj
I normally merge things easily, this time I had a bad time.
=> Fix duplicate package reference from bad merge

src/PowerShellEditorServices/Services/Symbols/Visitors/SymbolVisitor.cs, test/PowerShellEditorServices.Test.Shared/References/SimpleFile.ps1, test/PowerShellEditorServices.Test/Language/SymbolsServiceTests.cs
Resolves https://github.com/PowerShell/vscode-powershell/issues/1481.
=> Count `${Function:My-Function}` as a function reference

.mailmap
This makes Git transparently remap commits under my prior name and email to my new name and Microsoft email.
=> Add Git mailmap for Andy Jordan

.github/workflows/codeql-analysis.yml, .vsts-ci/azure-pipelines-ci.yml, .vsts-ci/misc-analysis.yml
I like it so far this time, so setting up just like in https://github.com/PowerShell/vscode-powershell/pull/4637.
=> Setup GitHub merge queue

modules.json
=> Update PSReadLine to `v2.3.2-beta2`

modules.json
=> Upgrade bundled PSReadLine module to v2.3.4

modules.json
=> Bump PSScriptAnalyzer

CHANGELOG.md, PowerShellEditorServices.Common.props, module/PowerShellEditorServices/PowerShellEditorServices.psd1
=> v3.19.0: Overhauled Terminal Shell Integration!

.github/workflows/ci-test.yml, .github/workflows/codeql-analysis.yml, .github/workflows/emacs-test.yml, .github/workflows/vim-test.yml
Until it's figured out how we're supposed to use these on GitHub.
=> Fix CI by removing Azure Artifacts Feeds

README.md
Hi! I am a maintainer of intellij-powershell, and we recently have released a plugin version that supports debugging using PSES (that works good, thank you folks so much!)
Since it is mentioned in the language section of the README already, I decided to add it to the debugger section as well.
=> Mention debugging support in intellij-powershell

Directory.Packages.props, test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
Which means the PowerShell SDK so its transitive dependencies update.
=> Bump packages for component governance

PowerShellEditorServices.build.ps1
=> Fix RestorePsesModules to use Save-PSResource

.github/workflows/ci-test.yml, PowerShellEditorServices.build.ps1
~~Expecting this to fail until https://github.com/PowerShell/PowerShell/pull/25124 is merged.~~ Working around this with `-Destination`.
=> Test PowerShell Preview in CI instead of Daily

PowerShellEditorServices.build.ps1
=> Skip PowerShell Preview tests on OneBranch

CHANGELOG.md, PowerShellEditorServices.Common.props, module/PowerShellEditorServices/PowerShellEditorServices.psd1
=> v4.4.0: Supports screen readers!
