PowerShell/PowerShellEditorServices

- src/PowerShellEditorServices.Host/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/ScopesRequest.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/StackTraceRequest.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/Variable.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/VariablesRequest.cs
- src/PowerShellEditorServices/Debugging/DebugService.cs
- src/PowerShellEditorServices/Debugging/StackFrameDetails.cs
- src/PowerShellEditorServices/Debugging/VariableContainerDetails.cs
- src/PowerShellEditorServices/Debugging/VariableDetails.cs
- src/PowerShellEditorServices/Debugging/VariableDetailsBase.cs
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
This PR adds support for displaying Global and Script scope variables.  It also supports showing local variables for stack frames other than the topmost frame (frame 0).
> Add support for more variable scopes in debugger

- src/PowerShellEditorServices.Protocol/Server/ProtocolServer.cs
This change fixes the casing of event messages raised from the debug
adapter.  This issue caused the VS Code debugger UI to not display details
correctly when stopped at a breakpoint.
> Fix casing of event messages from debug adapter

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Language/AstOperations.cs
- src/PowerShellEditorServices/Language/CompletionResults.cs
- src/PowerShellEditorServices/Language/LanguageService.cs
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Workspace/BufferPosition.cs
- src/PowerShellEditorServices/Workspace/BufferRange.cs
- src/PowerShellEditorServices/Workspace/ScriptFile.cs
- test/PowerShellEditorServices.Test.Shared/Completion/CompleteAttributeValue.cs
- test/PowerShellEditorServices.Test.Shared/Completion/CompleteFilePath.cs
- test/PowerShellEditorServices.Test.Shared/Completion/CompletionExamples.psm1
- test/PowerShellEditorServices.Test.Shared/PowerShellEditorServices.Test.Shared.csproj
- test/PowerShellEditorServices.Test/Language/LanguageServiceTests.cs
This change resolves a general class of issues around code completions
coming from the language service.  The JSON protocol allows the language
server to specify the range of code that will get replaced by a completion
item.  Previously this range was being computed incorrectly.  We now use
the replacement range given by the PowerShell API.
This also resolves PowerShell/vscode-powershell issues 45 and 12
> Fix #45, #63: Completion text replacement bugs

- .gitignore
- appveyor.yml
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- test/PowerShellEditorServices.Test.Host/PowerShellEditorServices.Test.Host.csproj
- test/PowerShellEditorServices.Test.Host/xunit.runner.json
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
- test/PowerShellEditorServices.Test/xunit.runner.json
This change fixes a hang that was caused by the recent refactoring of host
process server implementations.  In the debug adapter implementation, the
PowerShellContext was not being disposed at shutdown which was causing the
process to stay open because the associated threads were still alive.
This change adds the necessary ProtocolServer.Shutdown implementation.
> Fix hang when debug adapter finishes executing

- src/PowerShellEditorServices.Protocol/MessageProtocol/Serializers/JsonRpcMessageSerializer.cs
- src/PowerShellEditorServices.Protocol/Server/ProtocolServer.cs
This change improves JSON RPC message deserialization to tolerate requests
and events lacking a 'params' object.  This appeared while using
vscode-languageclient and attempting the language server using its stop()
method.
> Improve JSON RPC message deserialization

- src/PowerShellEditorServices.Host/Program.cs
- src/PowerShellEditorServices/Analysis/AnalysisService.cs
This change greatly reduces the set of Script Analyzer rules that are used
by default in the analysis service.  In the future, this list of rules
will be fully configurable by the user.  This change is meant to simplify
the ruleset in the meantime.
> Use a minimal set of Script Analyzer rules

- CHANGELOG.md
- appveyor.yml
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- test/PowerShellEditorServices.Test.Host/DebugAdapterTests.cs
- test/PowerShellEditorServices.Test.Shared/Debugging/DebugTest.ps1
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
This change fixes an issue from the latest refactoring which causes
the DebugAdapter to not send OutputEvents when output is written while
script is running.  This was reported in PowerShell/vscode-powershell#49.
This change also introduces a new test to ensure that the DebugAdapter is
writing output.
> Fix missing OutputEvents in DebugAdapter

- src/PowerShellEditorServices.Channel.WebSocket/Properties/AssemblyInfo.cs
- src/PowerShellEditorServices.Channel.WebSocket/WebsocketClientChannel.cs
- src/PowerShellEditorServices.Channel.WebSocket/WebsocketServerChannel.cs
- src/PowerShellEditorServices.Host/Program.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/EvaluateRequest.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Debugging/DebugService.cs
- src/PowerShellEditorServices/Language/AstOperations.cs
- src/PowerShellEditorServices/Language/FindSymbolsVisitor2.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
- test/PowerShellEditorServices.Test.Channel.WebSocket/Properties/AssemblyInfo.cs
- test/PowerShellEditorServices.Test.Channel.WebSocket/WebSocketChannelTest.cs
- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
- test/PowerShellEditorServices.Test.Host/PowerShellEditorServices.Test.Host.csproj
- test/PowerShellEditorServices.Test.Host/packages.config
- test/PowerShellEditorServices.Test/Console/PowerShellContextTests.cs
- test/PowerShellEditorServices.Test/Language/PowerShellVersionTests.cs
These changes vastly improve the current state of execution of commands in the REPL both while running inside and outside of the debugger.  The biggest change is that we now show the PowerShell prompt in the REPL output.  We also can now stream the results of commands run in the debugger console so that the user doesn't have to wait to see output until the command finishes.  Lastly, we now handle RuntimeExceptions correctly sending the error output to the host.
> Improvements to REPL execution

- src/PowerShellEditorServices.Host.x86/PowerShellEditorServices.Host.x86.csproj
- src/PowerShellEditorServices.Host.x86/packages.config
- src/PowerShellEditorServices.Host/PowerShellEditorServices.Host.csproj
- src/PowerShellEditorServices.Host/packages.config
- src/PowerShellEditorServices.Protocol/DebugAdapter/NextRequest.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/SetExceptionBreakpointsRequest.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/MessageDispatcher.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/MessageWriter.cs
- src/PowerShellEditorServices.Protocol/PowerShellEditorServices.Protocol.csproj
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices.Protocol/packages.config
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Session/PowerShellContext.cs
- src/PowerShellEditorServices/Utility/AsyncContext.cs
- src/PowerShellEditorServices/Utility/AsyncContextThread.cs
- src/PowerShellEditorServices/Utility/AsyncLock.cs
- src/PowerShellEditorServices/Utility/AsyncQueue.cs
- src/PowerShellEditorServices/Utility/ThreadSynchronizationContext.cs
- src/PowerShellEditorServices/packages.config
- test/PowerShellEditorServices.Test.Host/PowerShellEditorServices.Test.Host.csproj
- test/PowerShellEditorServices.Test.Host/ServerTestsBase.cs
- test/PowerShellEditorServices.Test.Host/packages.config
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
- test/PowerShellEditorServices.Test/Session/PowerShellContextTests.cs
- test/PowerShellEditorServices.Test/Utility/AsyncLockTests.cs
- test/PowerShellEditorServices.Test/Utility/AsyncQueueTests.cs
- test/PowerShellEditorServices.Test/packages.config
This change removes all uses of the Nito.AsyncEx NuGet package from the
solution.  This change was made to remove the use of this third-party
dependency so that consumers don't need to get extra open-source approval
when using PowerShell Editor Services.
Removing this dependency required the creation of our own custom
implementations of the classes we were using from Nito.AsyncEx.  These new
classes were written from scratch.
Resolves #115
> Remove Nito.AsyncEx dependency, add replacements

- src/PowerShellEditorServices.Protocol/LanguageServer/FindModuleRequest.cs
- src/PowerShellEditorServices.Protocol/LanguageServer/InstallModuleRequest.cs
- src/PowerShellEditorServices.Protocol/PowerShellEditorServices.Protocol.csproj
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
Enables execution of Find-Module, then the displaying of modules in a quick pick list, if one is selected, Install-Module is then invoked
> Add support for finding and installing PowerShell Gallery modules

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Language/CompletionResults.cs
- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
- test/PowerShellEditorServices.Test/Language/PowerShellVersionTests.cs
This commit not only addresses issue #98 but also improves completion list support overall for commands (shows resolved command or path to exe), parameters (shows parameter type) as well as .NET properties and methods (shows signature).
> Implementation for issue #98 - shorting file path completion list.

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
This takes advantage of the fact that PowerShell returns us a list of parameter names already in the preferred order (common params at the end).  We just need to make the SortText for each completion result preserve the initial order.
> Addresses issue #40 - improved parameter completion list order

- src/PowerShellEditorServices/Session/SessionPSHostRawUserInterface.cs
I'll also update the MaxWindowSize and MaxPhysicalWindowSize (including height) to all be consistent with the initial default size.  This is all we can do for now as we get no notifications from VSCode on console size changes.
> Fix for issue 129 - increase default dbg console to 120

- src/PowerShellEditorServices.Protocol/DebugAdapter/LaunchRequest.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
Turns out vscode passes us the cwd.  Just needed to rename the property in the LaunchRequest class to match. Same for args (renamed Arguments).  I have not hooked up script args yet though.
@daviwil - please look over the ExecuteCommand for Set-Location to make sure I'm doing the ContinueWith() correctly.
> Fixes #137 - working dir should be set to something reasonable.

- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
If cwd is a file path we check for that and if so, we grab its folder.  If any error occurs during this test for dir/grab parent dir operation we log it and continue.  I don't think we should crash the debugger.  Unfortunately the call to set-location with a bad path doens't get echoed to the debug console (just the debugAdapter.log) so the user won't know they typo'd a path - if they change the default.  :-(
> Adding support for passing ${file} as cwd.

- src/PowerShellEditorServices.Protocol/PowerShellEditorServices.Protocol.csproj
- src/PowerShellEditorServices.Protocol/Properties/AssemblyInfo.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices.Protocol/Server/OutputDebouncer.cs
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Utility/AsyncDebouncer.cs
- test/PowerShellEditorServices.Test.Host/DebugAdapterTests.cs
- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
- test/PowerShellEditorServices.Test.Host/OutputReader.cs
- test/PowerShellEditorServices.Test.Host/PowerShellEditorServices.Test.Host.csproj
- test/PowerShellEditorServices.Test.Protocol/PowerShellEditorServices.Test.Protocol.csproj
- test/PowerShellEditorServices.Test.Protocol/Server/OutputDebouncerTests.cs
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
- test/PowerShellEditorServices.Test/Utility/AsyncDebouncerTests.cs
This change introduces a new AsyncDebouncer class which is able to gate
invocation requests to only occur after a specified interval.  This class
is used to implement an OutputDebouncer which takes all output messages
written from the PowerShell host and buffers them.  This causes many lines
of output written in a short time window to be sent as one OutputEvent
rather than writing individual events for each line.
Resolves #113.
> Add intervallic buffering of OutputEvent messages

- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
- test/PowerShellEditorServices.Test.Shared/Debugging/DebugWithParamsTest.ps1
- test/PowerShellEditorServices.Test.Shared/PowerShellEditorServices.Test.Shared.csproj
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
This approach concats args (if any passed) with a space delimiter and then appends that to the scriptpath (space separed) and used AddScript() which takes this combination of script and args.
> Fixex #141 - passes args to script.

- src/PowerShellEditorServices/Session/SessionPSHost.cs
For some reason, the PowerShell engine thinks notepad.exe is a command-line app and calls the SessionPSHost BeginNotifyApplication() which used to throw NotImplementedException.  It now just logs the call.  
Also updated the PSHost version to pull the version from the services dll.  I tried several ways to pull from the host app (reflection Process.GetCurrentProcess().MainModule) but both caused the unit tests to hang.
> Fixes issue with notepad.exe running correctly.

- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
- test/PowerShellEditorServices.Test.Host/OutputReader.cs
This change provides a fix with timing issues that can occur with tests
which leverage the OutputReader class to read buffered output from the
host process.  It avoids test hangs by using a timeout of 5 seconds per
read and handles an edge case where some line segments don't end with
newlines.
> Fix timing issues with OutputReader in host tests

- .gitmodules
- CHANGELOG.md
- README.md
- appveyor.yml
Final release preparation for PowerShell Editor Services v0.4.0
> Release 0.4.0

- src/PowerShellEditorServices/Session/PowerShellContext.cs
- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
This change enables native console app output to be written in the host
process without it breaking the standard I/O channel between the client
and host.  It accomplishes this by setting an internal property in the
PowerShell runtime called ConsoleVisibility.AlwaysCaptureApplicationIO.
This is a short term solution until we find a better way to deal with
native application output.
> Fix #147: Enable native console app output in REPL

- src/PowerShellEditorServices.Host/Program.cs
OK been doing a lot of debugging of the debug adapater and this has been driving me crazy.   Launch VSCode, open PS1 file so I can find the PID of the editor host.  Then debug the script, hop over to VS attach to process, find the PID of the second host process (the debug instance) and attach.  This new approach will just pop up a dialog box asking which instance of VS to use to debug.  You can press NO to skip attaching the debugger and the script will continue to execute.
> Easier launching of the debugging when /waitForDebugger passed in.

- README.md
Also introducing the new [Development Roadmap](https://github.com/PowerShell/PowerShellEditorServices/wiki/Development-Roadmap) wiki page.  @rkeithhill, would appreciate your feedback on what I've laid out there so far.  Feel free to add new items that you're interested in working on.
> Update README.md to convey latest project status

- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
- test/PowerShellEditorServices.Test.Host/OutputReader.cs
This fix handles an edge case when buffered output that ends with a
newline is treated incorrectly causing an extra empty line to be returend
by the OutputReader.
> Fix #157: Tests using OutputReader sometimes hang

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServerBase.cs
The change fixes an issue in the LanguageServer's Shutdown method where
buffered output in the OutputDebouncer gets flushed before shutting down.
The problem here is the Wait call which blocks the message dispatcher
thread from completing the OutputDebouncer.OnFlush method's SendEvent
call.  The fix is to change the Shutdown method to async so that the
OnFlush call can be awaited, unblocking the message dispatcher thread's
SynchronizationContext for the SendEvent call to complete.
> Fix #159: LanguageServer.Shutdown hangs on flush

- src/PowerShellEditorServices/Debugging/StackFrameDetails.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
Because we use AddScript, that adds another scope not associated with any filename.  That resulted in a StackFrame ScriptPath with a null value.  Later, VSCode sent us a request for soruce with a sourceReference value of null.  That caused the JSON deserialization of that message to throw and that crashed the debug host.  I made two changes.  First, when we construct the StackFrameDetails, if the PowerShell CallStackFrame.ScriptName is null, we use the string "<No File>" instead for ScriptPath.  The second change was to ExecuteScriptAtPath.  Essentially, if you do not pass args we now use AddCommand(scriptPath) which does not add the extra stack frame.  If you do use args then we still use AddScript.  You will see the extra outermost stack frame of "<ScriptBlock>, <NoFile>".  What is …
> Fixes #155 - selecting outermost scope crashes debug host.

- src/PowerShellEditorServices/Analysis/AnalysisService.cs
- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
- test/PowerShellEditorServices.Test.Host/PowerShellEditorServices.Test.Host.csproj
- test/PowerShellEditorServices.Test.Host/TestFiles/SimpleSemanticError.ps1
This change fixes an issue in 0.4.1 where Script Analyzer analysis markers
are not being returned by the AnalysisService.  This issue was caused by a
new optional parameter to the ScriptAnalyzer.Initialize method called
'includeDefaultRules' which was introduced in 1.3.0.  Since this parameter
has a default value of 'false', the default Script Analyzer rules were not
being loaded or applied in analysis runs.
> Fix #153: Script Analyzer is not returning markers

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Session/EditorSession.cs
This change enables PowerShell Editor Services to operate correctly in the
scenario where no Script Analyzer binaries are available.  This is a first
step in the direction of removing the direct dependency on Script Analyzer
and moving analysis behavior to the new extensibility model.
> Fix #166: Handle lack of Script Analyzer binaries

- src/PowerShellEditorServices.Protocol/DebugAdapter/InitializeRequest.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/LaunchRequest.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/SetExceptionBreakpointsRequest.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/SourceRequest.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/StackTraceRequest.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapterBase.cs
This commit is in preparation for adding conditional breakpoint and function breakpoint support.  Also cleaned up some doc comments.  The two primary files that were changed functionally are InitializeRequest.cs and DebugAdapaterBase.cs.
> Fixes #164 - adds capabilities response to initialize request.

- src/PowerShellEditorServices.Protocol/DebugAdapter/Scope.cs
This makes the debug hover tips work better.  But if you want to look at a variable in a higher scope, you have to select that scope in the callstack so the variable is a "local" variable in that scope.
> Partial fix for issue 95 - set all scopes but Local as expensive.

- src/PowerShellEditorServices.Protocol/DebugAdapter/Breakpoint.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/SetBreakpointsRequest.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapterBase.cs
- src/PowerShellEditorServices/Debugging/BreakpointDetails.cs
- src/PowerShellEditorServices/Debugging/DebugService.cs
- test/PowerShellEditorServices.Test.Host/DebugAdapterTests.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
This adds some unit tests for conditional breakpoints and refactors some existing unit tests I wrote to be a bit more DRY.  Also, VSCode supports column breakpoints in its protocol.  And PowerShell supports breakpoints on columns other than 1.  So why don't I see any UI in VSCode to create a breakpoint at a specific column?  Is there something we have to do to declare support for column breakpoints?
> Fixes #94 - adds support for conditional breakpoints

- CHANGELOG.md
- appveyor.yml
(Very) minor release.  This includes one fix that enables an initial integration with the PowerShell ISE Preview.
> Release 0.4.3

- src/PowerShellEditorServices.Protocol/Client/DebugAdapterClientBase.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/Breakpoint.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/ConfigurationDoneRequest.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/SetFunctionBreakpointsRequest.cs
- src/PowerShellEditorServices.Protocol/PowerShellEditorServices.Protocol.csproj
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapterBase.cs
- src/PowerShellEditorServices/Debugging/BreakpointDetails.cs
- src/PowerShellEditorServices/Debugging/BreakpointDetailsBase.cs
- src/PowerShellEditorServices/Debugging/DebugService.cs
- src/PowerShellEditorServices/Debugging/FunctionBreakpointDetails.cs
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- test/PowerShellEditorServices.Test.Host/DebugAdapterTests.cs
- test/PowerShellEditorServices.Test.Shared/Debugging/DebugTest.ps1
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
This PR introduces support for the configurationDone request.  In fact, due to the order in which set*Breakpoints requests and the launch request come in, we now defer the execution of the script until we receive the configurationDone request.  When we executed from the launch request, the debug host would appear to hang.  It did not like executing Set/Remove-PSBreakpoint commands when the host debugger was running (not in a stopped state) AFAICT.
The first commit has a known issue with VSCode mixing up which breakpoint has a condition associated with it when you add/remove a breakpoint (see Microsoft/vscode#3558).  The second commit fixes this issue.
> Fixes #173 - implementation for function breakpoints 

- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
It turns out that when the debugger stops at a function breakpoint, it isn't necessarily obvious why the debugger stopped.  There is no breakpoint glyph for a function breakpoint.  So if we return "function breakpoint", then VSCode will display "PAUSED ON FUNCTION BREAKPOINT" in the call stack viewlet.  Hopefully that will help the user know why the debugger stopped.
See related VSCode issue - https://github.com/Microsoft/vscode/issues/3648
> Provide a bit more accurate "reason" for debug stop.

- src/PowerShellEditorServices.Protocol/DebugAdapter/Breakpoint.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices/Debugging/CommandBreakpointDetails.cs
- src/PowerShellEditorServices/Debugging/DebugService.cs
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
The services API should be oriented more towards PowerShell (and not VSCode) terminology.
> Renamed FunctionBreakpointDetails to CommandBreakpointDetails

- src/PowerShellEditorServices/Console/FieldDetails.cs
- src/PowerShellEditorServices/Session/SessionPSHostUserInterface.cs
This change adds proper error handling for input prompt requests for field
types that we don't yet support like SecureString and PSCredential.
Previously any Read-Host or Get-Credential call which prompts for either
of these types would crash the language and debugging services.  The fix
causes errors to be written to the host stating that these commands and
field types are not yet supported.
> Fix #181: Fix crash for unsupported field types

- appveyor.yml
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Session/EditorSession.cs
- src/PowerShellEditorServices/Workspace/ScriptFile.cs
- src/PowerShellEditorServices/Workspace/Workspace.cs
- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
- test/PowerShellEditorServices.Test.Host/PowerShellEditorServices.Test.Host.csproj
- test/PowerShellEditorServices.Test.Host/TestFiles/ChildModule/ChildModule.psm1
- test/PowerShellEditorServices.Test.Host/TestFiles/Module.psm1
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
- test/PowerShellEditorServices.Test/Language/LanguageServiceTests.cs
- test/PowerShellEditorServices.Test/Language/PowerShellVersionTests.cs
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
This change fixes an issue with relative module path resolution with the
'using module' statement in more recent versions of PowerShell v5.  A new
method overload was added to the PowerShell API's Parser.ParseInput method
which allows the script's path to be specified.  By using this parameter,
the PowerShell parser resolves relative module paths correctly.
This change also required a change to how PowerShell API usage is verified
for different PowerShell versions.  Since the PowerShell v5 reference
assemblies don't (yet) contain Parser.ParseInput overload, we now have to
make a distinction between the PowerShell v5 which is specified by the
reference assemblies and the one that is currently shipped in the latest
official Windows 10 release (10586).  Once updated reference assemblies
have …
> Fix #99: 'using module' relative path resolution

- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Session/EditorSession.cs
- src/PowerShellEditorServices/Session/IVersionSpecificOperations.cs
- src/PowerShellEditorServices/Session/PowerShell3Operations.cs
- src/PowerShellEditorServices/Session/PowerShell4Operations.cs
- src/PowerShellEditorServices/Session/PowerShell5Operations.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
This change finishes our PowerShell v3 and v4 support by conditionally
changing behavior for those versions.  This works by using an interface
facade in front of any version-specific behavior so that the CLR doesn't
try to resolve method names that aren't available in a particular version.
> Finish PowerShell v3 and v4 support

- src/PowerShellEditorServices.Channel.WebSocket/WebsocketServerChannel.cs
- src/PowerShellEditorServices.Host/Program.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServerSettings.cs
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Session/EditorSession.cs
- src/PowerShellEditorServices/Session/HostDetails.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
- src/PowerShellEditorServices/Session/ProfilePaths.cs
- src/PowerShellEditorServices/Session/SessionPSHost.cs
- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
- test/PowerShellEditorServices.Test.Shared/PowerShellEditorServices.Test.Shared.csproj
- test/PowerShellEditorServices.Test.Shared/Profile/Profile.ps1
- test/PowerShellEditorServices.Test.Shared/Profile/ProfileTest.ps1
- test/PowerShellEditorServices.Test/Session/PowerShellContextTests.cs
This change adds support for loading both host-agnostic and host-specific
profile scripts for the current user and all users depending on which of
those scripts are available on the system.  Profile loading behavior is
opt-in and not enabled by default.  Regardless of whether profiles get
loaded, a $profile variable is inserted into the PowerShellContext's
runspace upon initialization.
Resolves #111.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershelleditorservices/199)
> Add support for loading host profile scripts

- src/PowerShellEditorServices.Protocol/DebugAdapter/Breakpoint.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
This fixes the crash at the protocol layer for VSCode.  This does not cause the debug host to spit anything out to the debug console.  I was finding a good way to get a ScriptFile down to the SetLineBreakpoint() method for a source path that does not exist.  I figured at the least, we could eliminate the debug host crash for now.  
I also believe the VSCode folks should fix this by displaying our message in the breakpoints list UI.  See https://github.com/microsoft/vscode/issues/4935
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershelleditorservices/205)
> Fixes #195 - set breakpoint in non-existing file doesn't crash

- src/PowerShellEditorServices.Protocol/Server/DebugAdapterBase.cs
This commit sends the initialized event *after* the initializeRequest response (that sends capabilities info).  This was recommended by @isidorn in issue http://github.com/Microsoft/vscode/issues/4567.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershelleditorservices/204)
> Fixes #196 - reorder messages to prevent dbgr fail to start

- src/PowerShellEditorServices/Debugging/VariableDetails.cs
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Utility/Extensions.cs
Catch exceptions when calling ToString().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershelleditorservices/216)
> Fix for vscode-powershell issue 168.

- appveyor.yml
- docs/extensions.md
- src/PowerShellEditorServices.Protocol/LanguageServer/EditorCommands.cs
- src/PowerShellEditorServices.Protocol/PowerShellEditorServices.Protocol.csproj
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServerEditorOperations.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServerSettings.cs
- src/PowerShellEditorServices/Extensions/CmdletInterface.ps1
- src/PowerShellEditorServices/Extensions/EditorCommand.cs
- src/PowerShellEditorServices/Extensions/EditorContext.cs
- src/PowerShellEditorServices/Extensions/EditorObject.cs
- src/PowerShellEditorServices/Extensions/EditorWorkspace.cs
- src/PowerShellEditorServices/Extensions/ExtensionService.cs
- src/PowerShellEditorServices/Extensions/FileContext.cs
- src/PowerShellEditorServices/Extensions/IEditorOperations.cs
- src/PowerShellEditorServices/Language/CompletionResults.cs
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Session/EditorSession.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
- src/PowerShellEditorServices/Session/SessionPSHost.cs
- src/PowerShellEditorServices/Workspace/BufferPosition.cs
- src/PowerShellEditorServices/Workspace/BufferRange.cs
- src/PowerShellEditorServices/Workspace/FilePosition.cs
- src/PowerShellEditorServices/Workspace/ScriptFile.cs
- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
- test/PowerShellEditorServices.Test/Extensions/ExtensionServiceTests.cs
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
This change introduces a new PowerShell-based API that allows scripts and
modules to extend the behavior of the host editor.  Scripts can either
automate the editor directly or register commands that can later be
invoked by the user.  The ExtensionService provides this behavior for any
PowerShellContext by injecting a new variable '$psEditor' into the
session.
This version of the API is very early and will be expanded upon in future
releases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershelleditorservices/214)
> Introduce new editor extensibility API

- src/PowerShellEditorServices/Extensions/EditorObject.cs
This change fixes the EditorObject.RegisterCommand function to pass
through the return value of the ExtensionService.RegisterCommand function
so that the Register-EditorCommand cmdlet writes the correct verbose
output depending on whether the command was already registered.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershelleditorservices/217)
> Fix return value of EditorObject.RegisterCommand

- CHANGELOG.md
- README.md
- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershelleditorservices/219)
> Prepare 0.6.0 release

- docs/guide/extensions.md
- scripts/BuildDocs.ps1
Thanks @gerane!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershelleditorservices/225)
> Fix #223: Wrong InsertText call in extension docs

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
This change fixes an issue in the LanguageServer where the length of time
that it takes to evaluate the extension API script can cause the
"initialize" request to not complete.  This leaves the VS Code language
server client in an initializing state where no language features will
work for the rest of the session.  The fix is to execute the extension API
script after the "initialize" handler has been registered.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershelleditorservices/229)
> Fix #221: Occasional init hang in LanguageServer

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
This change fixes an issue where $host.UI prompt functions do not return
the user's response when run inside of PowerShell editor commands.  This
was caused by the HandleInvokeExtensionCommand method returning a Task
that did not complete until after the command completed.  The fix was to
not await on completion of the command so that the prompt response has a
chance to come through.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershelleditorservices/230)
> Fix #222: Prompt functions hang in editor commands

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Language/CommandHelpers.cs
- src/PowerShellEditorServices/Language/LanguageService.cs
- src/PowerShellEditorServices/Language/SymbolDetails.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
This change fixes an issue where the language server can sometimes crash
when the user has configured their $ErrorActionPreference variable to
"Stop" in the language server's session.  The fix is to refactor existing
code to use a common code path that handles RuntimeExceptions
appropriately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershelleditorservices/234)
> Fix #232: Language server crashes when ErrorActionPreference is "Stop"

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
LanguageServer.CreateCompletionItem was causing a editor host crash because it (er *I*) was injecting tooltip text (returned by the PS engine) into a regex pattern without escaping it.  One of the completion items was 'Notepad++.exe' which resulted in a regex parsing error.  Would like to add a test for this at some point but need to think on it.  CreateCompletionItem is private.
Fixes #240
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershelleditorservices/241)
> Need to escape regex pattern with external component.

- src/PowerShellEditorServices/Extensions/BuiltInCommands.ps1
This change adds the following built-in Editor Commands
- PowerShellEditorServices.OpenEditorProfile: Opens the current
Editor's profile. Uses $profile so should work when other Editors use
PSES.
- PowerShellEditorServices.OpenProfileList: Prompts user with a list of
Profiles to open.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershelleditorservices/254)
> Add Editor Commands for opening Profiles

- .gitignore
The generated PowerShellEditorServices.NoNano module folder kept showing up as untracked.  I see you have the root level PowerShellEditorServices folder excluded so I just added another entry for the PowerShellEditorServices.NoNano folder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershelleditorservices/259)
> Added NoNano dir to .gitignore file.

- src/PowerShellEditorServices.Host/EditorServicesHost.cs
It is handy to know which version of the OS we are running on and what architecture for both the extension hosts and the OS.  Also, converted from \r\n to Environment.NewLine just in case this code runs on Linux/MacOSX someday.  :-)
This outputs to the log file:
```
PowerShell Editor Services Host v0.0.0.0 starting (pid 2864)...
Host application details:
Name:      Visual Studio Code Host
ProfileId: Microsoft.VSCode
Version:   0.6.1
Arch:      64-bit
Operating system details:
Version: Microsoft Windows NT 10.0.10586.0
Arch:    64-bit
```
BTW this does use the C# 6 string interpolation feature but I think we already agreed that using C# 6 features was fair game, right?  There are some places where the `null conditional` operator would be real handy - like `session?.Dispose();`
---
This …
> Added OS info to log file.

- CHANGELOG.md
- appveyor.yml
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
This release fixes a few issues that appeared since the 0.6.1 release:
- #264: Variable and parameter IntelliSense broken in VS Code 1.4.0
- #240: Completion item with regex metachars can cause editor host to crash
- #232: Language server sometimes crashes then $ErrorActionPreference = "Stop"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershelleditorservices/267)
> Release 0.6.2

- CHANGELOG.md
- appveyor.yml
- module/PowerShellEditorServices/PowerShellEditorServices.psd1
- module/PowerShellEditorServices/PowerShellEditorServices.psm1
- src/PowerShellEditorServices.Host/EditorServicesHost.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/Scope.cs
- src/PowerShellEditorServices/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Language/AstOperations.cs
- src/PowerShellEditorServices/Language/FindSymbolsVisitor2.cs
- test/PowerShellEditorServices.Test.Host/ServerTestsBase.cs
- test/PowerShellEditorServices.Test/Language/LanguageServiceTests.cs
- Fixed PowerShell/vscode-powerShell#246: Restore default PSScriptAnalyzer ruleset
- Fixed PowerShell/vscode-powershell#248: Extension fails to load on Windows 7 with PowerShell v3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershelleditorservices/277)
> Release 0.7.1

- CHANGELOG.md
- appveyor.yml
- module/PowerShellEditorServices/PowerShellEditorServices.psd1
- src/PowerShellEditorServices.Protocol/MessageProtocol/MessageDispatcher.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Language/FindDotSourcedVisitor.cs
- src/PowerShellEditorServices/Session/EditorSession.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
- src/PowerShellEditorServices/Workspace/Workspace.cs
- test/PowerShellEditorServices.Test.Host/ServerTestsBase.cs
Fixes for bugs that users reported in the 0.7.0 and 0.7.1 releases:
- Fix #284: PowerShellContext.AbortException crashes when called more than once
- Fix #285: PSScriptAnalyzer settings are not being passed to Invoke-ScriptAnalyzer
- Fix #287: Language service crashes when invalid path chars are used in dot-sourced script reference
> Release 0.7.2

- src/PowerShellEditorServices/Analysis/AnalysisService.cs
This request came in on the VSCode-powershell project: https://github.com/PowerShell/vscode-powershell/issues/336.  Seems reasonable to me.
> Add PSMisleadingBacktick rule to the default ruleset.

- src/PowerShellEditorServices.Protocol/DebugAdapter/InitializeRequest.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/SetBreakpointsRequest.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/SetFunctionBreakpointsRequest.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapterBase.cs
- src/PowerShellEditorServices/Debugging/BreakpointDetails.cs
- src/PowerShellEditorServices/Debugging/BreakpointDetailsBase.cs
- src/PowerShellEditorServices/Debugging/CommandBreakpointDetails.cs
- src/PowerShellEditorServices/Debugging/DebugService.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
Add support plain Hit Count breakpoints as well as combination of Condition and Hit Count.
> Add support for Hit Count breakpoints

- .gitmodules
- PowerShellEditorServices.NoNano.sln
EditorServices does not use PSScriptAnalyzer `C#` APIs. Instead it calls `Invoke-ScriptAnalyzer` to get diagnostic markers.
> Remove PSScriptAnalyzer submodule

- src/PowerShellEditorServices.Protocol/LanguageServer/PowerShellVersionRequest.cs
- src/PowerShellEditorServices.Protocol/PowerShellEditorServices.Protocol.csproj
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Nano.PowerShellEditorServices.csproj
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Session/PowerShellContext.cs
- src/PowerShellEditorServices/Session/PowerShellVersionDetails.cs
- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
This change introduces a new PowerShellVersionDetails class which contains
additional details about the version and runtime of the current PowerShell
session: version, GitCommitId, edition, and processor architecture.  A new
protocol request and response pair was added for gathering this version
information from the editor client.
This will be used to show version information for the current PowerShell session in the host editor.
> Add PowerShellVersionDetails class and PowerShellVersionRequest

- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
This change fixes an issue where script output for very small scripts is
not being written out reliably before the debug adapter terminates.  The
fix is to add an extra output flush before sending the TerminatedEvent
back to the client.  This fix is temporary until we get the REPL
integration online.
Resolves #138.
Resolves PowerShell/vscode-powershell#284.
> Fix issue with debugger output not being written for short scripts

- src/PowerShellEditorServices.Protocol/LanguageServer/PowerShellVersionRequest.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
- src/PowerShellEditorServices/Session/PowerShellVersionDetails.cs
This change makes some slight tweaks to the PowerShell version and
architecture gathering code to improve the user experience in the host
editors which display those values.
> Improve PowerShell version and architecture gathering

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServerEditorOperations.cs
- src/PowerShellEditorServices/Extensions/EditorWorkspace.cs
- src/PowerShellEditorServices/Extensions/FileContext.cs
- src/PowerShellEditorServices/Extensions/IEditorOperations.cs
- src/PowerShellEditorServices/Language/FindDotSourcedVisitor.cs
- src/PowerShellEditorServices/Session/SessionPSHostUserInterface.cs
- src/PowerShellEditorServices/Workspace/Workspace.cs
- test/PowerShellEditorServices.Test/Extensions/ExtensionServiceTests.cs
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
- test/PowerShellEditorServices.Test/Session/WorkspaceTests.cs
- File preview Uris crash the language server
- Remove timeout for PSHostUserInterface prompts
- Add workspace path information to psEditor.Workspace API
- Set session's current directory to the workspace path
- Dot-source reference detection should ignore ScriptBlocks
> Various fixes and improvements for 0.8.0

- src/PowerShellEditorServices/Session/EditorSession.cs
Tried out the latest code on PowerShell v3 (Windows 8), noticed that Script Analyzer wasn't being loaded because we didn't remove the v3 restriction.  Removing it now that Script Analyzer fully supports v3 :)
> Remove limitation for use of PSScriptAnalyzer on PowerShell 3.0

- src/PowerShellEditorServices.Protocol/LanguageServer/ProjectTemplate.cs
- src/PowerShellEditorServices.Protocol/Messages/PromptEvents.cs
- src/PowerShellEditorServices.Protocol/PowerShellEditorServices.Protocol.csproj
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices.Protocol/Server/PromptHandlers.cs
- src/PowerShellEditorServices/Console/ChoiceDetails.cs
- src/PowerShellEditorServices/Console/ChoicePromptHandler.cs
- src/PowerShellEditorServices/Console/ConsoleChoicePromptHandler.cs
- src/PowerShellEditorServices/Nano.PowerShellEditorServices.csproj
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Session/EditorSession.cs
- src/PowerShellEditorServices/Session/SessionPSHostUserInterface.cs
- src/PowerShellEditorServices/Templates/TemplateDetails.cs
- src/PowerShellEditorServices/Templates/TemplateService.cs
- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
- test/PowerShellEditorServices.Test/Console/ChoicePromptHandlerTests.cs
This change introduces a new TemplateService which uses the new Plaster
module to provide the following features:
1. Listing available Plaster templates on the user's machine, both
built-in and contained within other PowerShell modules
2. Creating new projects from Plaster templates
This functionality is exposed up through the language service by the
powerShell/getProjectTemplates and powerShell/newProjectFromTemplate
request types.
> Add TemplateService for Plaster integration

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
When a user closes a file in a workspace, the extension does not clear the diagnostic markers corresponding to the closed file from the Problems window in vscode.
Fixes PowerShell/vscode-powershell#314
> Clear diagnostic markers after file is closed

- scripts/FetchLatestBuild.ps1
- src/PowerShellEditorServices/Language/LanguageService.cs
This change fixes an issue which appears sometimes when getting
IntelliSense results within a DSC resource.  The completion results return
a replacement range of -1 which causes an exception in our BufferRange
class.  This fix catches and logs this exception so that the session may
continue.
> Fix #323: DSC IntelliSense can cause language service to crash

- src/PowerShellEditorServices/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Templates/TemplateService.cs
This change fixes an issue with the loading of both the PSScriptAnalyzer
and Plaster modules.  We were simply using Import-Module without
specifying a version to be loaded.  Apparently PowerShell prioritizes the
PSModulePath order over the module version order so there are instances
where an older version of one of these module will be loaded even though a
newer version is available at a different location on the machine.
This change adds extra logic to sort the list of returned modules so that
the latest version of the module is always loaded.
> Fix #325: Module dependency loading should pick latest module version

- src/PowerShellEditorServices/Debugging/DebugService.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
- src/PowerShellEditorServices/Session/PowerShellVersionDetails.cs
- src/PowerShellEditorServices/Session/RemoteFileManager.cs
This change adds new behavior to the DebugService which enables it to
gather the listing of any source code that is being executed outside of a
script file when the debugger hits a breakpoint.  This is useful for
allowing the user to step through code in this type of scenario.
Currently this is being used for an unreleased feature in PowerShell 6.0
which allows you to step into ScriptBlocks run against remote sessions
with Invoke-Command.
> Fetch script listings for debugger stop events with no ScriptName

- README.md
... Or we could just remove the whole section on cloning since it is just a simple clone operation now.  What do you think?
> Remove submodule instructions from README.md.

- src/PowerShellEditorServices/Language/AstOperations.cs
- src/PowerShellEditorServices/Language/FindSymbolsVisitor.cs
- src/PowerShellEditorServices/Language/SymbolType.cs
This update will show the list of keys present in a psd1 file when a user invokes `Go to Symbols in File... (Ctrl+Shift+O)` on an psd1 file.
> Provide symbol outline for psd1 files

- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices/Session/RemoteFileManager.cs
- src/PowerShellEditorServices/Utility/Logger.cs
This change adds new behavior to RemoteFileManager so that a 'psedit'
command will be added to all sessions for the purpose of loading local or
remote files in the debugging experience.  For now the remotely opened
files do not have saved contents propagated to the remote machine but that
will be added shortly.
> Implement psedit command for remote file loading

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Analysis/AnalysisService.cs
Also improves the code formatting experience as the diagnostics now potentially run in a separate runspace and hence do not block code formatting request.
> Make analysis service methods async

- src/PowerShellEditorServices.Protocol/LanguageServer/Diagnostics.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Workspace/Workspace.cs
Apparently I've had these sitting around for a while and forgot to send a PR...
> Minor 0.9.0 fixes

- src/PowerShellEditorServices/Session/PowerShellContext.cs
This change adds a catch for the InvalidCastException when gathering the
user's prompt string in the case where their prompt function returns a
value other than a string.  In this case a default prompt is returned.
This change also improves the way we write prompts for the debugger.
Instead of writing out the prompt each time the debugger stops, we write
out the details about the breakpoint that was hit, if any.  We also try to
preserve any session context at the beginning of the prompt string like
the remote computer name or process ID.
Fixes #339.
> Handle non-string return values from the user's prompt function

- src/PowerShellEditorServices/Session/PowerShellVersionDetails.cs
This change fixes an issue caused by a recent change in the VS Code
extension which wiped out all of the environment variables in the process.
That particular issue has now been fixed but it's still good to guard
against this problem in the future.  This change adds a null check to
ensure that we don't throw a NullReferenceException in future occurrences
of the issue.
> Fix #346: GetVersionDetails failing due to empty environment variable

- src/PowerShellEditorServices/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Nano.PowerShellEditorServices.csproj
This change fixes the way that the PSScriptAnalyzer module gets loaded in
the new asynchronous AnalysisService.  Since we changed to using the
InitialSessionState to load the module, we were unable to specify the
exact version of the module we needed.  This change goes back to an
explicit Import-Module across the runspaces in the RunspacePool.
> Fix PSScriptAnalyzer module loading in new async AnalysisService

- src/PowerShellEditorServices/Analysis/AnalysisService.cs
The crash was very likely due to deferred execution when enumerating through the diagnostic records returned by PowerShell invocation.
> Fix crash caused when formatting document

- PowerShellEditorServices.build.ps1
Prevents the build failing if the code has never before been built, fixes #358.
> Updated build script to test for project asset files

- PowerShellEditorServices.build.ps1
- src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/NamedPipeClientChannel.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/MessageDispatcher.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServerBase.cs
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Session/PowerShellContext.cs
- test/PowerShellEditorServices.Test.Host/DebugAdapterTests.cs
- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
- test/PowerShellEditorServices.Test/Session/PowerShellContextTests.cs
These changes help the CI build fail far less often and prevent it from spewing compiler warnings.
> Clean up CI tests and build output

- src/PowerShellEditorServices/Analysis/AnalysisService.cs
Having multiple runspaces crashed scriptanalyzer invocation because of the following two issues:
* PSCmdlet.WriteOutput being called from another thread than Begin/Process
* CompositionContainer.ComposeParts complaining that "...Only one batch can be composed at a time"
We used multiple runspaces in the first place because PSSA was slow and having multiple runspaces sped things up by executing PSSA in a parallel manner. But having multiple runspaces causes a lot of issues which are hard to debug. Also, PSSA has become significantly fast compared to the previous version and thereby having just one runspace should not deteriorate the performance significantly. And on the positive side we do not have to deal with the aforementioned crashes.
> Fix crashes caused by multiple analysis runspaces

- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
- src/PowerShellEditorServices/Session/RemoteFileManager.cs
- src/PowerShellEditorServices/Session/RunspaceDetails.cs
- src/PowerShellEditorServices/Session/SessionDetails.cs
This change adds new behavior that makes the detection of sudden runspace
changes much more reliable.  These changes were particularly necessary for
detecting when we start debugging a runspace in a remote session since we
don't get a PushRunspace notifications when that happens.
This change also improves how we gather the prompt string just after a
command is executed.
> Improve detection of runspace changes

- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
- test/PowerShellEditorServices.Test/Session/PowerShellContextTests.cs
Renamed to ExecuteScriptWithArgs and check if "script" is a filename before attempting to escape wildcard chars in path.
> Modify ExecuteScriptAtPath to handle arb script.

- src/PowerShellEditorServices/Console/ConsoleService.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
This change fixes the ComputerName prefix for prompts shown in remote
sessions.  Recent changes caused it to be lost.
> Fix remote prompt ComputerName display

- src/PowerShellEditorServices/Console/ConsoleReadLine.cs
- src/PowerShellEditorServices/Session/SessionPSHostUserInterface.cs
This change resolves PowerShell/vscode-powershell#543 which reports that
characters typed using AltGr combinations cannot be typed into the
integrated console.  It also resolves the console's inability to write
Unicode characters as output by setting the console's OutputEncoding
correctly.
> Fix integrated console input and output of Unicode characters

- src/PowerShellEditorServices/Language/AstOperations.cs
- src/PowerShellEditorServices/Language/LanguageService.cs
This change adds IntelliSense (code completion) capabilities while the
debugger is stopped through invoking the TabCompletion2 command.
Resolves PowerShell/vscode-powershell#566.
> Enable editor IntelliSense while stopped at a breakpoint

- src/PowerShellEditorServices/Session/PowerShellContext.cs
This change adds a try/catch around our invocation of Set-ExecutionPolicy
to catch a CmdletInvocationException if a global ExecutionPolicy has
already been set on the machine.
Resolves #192.
Resolves PowerShell/vscode-powershell#454.
> Handle exceptions when calling Set-ExecutionPolicy

- module/PowerShellEditorServices/PowerShellEditorServices.psm1
- src/PowerShellEditorServices.Host/EditorServicesHost.cs
This change adds initial support for feature flags in the
EditorServicesHost so that we can enable new experimental features
conditionally while maintaining current behavior for most users.
> Add initial support for feature flags

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
This change causes VS Code to preserve PowerShell's original
CommandCompletion result sort order by creating SortText entries for every
completion result, not just parameters.
Resolves PowerShell/vscode-powershell#579.
> Preserve PowerShell's CommandCompletion result sort order in VS Code

- src/PowerShellEditorServices.Protocol/LanguageServer/TextDocument.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Session/RemoteFileManager.cs
This change enables the saving of files opened from a remote session using
the psedit command.  When the editor saves the file contents it sends a
DidSaveTextDocumentNotification to the language server which in turn sends
the document's contents back to the remote session to be saved in the
original file.
Resolves PowerShell/vscode-powershell#583.
> Enable saving remote files opened with psedit

- src/PowerShellEditorServices/Console/ConsoleReadLine.cs
- src/PowerShellEditorServices/Console/ConsoleService.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
- src/PowerShellEditorServices/Session/SessionPSHostUserInterface.cs
This change uses a new strategy for providing a quasi-async
Console.ReadKey implementation so that key handling works better on Linux
and macOS.  This should eliminate issues where keys and escape sequences
were being echoed incorrectly.  It should also eliminate the issue where
the backspace key is unusable on these platforms.
Resolves PowerShell/vscode-powershell#533.
Resolves PowerShell/vscode-powershell#542.
> Use new strategy for ConsoleReadLine.ReadKeyAsync to fix macOS and Linux issues

- src/PowerShellEditorServices.Protocol/DebugAdapter/StackFrame.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/StoppedEvent.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices/Debugging/DebugService.cs
- src/PowerShellEditorServices/Debugging/StackFrameDetails.cs
- test/PowerShellEditorServices.Test.Host/DebugAdapterTests.cs
This change causes the column number of the debugger's currently stopped
position to be passed through with the top stack frame.  This allows VS
Code's debugger UI to show an indicator that points to where the debugger
stopped when stepping through code.
Resolve PowerShell/vscode-powershell#616
> Report column number in stack frame when debugger stops

- src/PowerShellEditorServices/Debugging/DebugService.cs
This doesn't fix the issue with all the global variables appearing in `Auto`.
Fixes PowerShell/vscode-powershell#614.
> Fix issue w/Auto variables empty in script scope.

- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
This change enables the debugging of untitled script files by executing
their contents directly, not as a script file.  Since the language server
has already received the contents of the untitled file, we can easily
access them in the server for execution purposes.
Part of PowerShell/vscode-powershell#555.
> Enable debugging of untitled script files

- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
This change fixes a crash that occurs when a breakpoint is hit at a time
when the debugger is not active.  This is caused by some event handlers
being registered prematurely in the DebugAdapter before it gets activated
by VS Code.
Fixes PowerShell/vscode-powershell#620.
> Fix crash when breakpoint gets hit outside of debug mode

- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Console/ChoicePromptHandler.cs
- src/PowerShellEditorServices/Console/ConsoleService.cs
- src/PowerShellEditorServices/Session/ExecutionOptions.cs
- src/PowerShellEditorServices/Session/ExecutionStatus.cs
- src/PowerShellEditorServices/Session/ExecutionStatusChangedEventArgs.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
- src/PowerShellEditorServices/Session/SessionPSHostUserInterface.cs
- src/PowerShellEditorServices/Templates/TemplateService.cs
This change fixes a general class of problems in the integrated console
experience where commands that were executed internally (like extension
commands or running Plaster templates) do not interrupt the command
prompt, causing future input to be written over previous output lines.
The fix is to have the command prompt be interrupted by any commands
which write output or errors to the host.
Fixes #411.
> Interrupt integrated console command prompt when commands are executed

- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
This change removes some code that was causing an extra command prompt
string to be printed to the integrated console when running an
interactive debugging session.  It also makes the termination of such a
session more reliable.
Resolves #422.
> Remove extra prompt string added to interactive debugging session

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
This change fixes a host crash which occurs when the user tries to
perform a symbol operation (like Go to Definition or Find References) in
an untitled script file.  The fix is to not try and convert an untitled
file's path to a Uri.
Resolves PowerShell/vscode-powershell#645
> Fix crash when performing symbol operations in untitled file

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Language/CommandHelpers.cs
This change mitigates seemingly intermittent IntelliSense slowness by
preventing Get-Command and Get-Help from being called on cmdlets from
the PowerShellGet and PackageManagement modules.  Something in the
PackageManagement module is causing completions to be returned at 10x
delay when that module is loaded.  If the module is removed from the
session, completions go back to their normal duration.
By avoiding calling Get-Command on these cmdlets, we avoid loading
PackageManagement when the user types a string like `Get-P` which
incidentally happens to make VS Code see the `Get-Package` cmdlet and
try to resolve its details.
This fix is temporary and will be removed in the future once
https://github.com/OneGet/oneget/issues/275 is fixed.
Related to PowerShell/vscode-powershell#647
> Temporarily mitigate intermittent IntelliSense slowness

- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
This change fixes a hang that occurs when the user starts the debugger
right when the PowerShell session is still initializing.  This is caused
by a call to PowerShellContext.SetWorkingDirectory which isn't
respecting the current state of the runspace.  The fix is to ask for a
RunspaceHandle to ensure that the runspace is free before attempting to
set the working directory.
Resolves PowerShell/vscode-powershell#632
> Fix debugger startup hang when session still initializing

- src/PowerShellEditorServices/Language/AstOperations.cs
This change fixes an issue where calling TabExpansion2 while debugging
will sometimes cause a crash due to it returning an ErrorRecord instead
of a CommandCompletion.  The fix is to expect the possibility of the
ErrorRecord and log it when it occurs.
Resolves #427.
> Fix occasional crash when requesting IntelliSense while debugging

- src/PowerShellEditorServices.Host/EditorServicesHost.cs
Any chance we can go back to this? This is nicer because it pops the attach a debugger UI.  You don't have to track down the PID.  You only have to select which instance of VS you want to use to debug.
> How about popping UI to attach the debugger?

- .vscode/launch.json
- PowerShellEditorServices.Common.props
This change turns on the portable PDB format for the primary assemblies
in the project so that they can be debugged in VS Code.  Version 1.9 of
the C# extension added a new debugger type, `clr`, which allows you to
debug 64-bit Full CLR apps when portable PDBs are in use.
> Enable debugging of PowerShell Editor Services using VS Code

- src/PowerShellEditorServices/Console/ConsoleService.cs
This change fixes PowerShell/vscode-powershell#618 which reports that
empty input lines are being added to command history in the integrated
console.  This change updates the command input logic to skip sending
empty lines to the command executor.
> Don't add empty input lines to command history

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
This wasn't being set so our Intellisense was showing props like so:
Props show as w/this PR:
> Set CompletionItemKind for properties.

- src/PowerShellEditorServices.Protocol/LanguageServer/Definition.cs
- src/PowerShellEditorServices.Protocol/LanguageServer/References.cs
- src/PowerShellEditorServices.Protocol/LanguageServer/TextDocument.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
These changes got left out of #445
> Fix definition and reference request parameters

- module/PowerShellEditorServices/PowerShellEditorServices.psd1
- module/PowerShellEditorServices/PowerShellEditorServices.psm1
I'm not sure about the noun on this command.  Open to suggestions.  But if we take this then the VSCode-PowerShell issue template simplifies to having folks run the command from the IC and paste results into issue.  Another option would be to have them open the logs and copy the version info from there.
Also, I don't have a Mac so the command to get OS version `lsb_release -d` needs to be tested and potentially replaced with the correct command.
> Add command to get pertinent version info.

- src/PowerShellEditorServices/Session/PowerShellContext.cs
This change causes both errors and object output to be written to the
host when profiles are being loaded.  Users who had issues in their
profile scripts thought that the scripts weren't being loaded when in
fact there were errors not being displayed.  Also, users using
Write-Output in their profile scripts did not see that output.  This
change makes the PSES host consistent with the PowerShell ConsoleHost,
writing both forms of output when loading profile scripts.
Resolves PowerShell/vscode-powershell#689
Resolves PowerShell/vscode-powershell#663
> Errors and output written during profile loading don't show in host

- src/PowerShellEditorServices.Protocol/LanguageServer/StartDebuggerEvent.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Debugging/DebugService.cs
This change is part of the fix for PowerShell/vscode-powershell#619
which states that hitting a breakpoint in the integrated console does
not activate the debugger in VS Code.  The fix is to check whether a
debugger client is connected when a breakpoint is hit, and if not, send
a notification through the language server to have the editor connect
its debugger client.
> Breakpoints hit when debugger isn't active now notify editor

- PowerShellEditorServices.build.ps1
This change updates the project's build script to correctly handle
version numbers without prerelease tags like "-beta".
> Fix versioning in build script

- src/PowerShellEditorServices/Language/AstOperations.cs
- src/PowerShellEditorServices/Language/FindDeclarationVisitor.cs
- src/PowerShellEditorServices/Language/FindDeclartionVisitor.cs
- src/PowerShellEditorServices/Language/SymbolReference.cs
- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
- test/PowerShellEditorServices.Test.Host/TestFiles/FindReferences.ps1
- test/PowerShellEditorServices.Test.Host/TestFiles/VariableDefinition.ps1
Resolves PowerShell/vscode-powershell#710
> Fix finding variable definitions in workspace

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Analysis/AnalysisService.cs
This PR partly fixes the performance issue mentioned in PowerShell/vscode-powershell#771. I have identified the following 3 reasons why performance is poor for help completion in large script (having 100+ functions). 
1. Whenever a user makes a change to the file, the server starts analyzing the file for any diagnostic markers. For a large script, `FunctionDefinitionAst.GetCommentHelp()` seems to be the bottleneck, which is called by the `PSProvideCommentHelp` rule. If you disable this rule, analysis results are obtained almost instantaneously, except for the first time when a file is analyzed. 
2. Our implementation for help completion was inefficient, in the sense, that it relies on running `PSProvideCommentHelp` rule to obtain the help snippet. When a user types the trigger characters, …
> Fix help completion performance for large files

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Language/LanguageService.cs
Resolves PowerShell/vscode-powershell#763
> Auto-complete comment help in function body

- .vscode/tasks.json
- README.md
- module/PowerShellEditorServices/PowerShellEditorServices.psm1
- src/PowerShellEditorServices.Host/EditorServicesHost.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Console/ConsoleService.cs
- src/PowerShellEditorServices/Language/FindDeclarationVisitor.cs
- src/PowerShellEditorServices/Session/EditorSession.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
- src/PowerShellEditorServices/Session/SessionPSHost.cs
- test/PowerShellEditorServices.Test/Console/ConsoleServiceTests.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
- test/PowerShellEditorServices.Test/Extensions/ExtensionServiceTests.cs
- test/PowerShellEditorServices.Test/Language/LanguageServiceTests.cs
- test/PowerShellEditorServices.Test/PowerShellContextFactory.cs
- test/PowerShellEditorServices.Test/Session/PowerShellContextTests.cs
This change kicks off a larger refactoring of how PowerShell Editor Services is initialized.  The goal here is to move toward a more granular interface design which can be exposed as an extensibility API.  I'll be working toward this incrementally over the next few releases.
> Refactor runspace creation to enable more design improvements

- src/PowerShellEditorServices.Protocol/Client/DebugAdapterClientBase.cs
- src/PowerShellEditorServices.Protocol/Client/LanguageClientBase.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/MessageDispatcher.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/ProtocolEndpoint.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapterBase.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServerBase.cs
This is a small step in a larger refactoring that I should be sending a PR for today.  Basically I just needed a way to register message handlers without having an established LanguageServer/DebugServer.  Didn't make sense to have all that behavior wrapped up together anyway.
> Decouple MessageDispatcher from ProtocolEndpoint

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Workspace/ScriptFileMarker.cs
This change adds the PSScriptAnalyzer rule name to any marker messages
that are returned so that it's easy to know which rule to suppress or
disable in settings.  It also makes the rule source more clear in marker
messages, distinguishing between PowerShell syntax markers and
PSScriptAnalyzer's semantic markers.
Resolves PowerShell/vscode-powershell#781.
> Include PSScriptAnalyzer rule name in marker message

- src/PowerShellEditorServices/Language/LanguageService.cs
This change catches a RuntimeException that may occur when the user
types out the name of a command or script which uses an invalid
parameter binding attribute.  This exception will be logged and the
signatures just won't be displayed for that command.
Resolves #462.
> Catch RuntimeException when getting signatures with bad attribute

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Workspace/ScriptFile.cs
Resolves #478
Comment help auto-completion does not work correctly for block comment ('<#') trigger characters at the beginning of function body - the auto-completed help does not contain the parameters. When the user types '<', it invalidates the following param block such that the parser does not recognize it as a param block, which results in the help not containing the parameters. 
```powershell
function foo {
<    
param($param1)
}
```
> Fix help completion at the beginning of function body

- src/PowerShellEditorServices/Console/ConsoleService.cs
This change fixes an issue in the integrated console where the result of
a user's custom prompt function would not be interpreted correctly,
causing the default prompt string of "PS>" to be written out when it
wasn't needed.  The fix is to expect a PSObject result rather than
object so that we can evaluate the inner object's type correctly.
Resolves PowerShell/vscode-powershell#808.
> Fix evaluation of prompt function output to remove unneeded "PS>"

- src/PowerShellEditorServices/Workspace/Workspace.cs
This change fixes an issue where the Workspace's file enumeration logic
would throw an UnauthorizedAccessException when it encounters an
unaccessible file or path.  The fix is to make the file enumeration code
more robust so that it catches these exceptions and continues
enumerating as far as it can.
Resolves PowerShell/vscode-powershell#813.
> Catch UnauthorizedAccessException in file path enumeration

- src/PowerShellEditorServices.Host/EditorServicesHost.cs
- src/PowerShellEditorServices.Protocol/Client/DebugAdapterClientBase.cs
- src/PowerShellEditorServices.Protocol/Client/LanguageServiceClient.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/ChannelBase.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/NamedPipeClientChannel.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/NamedPipeServerChannel.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/NamedPipeServerListener.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/ServerListenerBase.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/StdioClientChannel.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/StdioServerChannel.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/StdioServerListener.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/TcpSocketClientChannel.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/TcpSocketServerChannel.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/TcpSocketServerListener.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/ProtocolEndpoint.cs
- src/PowerShellEditorServices/Session/RemoteFileManager.cs
- test/PowerShellEditorServices.Test.Host/DebugAdapterTests.cs
- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
This change refactors our existing channel model to move all connection
logic outside of the ChannelBase implementations so that the
language and debug client/service pairs can be simplified.  This change
also allows us to remove a long-standing hack in our Host unit tests
which added an artifical delay to give the channel and MessageDispatcher
time to get established.
> Establish new channel connection model using server listeners

- module/PowerShellEditorServices/Commands/Public/Find-Ast.ps1
This fixes an issue where the before switch wasn't searching in the correct order.
> Fix before switch parameter for Find-Ast

- src/PowerShellEditorServices.Host/EditorServicesHost.cs
- src/PowerShellEditorServices.Host/PSHost/ProtocolPSHostUserInterface.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Components/IComponentRegistry.cs
- src/PowerShellEditorServices/Components/IComponentRegistryExtensions.cs
- src/PowerShellEditorServices/Extensions/EditorObject.cs
- src/PowerShellEditorServices/Extensions/ExtensionService.cs
- src/PowerShellEditorServices/Session/Host/EditorServicesPSHostUserInterface.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
- test/PowerShellEditorServices.Test.Host/OutputReader.cs
- test/PowerShellEditorServices.Test/Extensions/ExtensionServiceTests.cs
- Remove unnecessary newline output in the Integrated Console
- Run Selection (F8) was not wired up correctly (thanks @SeeminglyScience!)
- IComponentRegistry should be exposed on $psEditor as Components property
- Change IComponentRegistry methods to enable non-generic method calls in PowerShell
> Miscellaneous fixes to latest improvements

- src/PowerShellEditorServices.Host/CodeLens/PesterCodeLensProvider.cs
- src/PowerShellEditorServices/Symbols/PesterDocumentSymbolProvider.cs
This change fixes a couple of issues with the new Pester CodeLens
feature.  One is that the "Describe" function is not recognized when it
is not cased exactly like that and the other is that the language server
has an internal error that causes it to hang when typing Describe blocks
into a script.
Resolves PowerShell/vscode-powershell#850
Resolves PowerShell/vscode-powershell#851
> Fix crash and hang issues with Pester CodeLens feature

- src/PowerShellEditorServices.Protocol/DebugAdapter/Variable.cs
- src/PowerShellEditorServices/Debugging/DebugService.cs
> Fix variable's 'add to watch' feature.

- module/docs/ConvertFrom-ScriptExtent.md
- module/docs/ConvertTo-ScriptExtent.md
- module/docs/Find-Ast.md
- module/docs/Import-EditorCommand.md
- module/docs/Join-ScriptExtent.md
- module/docs/PowerShellEditorServices.Commands.md
- module/docs/Register-EditorCommand.md
- module/docs/Set-ScriptExtent.md
- module/docs/Test-ScriptExtent.md
- module/docs/Unregister-EditorCommand.md
This change fixes some mistakes in the help documents for the Commands module and adds additional examples.
> Update help docs for Commands module

- src/PowerShellEditorServices.Protocol/DebugAdapter/StackFrame.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/StackTraceRequest.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices/Debugging/DebugService.cs
- src/PowerShellEditorServices/Debugging/StackFrameDetails.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
This PR addresses two bugs.  First the missing line info was due to use passing back null when we didn't have end line/col info.  The protocol claims that should work.  But when I changed the end line/col to reflect the same values as the start line/col (assuming the end values were null - not set) then the callstack started to display the line info.  It is  a bit weird but the very first frame in some cases contains a col other than 0.
The second bug was that the call stack was getting duplicated.  I implemented the new stackTraceRequest for paging stack frames back to VSCode and now that bug is fixed.
I tried to implement StackFrame.PresentationHint == "subtle" for script outside the initial working directory.  Do you have a better way to get the workspaceRoot path in the debugger?  I …
> Fix for vscode-powershell #837 callstack missing line info. 

- src/PowerShellEditorServices.Host/EditorServicesHost.cs
This change causes all unhandled exceptions to crash the server so that
the user is not left with an inoperative language service.  This was the
expected behavior before the recent redesign changed how the exception
gets propagated all the way back to the EditorServicesHost.  The host
will now throw the unhandled exception from the WaitForCompletion
method causing the process to exit.
> Server should crash on unhandled exceptions in message loop

- module/PowerShellEditorServices/PowerShellEditorServices.psm1
- src/PowerShellEditorServices.Host/EditorServicesHost.cs
This change finishes the work necessary to enable debug-only sessions
where a new PowerShell process is launched strictly for the purpose of
providing a fresh debugging session.  This is useful when debugging
modules which use PowerShell classes or binary components which cannot
be reloaded in the same process.
Part of the implementation for PowerShell/vscode-powershell#367.
> Enable debug-only PowerShell Editor Services sessions

- src/PowerShellEditorServices.Protocol/MessageProtocol/MessageReader.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/MessageWriter.cs
- src/PowerShellEditorServices/Utility/ILogger.cs
This change adds a new "Diagnostic" logging level which is used for
logging the JSON contents of protocol messages that are read or written.
This will provide two benefits:
1. Increase the privacy of user logs that are transmitted over GitHub
2. Increase the performance of writing Verbose logs
We still log the high-level message details like message type, method,
and ID so that we can keep track of the message sequence.
> Add Diagnostic logging level for protocol message JSON

- module/PowerShellEditorServices.VSCode/PowerShellEditorServices.VSCode.psd1
- module/PowerShellEditorServices.VSCode/PowerShellEditorServices.VSCode.psm1
- module/PowerShellEditorServices.VSCode/Public/HtmlContentView/Close-VSCodeHtmlContentView.ps1
- module/PowerShellEditorServices.VSCode/Public/HtmlContentView/New-VSCodeHtmlContentView.ps1
- module/PowerShellEditorServices.VSCode/Public/HtmlContentView/Set-VSCodeHtmlContentView.ps1
- module/PowerShellEditorServices.VSCode/Public/HtmlContentView/Show-VSCodeHtmlContentView.ps1
- module/PowerShellEditorServices.VSCode/Public/HtmlContentView/Write-VSCodeHtmlContentView.ps1
- src/PowerShellEditorServices.VSCode/ComponentRegistration.cs
- src/PowerShellEditorServices.VSCode/CustomViews/CustomViewBase.cs
- src/PowerShellEditorServices.VSCode/CustomViews/CustomViewFeature.cs
- src/PowerShellEditorServices.VSCode/CustomViews/CustomViewMessages.cs
- src/PowerShellEditorServices.VSCode/CustomViews/CustomViewType.cs
- src/PowerShellEditorServices.VSCode/CustomViews/HtmlContentView.cs
- src/PowerShellEditorServices.VSCode/CustomViews/HtmlContentViewMessages.cs
- src/PowerShellEditorServices.VSCode/CustomViews/HtmlContentViewsFeature.cs
- src/PowerShellEditorServices.VSCode/CustomViews/ICustomView.cs
- src/PowerShellEditorServices.VSCode/CustomViews/IHtmlContentView.cs
- src/PowerShellEditorServices.VSCode/CustomViews/IHtmlContentViews.cs
- src/PowerShellEditorServices.VSCode/CustomViews/ViewColumn.cs
- src/PowerShellEditorServices.VSCode/PowerShellEditorServices.VSCode.csproj
This change adds support for custom HTML views in the VSCode module
which forms the basis for UI extensions in the PowerShell extension in
Visual Studio Code.  This change includes both .NET PowerShell
cmdlet APIs for interacting with custom HTML UI in the editor.
> Add custom HTML views to VSCode module

- module/PowerShellEditorServices/PowerShellEditorServices.psm1
This change fixes an issue caused by PowerShell Core 6.0.0-beta3's
AssemblyLoadContext changes where the Protocol assembly isn't being
auto-loaded when the Host assembly gets loaded.  The fix is to
explicitly load that assembly when loaded inside of PowerShell Core.
Resolves #529
> Fix issue with loading PSES in PowerShell Core 6.0.0-beta3

- test/PowerShellEditorServices.Test.Host/ServerTestsBase.cs
This will remove one place where I have to bump the version every release ;)
> Detect PSES module version from test assembly version

- src/PowerShellEditorServices/Extensions/EditorObject.cs
- src/PowerShellEditorServices/Extensions/ExtensionService.cs
With this method you are able to receive all registered EditorCommand´s, and then unregister them or expose all commands through the HTML-ContentView and and be able to execute them once [this](https://github.com/PowerShell/vscode-powershell/issues/910) is implemented.
> Implement GetCommands() on $psEditor

- src/PowerShellEditorServices.Protocol/DebugAdapter/Variable.cs
- src/PowerShellEditorServices/Debugging/DebugService.cs
- src/PowerShellEditorServices/Debugging/VariableDetails.cs
- src/PowerShellEditorServices/Debugging/VariableDetailsBase.cs
This implements a debug protocol feature that was added a while ago (but after we did the majority of work on the Variables view).  This will display the variables type if you hover over it e.g.:
The screen shot didn't capture my cursor.  I'm hovering over the `$InformationPreference` variable.
> Add Type field for Variables.

- module/PowerShellEditorServices/PowerShellEditorServices.psm1
- module/Start-EditorServices.ps1
Since the _Diagnostic_ LogLevel was introduced [here](https://github.com/PowerShell/PowerShellEditorServices/pull/519) it wasn´t possible to use it due to the ValidateSet in the scripts.
> Add "Diagnostic" to ValidateSet for LogLevel

- module/PowerShellEditorServices.VSCode/Public/HtmlContentView/Set-VSCodeHtmlContentView.ps1
- src/PowerShellEditorServices.VSCode/CustomViews/HtmlContent.cs
- src/PowerShellEditorServices.VSCode/CustomViews/HtmlContentView.cs
- src/PowerShellEditorServices.VSCode/CustomViews/HtmlContentViewMessages.cs
- src/PowerShellEditorServices.VSCode/CustomViews/IHtmlContentView.cs
This change adds new parameters to Set-VSCodeHtmlContentView which allow
the user to specify JavaScriptPaths and StyleSheetPaths to include local
JavaScript and CSS files into their HTML views.
Part of the fix for PowerShell/vscode-powershell#910.
> Allow inclusion of JavaScript and CSS file paths in the HtmlContentView

- src/PowerShellEditorServices.Host/EditorServicesHost.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices/Session/EditorSession.cs
This change fixes an issue which causes the command prompt to not appear
when you start an interactive debugging session with the
-DebugServiceOnly parameter.  The fix is to invoke the host's command
loop in this specific case.
Resolves PowerShell/vscode-powershell#942
> Fix missing prompt when launching temporary interactive debug session

- module/PowerShellEditorServices.VSCode/Public/HtmlContentView/Write-VSCodeHtmlContentView.ps1
This change adds the ValueFromPipeline setting to the
AppendedHtmlBodyContent parameter of the Write-VSCodeHtmlContentView
cmdlet so that pipeline output can be written out to an HtmlContentView
with ease.
Resolves PowerShell/vscode-powershell#909.
> Add pipeline input to Write-VSCodeHtmlContentView cmdlet

- module/PowerShellEditorServices/Commands/Public/ConvertTo-ScriptExtent.ps1
- Fixed an issue where `ConvertTo-ScriptExtent` could reverse starting line and column in some situations.
> Fix ConvertTo-ScriptExtent swapping start line and column

- PowerShellEditorServices.Common.props
- PowerShellEditorServices.build.ps1
- src/PowerShellEditorServices.Channel.WebSocket/PowerShellEditorServices.Channel.WebSocket.csproj
- src/PowerShellEditorServices.Host/PowerShellEditorServices.Host.csproj
- src/PowerShellEditorServices.Protocol/PowerShellEditorServices.Protocol.csproj
- src/PowerShellEditorServices.VSCode/PowerShellEditorServices.VSCode.csproj
- test/PowerShellEditorServices.Test.Host/PowerShellEditorServices.Test.Host.csproj
- test/PowerShellEditorServices.Test.Protocol/PowerShellEditorServices.Test.Protocol.csproj
- test/PowerShellEditorServices.Test.Shared/PowerShellEditorServices.Test.Shared.csproj
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
This change updates the build script to use the newly released .NET SDK
2.0.  dotnet CLI 2.0 now restores package dependencies implicitly so all
restore logic has been taken out of the build script.  The test projects
have also been updated to use xUnit 2.3 and their new `dotnet xunit`
runner.
> Update to .NET SDK 2.0

- src/PowerShellEditorServices/Session/Host/IHostOutput.cs
This change resolves PowerShell/vscode-powershell#637 which reports that
on Linux and macOS the input prompt is printed out with a black
background, overriding the console's default background color.  The
fix is to use a System.ConsoleColor of -1 as the default rather than
System.ConsoleColor.Black so that .NET's console library will not
override the console's background color.
> Use raw console bgcolor by default in IHostOutput.WriteOutput

- src/PowerShellEditorServices.Protocol/DebugAdapter/StackFrame.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Session/Host/TerminalPSHostUserInterface.cs
Fix bug where the user can select the bottom most stack frame during interactive session debugging and that generates an error in VSCode when it can't find <No File>.
Fix #555 ParameterBindingValidationException when invoking PSSA on an empty PS1 file.
> Fix bug where bg of -1 causes crash of interactive session.

- src/PowerShellEditorServices/Workspace/Workspace.cs
Enumerating files in a dir shouldn't crash PSES for security, path length and errors from dir not found.
> Fix DirectoryNotFoundException user is seeing in deep node_modules dir

- src/PowerShellEditorServices/Session/Host/EditorServicesPSHost.cs
This fix overrides the built-in PSHost.PrivateData property, which returns null.  The override instead returns an empty PSObject.  This fixes the Get-Help -ShowWindow scenario since Windows PowerShell will no longer get a NullRefEx on access the host PrivateData property without doing a null check.  Since PrivateData["Window"] will still return null, PowerShell will show the dialog with the desktop as the parent window. IOW this PR does not fix the issue with the help window not appearing on top.  It simply fixes the error you get in PSIC.
> Fix #570 Get-Help -ShowWindow errors in PSIC

- src/PowerShellEditorServices/Workspace/ScriptFile.cs
The old code allowed the line param to be *equal* to FileLines.Count + 1.
That's not a valid index even after subtracting 1 to get to a 0-based index.
Also added more data to log messages to help in the future.
@daviwil I pretty sure about the off-by-one but not 100% sure.  Can you double check?  At the very least, I'd like to enhance the log messages.
This is related to #567.  I'm not sure if this fixes it (kind of doubt it) but I'm hopeful the enhanced log messages might help if someone repro's this.
> Fix off-by-one on maxlLine calc

- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices/Workspace/ScriptFile.cs
Fix #574 
There's still an associated but separate bug when a user is attempting to start debug on the current file when the active window is a Git diff window.  I opened an issue on vscode-debugadpter-node project: https://github.com/Microsoft/vscode-debugadapter-node/issues/134
> Do not set breakpoint on non-PowerShell files

- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
This fixes https://github.com/PowerShell/vscode-powershell/issues/1014
> Fix crash of PSES on startup when workspace folder has [] in path

- src/PowerShellEditorServices/Workspace/ScriptRegion.cs
fixes #582 
`IScriptExtent` throws an `ArgumentOutOfRangeException`. When accessing the `Text` property.
This PR catches that error and sets it to a default value of empty string.
> Catch ArgumentOutOfRange exception

- src/PowerShellEditorServices.Protocol/Server/LanguageServerSettings.cs
Crash happens if user tries to set path to something like `${env:HOME}\pssettings.psd1` which looks like it might be valid but isn't because the variable doesn't get expanded.
It seems the GH diff view has gotten dumber or something. This is the diff I see in VS:
> Fix bad pssa settings path crashes PSES

- PowerShellEditorServices.build.ps1
- appveyor.yml
- scripts/travis.ps1
Use new syntax for safe-running jobs. Also specified the max versions in AppVeyor and Travis.
Thanks @nightroman for the tip!
Addresses https://github.com/nightroman/Invoke-Build/issues/113
> change 'job Test -Safe' to '?Test'

- src/PowerShellEditorServices.Protocol/LanguageServer/EditorCommands.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServerEditorOperations.cs
- src/PowerShellEditorServices/Extensions/FileContext.cs
- src/PowerShellEditorServices/Extensions/IEditorOperations.cs
- test/PowerShellEditorServices.Test/Extensions/ExtensionServiceTests.cs
This is the PSES portion of this change. See the PSES portion here: https://github.com/PowerShell/vscode-powershell/pull/1139
Please let me know if I'm missing something.
To test this, you can use:
```powershell
$psEditor.GetEditorContext().CurrentFile.Save()
```
in the Integrated Console.
> add Save to FileContext API

- src/PowerShellEditorServices/Session/PowerShellContext.cs
This improves the output to the EditorServices.log file from:
```
1/4/2018 6:49:26 PM [ERROR] - Method "ExecuteCommand" at line 575 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs
Execution completed with errors:
You cannot call a method on a null-valued expression.
You cannot call a method on a null-valued expression.
```
to
```
1/4/2018 6:49:26 PM [ERROR] - Method "ExecuteCommand" at line 575 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs
Execution of command 'Import-Module - C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\module\PowerShellEditorServices\bin\Desktop\..\..\Commands\PowerShellEditorServices.Commands.psd1;' completed with …
```
> Improve error logging for exec of pscommands

- PowerShellEditorServices.build.ps1
- src/PowerShellEditorServices/Console/ConsoleReadLine.cs
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
This change resolves an issue where the debugger would appear hung until a key was pressed on Unix platforms.
This issue was caused by a quirk with the Unix implementation for `System.Console`.  The way cursor position is retrieved is by writing the cursor position escape sequence query and reading it from stdin. To ensure those escape sequences don't trigger `Console.ReadKey`, the internal stdin buffer is locked while `ReadKey` is running. This means that while `ReadKey` is running, any attempts to query cursor position will block the thread until the pending `ReadKey` finishes.
The pipeline appears to hang on a debugger stop because there is a pending `ReadKey` call in another thread and various methods in both the internal PowerShell engine and in our host implementation obtain the …
> Fix debugger step through on Unix platforms

- .gitignore
On Mac, I have to use Visual Studio for Mac to get the "Go To Def" and such because of this bug:
https://github.com/OmniSharp/omnisharp-vscode/issues/1937
It creates one of these files that doesn't need to be checked in.
> add userprefs for VS for Mac

- Third Party Notices.txt
For legal purposes.
for reference: https://github.com/PowerShell/vscode-powershell/blob/master/Third%20Party%20Notices.txt
> Create Third Party Notices.txt

- src/PowerShellEditorServices/Session/RemoteFileManager.cs
- src/PowerShellEditorServices/Session/SessionDetails.cs
`*-Content -Encoding Byte` was changed to `*-Content -AsByteStream` in PSCore. This PR adds a check for the version of PowerShell... and uses the correct param.
Also, since `$env:ComputerName` is not set on Linux or Mac, we get null ref exceptions so we are using `[Environment]::MachineName` instead and defaulting to "localhost" if it does not exist.
This allowed me to remote edit/debug a file on an Ubuntu VM from my Mac 🎉
Resolves https://github.com/PowerShell/PowerShellEditorServices/issues/597
Resolves https://github.com/PowerShell/vscode-powershell/issues/789
> fix *-Content calls in psedit scripts and set ComputerName default

- src/PowerShellEditorServices/Session/PowerShellContext.cs
I thought I had looked for an existing impl of this but somehow missed `GetStringForPSCommand()`.  Modified it to render parameter info and use it from `ExecuteCommand` method.  
Actually,  you'd think this ability to render the complete command to a string would be built into the PSCommand type - oh well.
> Found GetStringForPSCommand - moved parameter dump code into it

- module/PowerShellEditorServices/Commands/PowerShellEditorServices.Commands.psd1
- module/PowerShellEditorServices/Commands/Public/CmdletInterface.ps1
- src/PowerShellEditorServices/Session/RemoteFileManager.cs
This works both in local and remote sessions.
psedit became Open-EditorFile
and psedit aliases Open-EditorFile
Resolves #528
> change psedit to Open-EditorFile and alias psedit to it

- src/PowerShellEditorServices/Workspace/Workspace.cs
As @daviwil mentioned in #612, 
> If you change those EnumerateDirectories/Files calls to GetDirectories/Files, it might take care of the problem. There's really no benefit to using the Enumerate variety since we're not streaming the results back anyway, it just seemed to be the right thing to do at the time.
He was correct! Changing the Enumerates to Gets did the trick. Verified this on macOS by opening up a big workspace and finding all references/go to definition.
Resolves #612 
Resolves https://github.com/PowerShell/vscode-powershell/issues/908
Resolves https://github.com/daviwil/ide-powershell/issues/1
> change Enumerate* to Get*

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
For some reason, on macOS `Sort` did not exist.
I switched it to Sort-Object which is universal and not an alias.
It's a shame we can't run PSSA on our script strings in the c# of PSES :) No aliases allowed!
Resolves https://github.com/PowerShell/vscode-powershell/issues/1185
> replace sort with sort-object

- build.ps1
* running `build.ps1` checks for missing tools and runs `Invoke-Build Build`
* running `build.ps1 -Clean` checks for missing tools and runs `Invoke-Build Clean` and then `Invoke-Build Build`
* running `build.ps1 -Test` checks for missing tools and runs `Invoke-Build Build` and then `Invoke-Build Test`
* running `build.ps1 -Bootstrap` informs you of what tools you are missing
- the dependencies it checks for are:
- openssl for macOS
- PowerShellGet
- InvokeBuild
* pulling dotnet sdk installation out of current build script
The script is a bit verbose on purpose so that we can easily add additional dependencies.
Resolves https://github.com/PowerShell/PowerShellEditorServices/issues/586
> first build.ps1

- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
Fixex https://github.com/PowerShell/vscode-powershell/issues/1159
When VSCode passes us a breakpoint to set, we normally set
a flag to indicate "setBreakpointInProgress" so that when
the DebugService_BreakpointUpdated event is fired, we can
tell that we initiated it instead of the user using Set-PSBreakpoint
to set a breakpoint.   Well, the code that handled function
breakpoints msgs sent by VSCode was not setting that flag.
Also, when the user does use Set-PSBreakpoint -Command
there is no debug protocol event for function breakpoints
so we need to ignore this type of breakpoint set by the user
until the debug protocol support it.  
See https://github.com/Microsoft/vscode-debugadapter-node/issues/157
> Fix PSES crash on debug start when function breakpoint defined

- src/PowerShellEditorServices.Host/EditorServicesHost.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/LaunchRequest.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
This does not leave a working prompt.  I think that is OK for now.  This is still better than the current situation.
> Track tempIntegratedConsole launch param, do not exit when session ends

- module/PowerShellEditorServices/Commands/PowerShellEditorServices.Commands.psd1
- module/PowerShellEditorServices/Commands/Public/CmdletInterface.ps1
- src/PowerShellEditorServices.Protocol/LanguageServer/EditorCommands.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServerEditorOperations.cs
- src/PowerShellEditorServices/Extensions/EditorWorkspace.cs
- src/PowerShellEditorServices/Extensions/IEditorOperations.cs
- src/PowerShellEditorServices/Session/RemoteFileManager.cs
- test/PowerShellEditorServices.Test/Extensions/ExtensionServiceTests.cs
Here's what you can do:
```powershell
Open-EditorFile foo.txt -Force
```
This will create a new file called `foo.txt` if no file exists. It will throw an error if you don't add `-force` and `foo.txt` does not exist.
Also,
```powershell
Get-Process | Open-EditorFile foo.txt -Force
```
This will create a new file called `foo.txt` with the contents of what came in through the pipeline. Another example:
```powershell
irm https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/install-powershell.ps1 | psedit install-powershell.ps1 -Force
```
You can also do:
```powershell
Get-Process | Open-EditorFile
```
This will open an Untitled file in your editor and put the contents in it.
This works in local and remote sessions.
Note, Get-Process has an issue in remote sessions when piping …
> Add New-EditorFile

- src/PowerShellEditorServices/Session/Host/EditorServicesPSHostUserInterface.cs
This is to eliminate duplicate `[DBG]` in the prompt string for folks like me that write their prompt function to handle the DBG prompt.  Without this change, my prompt looks like this:
And after this change:
> Eliminate duplicate dgb prompt

- src/PowerShellEditorServices/Utility/FileLogger.cs
This is minor but since VSCode is now colorizing log files, this format looks better when viewing PSES log files in VSCode.
Old format:
New format:
> Switch to w3c log file timestamp format

- src/PowerShellEditorServices.Protocol/LanguageServer/ExecutionStatusChangedEvent.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
Create notification events for when the Language Server runs PowerShell
scripts, so the client is informed about the status of the running
script.
This can be used by the client to alert the user when a script is running.
Solves [vscode-powershell #154](https://github.com/PowerShell/vscode-powershell/issues/154).
> Add events for PowerShell execution status (running, completed, etc).

- PowerShellEditorServices.build.ps1
our build script required 2.0.0. Now the cli is up to 2.1.4. This small change allows newer versions to be used.
We may want to eventually put an upper bound on this... but I don't think the dotnet cli will change much at least how we're using it.
> Allow newer dotnet cli

- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
- test/PowerShellEditorServices.Test.Host/PowerShellEditorServices.Test.Host.csproj
- test/PowerShellEditorServices.Test.Host/ServerTestsBase.cs
- test/PowerShellEditorServices.Test.Protocol/PowerShellEditorServices.Test.Protocol.csproj
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
Fix issue with running xUnit tests over and over.  Have a better
way to detect when the session details file has been written.
Fix issue with ServiceReturnsPowerShellVersionDetails test,
where it only worked when you ran the tests using x86 arch.
It now runs correctly using x64.
> Add support for running xUnit tests in VS Test Explorer

- src/PowerShellEditorServices/Workspace/Workspace.cs
- test/PowerShellEditorServices.Test/Session/WorkspaceTests.cs
Fix #569
PSES would crash quite often when the user viewed a ps1 file in a diff window
or an earlier version using GitLens.
This approach using the System.Uri class that can detect file vs other schemes.
URI chokes on relative file paths.  In this case, we fall back to the previous
approach of using Path.GetFullPath().
> Implement better way to test for in-memory file

- src/PowerShellEditorServices/Symbols/PesterDocumentSymbolProvider.cs
Fixes [vscode-powershell #1223](https://github.com/PowerShell/vscode-powershell/issues/1223).
Previously, Pester test parsing by PSES has made a couple of assumptions that didn't hold and as a result it wouldn't recognise tests with tags.
Now we do all of that, and are even set up to add something like tag-awareness in future more easily.
> Refactor pester script detection

- src/PowerShellEditorServices/Workspace/ScriptRegion.cs
We've been sitting on a compile warning for a while, so I've removed the offending variable.
> Get rid of the unneeded exception variable causing a compile warning

- src/PowerShellEditorServices/Session/RemoteFileManager.cs
Make the `PSESRemoteSessionOpenFile` a support event, so `Get-EventSubscriber` won't show up that subscriber. `Get-EventSubscriber -Force` can still show the support events. `Unregister-Event -Force` needs to be used to remove a support event.
The event subscriber for `PSInternalRemoteDebuggerStopEvent` and `PSInternalRemoteDebuggerBreakpointUpdatedEvent` are already made support events, see [`ServerRunspacePoolDriver.cs`](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs#L2167).
> Make the 'PSESRemoteSessionOpenFile' a support event

- src/PowerShellEditorServices/Session/PowerShellContext.cs
We were seeing this exception every time on macOS.
```
2018-02-23 20:23:14 [WARNING] - Method "GetVersionDetails" at line 153 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellVersionDetails.cs
Failed to look up PowerShell version, defaulting to version 5.
System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.PowerShell.EditorServices.PowerShellContext.<>c__56`1.<ExecuteScriptAndGetItem>b__56_0(PSObject pso)
at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
at System.Linq.Enumerable.<OfTypeIterator>d__32`1.MoveNext()
at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
at …
```
> fix GetVersionDetails error

- src/PowerShellEditorServices.Protocol/LanguageServer/EditorCommands.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServerEditorOperations.cs
- src/PowerShellEditorServices/Extensions/FileContext.cs
- src/PowerShellEditorServices/Extensions/IEditorOperations.cs
- test/PowerShellEditorServices.Test/Extensions/ExtensionServiceTests.cs
Adds a `SaveAs()` method to the `FileContext` object, which sends a message to language client to save the current file as something else, at a path relative to the current file.
One note: there's a small amount of validation, just to not let you overwrite a file (since VSCode won't). The question is: should we do more validation, or none and instead get VSCode to send us back a success/failure message?
See [vscode-powershell #1261](https://github.com/PowerShell/vscode-powershell/pull/1261) for the client side of this feature.
> Add $psEditor.GetEditorContext().CurrentFile.SaveAs("Name") support

- .gitignore
- PowerShellEditorServices.build.ps1
- module/PowerShellEditorServices/Start-EditorServices.ps1
- modules.json
- src/PowerShellEditorServices/Analysis/AnalysisService.cs
- test/PowerShellEditorServices.Test.Host/ServerTestsBase.cs
When PSES builds, it should be responsible for its own modules. So I've added a build rule that populates its `/module/` directory. This moves the `modules.json` file over from the VSCode extension as well.
So with this, PSES should be generally self contained and ready to run after building.
> Change PSES to be buildable as a standalone

- module/PowerShellEditorServices/PowerShellEditorServices.psm1
- src/PowerShellEditorServices.Host/EditorServicesHost.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
Fixes #655 
This shuts down PSES when it receives the `exit` message [following the language server protocol](https://microsoft.github.io/language-server-protocol/specification#exit).
This also makes the `shutdown` message NOT kill the server which also [follows the language server protocol](https://microsoft.github.io/language-server-protocol/specification#shutdown).
I've tested this using the [NeoVim Language Client](https://github.com/autozimu/LanguageClient-neovim)
> Close stray processes on exit

- .gitignore
ignore .idea folder that jetbrains products like to spit out (Rider, IntelliJ, Resharper)
> ignore .idea folder that jetbrains products like to spit out

- .editorconfig
- .gitattributes
- .vscode/extensions.json
Address #665 
This should help address differences in behavior between editing in VS and in VSCode.  
Although at first, we'll probably get a lot of whitespace changes (due to trimming trailing
whitespace in C# files).
> Add .gitattributes, .editorconfig and extensions.json

- src/PowerShellEditorServices.Host/EditorServicesHost.cs
PSES's debug adapter wasn't properly shutting down between debug sessions (some things were shut down, some things weren't). This might have been the cause of other debug issues we have seen when/if folks have been unable to restart the debugger.
This change is needed to get NamedPipes working because when running Start without fully Stopping before it, the debug adapter would crash with:
> All pipe instances are busy
> Stop before we restart

- src/PowerShellEditorServices.Protocol/LanguageServer/InitializedNotification.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
We do nothing in the handler atm but in the future we can do dynamic
registration of capabilities in it.
> Implement initialized notification handler to get rid of log error

- PowerShellEditorServices.build.ps1
This copies over the .pdb files into the module so that it can be debugged alongside the/a client. Only copies the files in the Debug configuration.
> Add symbols to modules built in Debug configuration

- src/PowerShellEditorServices/Analysis/AnalysisService.cs
Since the majority of people do not customize the PSSA settings inside VSCode and just use the vs code extension how it comes out of the box, therefore enabling more useful PSSA rules by default, especially `PSPossibleIncorrectComparisonWithNull` (this was what drove me to change the defaults because I really expected this to be on by default when I was doing a demo)
The parallel nature of PSSA (that executes all rules in parallel) means that the time to analyse a script will be always bound by the slowest rule.
> Add more useful PSSA rules that should be enabled by default

- .github/CODEOWNERS
I'm not entirely sure this is supported:
```
src/PowerShellEditorServices/Session/*ReadLine*.cs 
```
guess we just have to see once this is merged.
> Initial CODEOWNERS file to auto assign PR reviewers

- src/PowerShellEditorServices/Analysis/AnalysisService.cs
Invoke-Formatter -ScriptDefinition '' - throws a terminating error:
ParameterBinderValidationException.
I suppose we could have added another catch statement to the InvokePowerShell method
in the AnalysisService but in general, we probably want to know about such bugs.
We could also update the extension to not send a format request for an empty doc
but I'm not sure it's worth the additional code change given this corner case scenario.
But I could be convinced otherwise.
This is a partial fix to vscode issue https://github.com/PowerShell/vscode-powershell/issues/1346#issuecomment-396084932
> Fix PSES crash when you format an empty PS doc

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Extensions/EditorObject.cs
- src/PowerShellEditorServices/Extensions/ExtensionService.cs
- src/PowerShellEditorServices/Session/EditorSession.cs
- src/PowerShellEditorServices/Utility/Logging.cs
- src/PowerShellEditorServices/Utility/PsesLogger.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/1298 and https://github.com/PowerShell/PowerShellEditorServices/issues/657.
* Load the latest version of PSScriptAnalyzer we can find on the path.
* Eliminate the `VerifyPSScriptAnalyzerAvailable`, since `ImportPSModule()` executes the same code internally.
* Do all the runspace manipulation in a factory method rather than in a constructor...
* Get rid of a bunch of needless private variables that just backed public ones.
* Get rid of `_hasScriptAnalyzerModule`, since it only got checked after the object was constructed (meaning it was always true...).
* Added some null checks on `AnalysisService` usage, since it can definitely be null.
> Make AnalysisService use the latest version of PSScriptAnalyzer

- module/PowerShellEditorServices.VSCode/PowerShellEditorServices.VSCode.psm1
- module/PowerShellEditorServices/Commands/PowerShellEditorServices.Commands.psm1
- module/PowerShellEditorServices/PowerShellEditorServices.psm1
- module/PowerShellEditorServices/Start-EditorServices.ps1
- src/PowerShellEditorServices/Session/RemoteFileManager.cs
redefines set-content, breaks Start-PSES
Fixes https://github.com/PowerShell/vscode-powershell/issues/1331
I wish we didn't have to module qualify command names like this but
we've been bitten several times now by overridden commands.
One concern I have is testing this due to it needing to be signed.
> Fix issue where MS Dynamics CRM

- module/PowerShellEditorServices/Start-EditorServices.ps1
This error happens because when log level is set to Diagnostic, we use
Start-Transcript to log the output of Start-EditorServices.ps1.
But the log filename we we're using was always Start-EditorServices.log.
When we start a temp console debug session, it's using the
Start-EditorServices.ps1 script to start the debug session.
That attempts to log to the original log file which is locked.
This causes an error. The fix is to append the log filename
which will be unique per launch of the Start-ES script.
> Fix error w/Start-EditorServices transcript logging using temp console

- src/PowerShellEditorServices.Protocol/DebugAdapter/LaunchRequest.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
Fix for PowerShell/vscode-powershell#1330
Removes deprecated "Program" field from LaunchRequest class.
Simplifies working dir logic in HandleLaunchRequest.  Basically if the
launch request happens in the regular integrated console, a null/empty
cwd means "do not change the working dir".  If the request is using the
temp integrated console, there is no "existing" workng dir, so we use
the original logic to set the working dir.
> Change debug launch handler to treat null/empty cwd to not change dir

- module/PowerShellEditorServices/Start-EditorServices.ps1
Start-EditorServices.ps1 currently uses `New-Guid`, which is a v5+ cmdlet.
This replaces it with `[guid]::NewGuid()` for v3/4 compatibility.
> Fix incompatible New-Guid usage in start script

- module/PowerShellEditorServices/Start-EditorServices.ps1
The `stat` usage in the startup script currently does not work on Linux.
This changes the `%A` to `%a` to make it work.
> Fix issue with stat format on Linux

- CHANGELOG.md
- PowerShellEditorServices.Common.props
- appveyor.yml
- module/PowerShellEditorServices/PowerShellEditorServices.psd1
Update PowerShellEditorServices to v1.8.1
> Update CHANGELOG and version numbers for 1.8.1 release

- src/PowerShellEditorServices/Analysis/AnalysisService.cs
Despite modern editors having the ability to eliminate redundant whitespace when saving the file automatically, people are still upset by PSSA pointing out whitespace for whitespace-only lines by the rule `PSAvoidTrailingWhitespace`. Until the rule is customisable for that with a potential change of the default behaviour, it is probably better to not have this rule enabled by default. This rule got enabled by default in version`1.8.0` of the vscode extension along with other rules.
References:
https://github.com/PowerShell/PSScriptAnalyzer/issues/1033
https://github.com/PowerShell/PSScriptAnalyzer/issues/1036
https://github.com/PowerShell/vscode-powershell/issues/1429
https://github.com/PowerShell/vscode-powershell/issues/1432
> Do not enable PSAvoidTrailingWhitespace rule by default as it currently flags whitespace-only lines as well and users don't like it

- src/PowerShellEditorServices/Analysis/AnalysisService.cs
Current bug means we always load the oldest version of PSSA.
Now we will load the newest.
> Fix load order of PSSA modules

- module/PowerShellEditorServices/PowerShellEditorServices.psm1
if both are launched - then the text is split between the language and debug service - aka PSES just doesn't work.
This should be the final PR in "fixing stdio"
> stdio should only launch language service not debug

- module/PowerShellEditorServices/Start-EditorServices.ps1
when Start-EditorServices logs to stdio when PSES is using stdio to communicate, the logs are treated as messages and PSES fails to work.
This allows you to set it to Diagnostic and also use stdio.
> Stop Diagnostic logging from logging to stdio when stdio is present

- src/PowerShellEditorServices/Language/FindDeclarationVisitor.cs
fixes https://github.com/PowerShell/vscode-powershell/issues/1439
The issue was that when you hit F12 (aka go to definition) on any of the following scenarios except for the first one, they would fail to find the definition.
```powershell
$var1 = "string"
$var1
[string] $var2 = "string"
$var2
[NJsonSchema.Annotations.NotNull()] $var3 = "string"
$var3
$a, $var4 = "string", "sss"
$var4
$a, [string] $var5 = "string", "sss"
$var5
```
All these scenarios now work with this PR.
We needed to recurse the AST to find the VariableExpressionAst because it could be nested in another Ast type.
> Go To Definition works with different Ast types

- src/PowerShellEditorServices.Host/CodeLens/ReferencesCodeLensProvider.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- test/PowerShellEditorServices.Test/Session/WorkspaceTests.cs
This isn't the most elegant solution but it does the trick. I don't think we'll run into many (if not any) more Uri schemes we care about. When we run into another, then we can probably discuss a better solution.
Let me know if you feel differently.
> workaround to support inmemory://

- CHANGELOG.md
- PowerShellEditorServices.Common.props
- appveyor.yml
- module/PowerShellEditorServices/PowerShellEditorServices.psd1
> Prep for 1.8.2 release

- module/PowerShellEditorServices/Start-EditorServices.ps1
be explicit in calling stat since users can install GNU coreutils (which has a different signature) on macOS.
> fix #1444 stat call

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Workspace/ScriptFile.cs
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
The previous implementation used LINQ on a relatively hot path, returned a lazy IEnumerable that was always eagerly converted to a List or Array and allocated two strings per line when Windows linebreaks were used.  Profiling indicates that PSES spends a huge percentage of its time in GC, so switching to a slightly more complex implementation that allocates less than half as much seems justified.
This is some of the "low hanging fruit" I mentioned in https://github.com/PowerShell/vscode-powershell/issues/1342.
> Reduce allocations when parsing files

- PowerShellEditorServices.Common.props
- appveyor.yml
- module/PowerShellEditorServices/PowerShellEditorServices.psd1
Bumping the version to 1.8.3 so that if people grab the vsix in vscode-powershell it will not get overwritten by the current release.
addresses https://github.com/PowerShell/vscode-powershell/issues/1445
> increment version for prerelease

- tools/releaseBuild/signing.xml
- tools/releaseBuild/vstsbuild.ps1
Adds a VSTS variable replacement step for signing using PowerShell's signing update script
> Add VSTS signing step

- CHANGELOG.md
Updates the CHANGELOG for the v.1.8.3 release
> Update CHANGELOG for v1.8.3

- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/1334.
I was looking at this trying to figure out what's going on, and I think what's happening is that the null check we do it not helpful because we don't await the execution of the method.
So I've changed it to pass the actual value of the string in at call time. I assume that will work, but let me know if not.
Also the first commit here was a style change one...
> Fix null dereference when debugging untitlted files

- src/PowerShellEditorServices.Host/CodeLens/CodeLensFeature.cs
- src/PowerShellEditorServices.Host/CodeLens/PesterCodeLensProvider.cs
- src/PowerShellEditorServices.Host/CodeLens/ReferencesCodeLensProvider.cs
- src/PowerShellEditorServices/Utility/HashCodeCombiner.cs
Went and tackled some easy stuff in the CodeLens provider (since disabling it seems to give the best performance improvement for EditorServices).
There should be no semantic changes from this.
I didn't go after caching, since that's a bit riskier and probably needs some design discussion about where the caches live (i.e. what objects are responsible for them).
> Reduce allocations in the CodeLens providers

- src/PowerShellEditorServices/Console/InputPromptHandler.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/1450.
When a parameter causes an invalid cast exception in the console, we assumed the inner exception wasn't null. Now if it is, we pass through the outer exception.
> Fix a null dereference when an invalid cast exception has no inner exception

- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
- test/PowerShellEditorServices.Test/Language/LanguageServiceTests.cs
- test/PowerShellEditorServices.Test/Utility/AsyncDebouncerTests.cs
The `FindNoReferencesOnEmptyLine` test is hanging in AppVeyor (not on a local Windows machine).
This skips it.
We should work out why this is though, especially since it isn't even an `async` test...
I've also re-enabled a bunch of previously skipped tests, because they seem to be passing.
EDIT: Turns out I had to add a timeout to the task tests (even though none of them actually time out...)
> Make AppVeyor tests pass

- src/PowerShellEditorServices/Language/LanguageService.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/1471 and fixes https://github.com/PowerShell/PowerShellEditorServices/issues/718.
If a file is removed when the reference symbols are being parsed, it will cause an exception to be thrown. Now if that file does not exist, we just skip it.
> Fix codelens crash when a file does not exist

- src/PowerShellEditorServices/Workspace/ScriptFile.cs
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/1283 and fixes https://github.com/PowerShell/vscode-powershell/issues/1492.
**Note**: I doubt it will affect https://github.com/PowerShell/vscode-powershell/issues/1453; that looks like a separate issue.
It looks like there is a tendency for VSCode to generate a text document change request with an offset that is one beyond the current lines we track under certain conditions. @rkeithhill's repro is the best I've seen.
Anyway, this PR just detects that case and bypasses all the magic insertion logic -- instead we just append the lines to the end.
> Fix crash where lines appended to end of script file causes out of bounds exception

- src/PowerShellEditorServices/Analysis/AnalysisService.cs
Addresses https://github.com/PowerShell/PSScriptAnalyzer/issues/1057 and https://github.com/PowerShell/PSScriptAnalyzer/issues/826#issuecomment-372135654.
When the formatter was run, it we would try to format even a document with parse errors. Now if there are parse errors, the formatter will do nothing (silently). Ideally we should make VSCode report that formatting failed and why, although this would mean returning a different format result.
> Fix formatter crash when script contains parse errors

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Utility/ExecutionTimer.cs
- src/PowerShellEditorServices/Utility/Logging.cs
- src/PowerShellEditorServices/Utility/PerformanceTimer.cs
Adds a method onto the `ILogger` that can time the execution of a `using` block -- so you can time things like:
```csharp
using (_logger.LogExecutionTime("Executed MyMethod."))
{
MyMethod(args);
}
```
That prints something to the logs like
```
[VERBOSE] Executed MyMethod. [25ms]
```
> Add an easy to use execution timer

- PowerShellEditorServices.build.ps1
I've gotten to understand the testing layout better, and to stop AppVeyor failing for now I thought we might just exclude the integration testing that's timing out.
Making testing work is the next item on my list, so it will be back in some form.
> [Ignore] Exclude integration tests

- PowerShellEditorServices.build.ps1
- appveyor.yml
- modules.json
- scripts/travis.ps1
- src/PowerShellEditorServices/Session/PSReadLinePromptContext.cs
- Uses the PSReadLine beta3 release from PowerShell gallery instead of downloading the master build from AppVeyor
- Filters out the old beta versions that don't have @SeeminglyScience's private API in it (which effectively break us trying to pull PSRL2 in)
Quick question: is there anything else that needs changing for better PSRL module support here?
> Use PSRL release and filter out previous betas

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
Removes a few LINQ calls from the Language Server, in an effort to chip away at performance issues.
Given how complicated and central the logic here is, I haven't made any style changes, but would be happy to make any :)
> Remove unnecessary LINQ calls from LanguageServer

- src/PowerShellEditorServices/Language/LanguageService.cs
Removes most LINQ calls in the language service methods.
There are also some style changes. They should be contained to commits marked `[Style]`.
> Remove LINQ usage in language service methods

- src/PowerShellEditorServices/Language/AstOperations.cs
I noticed that completion queries do a reflection call every time. This code caches instead, but it's not terribly elegant. So if you have any suggestions, please let me know.
> Cache the reflection call done for completions

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/1509.
I'm not sure what the added `lines ??` part of the comment based help request handler was trying to achieve, but I don't think it was correct. So I've removed that.
My second commit refactors the method body a bit to make it a bit simpler.
> Fix inner help completion

- src/PowerShellEditorServices/Utility/ExecutionTimer.cs
Discovered while debugging that the stopwatch in the execution timer wasn't being used properly.
> Fix NRE when trying to start the stopwatch

- src/PowerShellEditorServices/Language/LanguageService.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/1518.
Protects against trying to open bad paths from `ScriptFile.GetFile()` in the symbol provider.
This fixes the given issue, but might not be the best way to do so -- perhaps better for `GetFile()` to return null in this case?
But we can change that at some later point perhaps.
> Fix crash for finding symbols on bad paths

- src/PowerShellEditorServices/Workspace/ScriptFile.cs
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
Fixes https://github.com/PowerShell/PowerShellEditorServices/issues/739.
- Allows VSCode to send a request where the end line is 1 past the number of lines in the file.
- Restores the old validation behaviour.
- Adds a couple of tests.
> Fix index out-of-range exception when deleting script files

- src/PowerShellEditorServices/Workspace/Workspace.cs
- test/PowerShellEditorServices.Test/Session/WorkspaceTests.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/1518 in a second way!
We seemed to be double escaping URIs. I've changed the behaviour and added a battery of tests around `Workspace.ResolveFilePath()` (that we should add to).
Now a URI like `file:///C:/foo/bar#x/baz/` will resolve to `C:\foo\bar#x\baz\` and not `C:\foo\bar`.
> Fix issue where # in path causes the path to resolve incorrectly

- src/PowerShellEditorServices.Protocol/LanguageServer/ShowHelpRequest.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
I noticed it was hard to get the offline behaviour in @corbob's awesome addition to fire, so I made a minor edit where we test if the help page is accessible first.
@corbob GitHub won't let me add you as a reviewer, but if you've got time to review please do!
> Enforce Get-Help offline dropback when page or internet is down

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
Fix a regression where we don't accumulate signatures we discover.
I've now read through both the LINQ PRs I merged looking for this problem and this is the only other instance I found.
> Fix signature handler regression

- src/PowerShellEditorServices/Session/Capabilities/DscBreakpointCapability.cs
Checking for DSC capability is currently done by attempting to import a drive qualified path to where we would expect the DSC module. This fails during parameter validation due to an invalid drive.
This change broadens the scope of the catch block to account for this exception.
> Fix exception when remoting from Windows to non-Windows

- src/PowerShellEditorServices/Session/PowerShellContext.cs
Resolves https://github.com/PowerShell/vscode-powershell/issues/1573.
Marks runtime executions from `PowerShellContext.Invoke()` as `WARNING`s not `ERROR`s, since they don't crash the extension and often cause distraction in the log.
> Make pipeline runtime exceptions warnings in log

- src/PowerShellEditorServices.Protocol/MessageProtocol/MessageDispatcher.cs
Resolves https://github.com/PowerShell/vscode-powershell/issues/1572.
Unhandled messages are tolerated in the LSP and we know about the major ones. Having them as an error is distracting in the logs, so this changes the report to a warning.
> Change unhandled messages to Warning

- src/PowerShellEditorServices/Session/PowerShellContext.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/1571.
I carelessly took out the `runspace.ApartmentState = ApartmentState.STA` line of PSES v1.x without thinking and forgot to reinstate it.
This PR puts it back in.
> Set Runspaces to use STA when running in Windows PowerShell

- src/PowerShellEditorServices/Utility/ExecutionTimer.cs
- src/PowerShellEditorServices/Utility/ObjectPool.cs
- test/PowerShellEditorServices.Test/Utility/ExecutionTimerTests.cs
- test/PowerShellEditorServices.Test/Utility/ObjectPoolTests.cs
Fix #779: NRE on Dispose in ExecutionTimer
As discussed, `ThreadStatic` implementation replaced by an object pool. My object pool is very basic as I didn't feel like the current usage warranted anything more complex. Let me know if you think I should do anything different!
> Fix #779: NRE on Dispose in ExecutionTimer

- src/PowerShellEditorServices.Protocol/LanguageServer/ShowHelpRequest.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
The ShowOnlineHelp message was deprecated in v1.9.0. This is to fully remove the message.
Opened PR against 2.0.0 branch because it shouldn't be removed until 2.0.0 at the earliest.
> Removed ShowOnlineHelp Message

- .gitignore
- PowerShellEditorServices.build.ps1
- module/PowerShellEditorServices/Start-EditorServices.ps1
- src/PowerShellEditorServices.Host/BuildInfo/BuildInfo.cs
- src/PowerShellEditorServices.Host/EditorServicesHost.cs
- src/PowerShellEditorServices.Host/PowerShellEditorServices.Host.csproj
- src/PowerShellEditorServices/Console/ConsoleReadLine.cs
- src/PowerShellEditorServices/Language/LanguageService.cs
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Workspace/Workspace.cs
Partially helps https://github.com/PowerShell/vscode-powershell/issues/1393.
This logs the information about where the extension was build in the log file at startup.
I also cleaned up the startup logging a little bit.
> Log build info

- src/PowerShellEditorServices.Protocol/LanguageServer/EditorCommands.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServerEditorOperations.cs
- src/PowerShellEditorServices/Extensions/EditorContext.cs
- src/PowerShellEditorServices/Extensions/FileContext.cs
- src/PowerShellEditorServices/Language/LanguageService.cs
- src/PowerShellEditorServices/Workspace/Workspace.cs
Partnered with: [vscode-powershell issue]
This fixes the problem where `$psEditor.GetEditorContext()` assumed that the file open was a real file on the file system OR a powershell untitled file. Since that isn't always the case, It would throw an exception:
```
Exception calling "GetEditorContext" with "0" argument(s): "One or more errors occurred. (Could not find file '/Users/tyler/Code/PowerShell/vscode/PowerShellEditorServices/untitled:Untitled-1'.)"
At /Users/tyler/.vscode-insiders/extensions/ms-vscode.powershell-1.9.0/modules/PowerShellEditorServices/Commands/Public/CmdletInterface.ps1:152 char:13
+             $psEditor.GetEditorContext().CurrentFile.InsertText(($val ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: …
```
> New-EditorFile works on non-powershell untitled files

- src/PowerShellEditorServices/Language/FindDeclarationVisitor.cs
- src/PowerShellEditorServices/Language/FindDotSourcedVisitor.cs
- src/PowerShellEditorServices/Language/FindSymbolVisitor.cs
- src/PowerShellEditorServices/Language/FindSymbolsVisitor.cs
- src/PowerShellEditorServices/Language/FindSymbolsVisitor2.cs
Fix descion/decision typo in visitors
Another typo PR, hope you don't mind them. This typo was copy/pasted across a few visitors. It shouldn't be too hard to merge. :)
> Fix descion/decision typo in visitors

- src/PowerShellEditorServices/Workspace/ScriptFile.cs
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
Fixes #781.
See also: https://github.com/dotnet/corefx/issues/32990.
`StringReader.ReadLine()` likes to ditch the last line in a file if it's a newline.
The simplest approach is to replace with a `String.Split()`, which I've done in this PR.
This would probably help up with all the off-by-one errors we keep seeing.
If we don't think `String.Split()` is efficient enough (or want to deduplicate the creation of the array and feeding it into a list), I would be very happy to rewrite this manually.
> Replace bad StringReader usage with String.Split()

- src/PowerShellEditorServices/Utility/PsesLogger.cs
Also update format to display method before filename, makes it easy to
visually scan the log to see what is going on.
Here is log output before this change:
```
2018-11-03 17:26:10.560 [NORMAL] C:\PowerShellEditorServices\src\PowerShellEditorServices.Host\EditorServicesHost.cs: In method 'StartLanguageService', line 194:
```
And after:
```
2018-11-03 17:21:55.858 [NORMAL] [tid:15] In method 'StartLanguageService' C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Host\EditorServicesHost.cs:194:
```
> Add managed thread id to log output to add debugging threading issues

- module/PowerShellEditorServices/PowerShellEditorServices.psm1
- module/PowerShellEditorServices/Start-EditorServices.ps1
- src/PowerShellEditorServices.Host/EditorServicesHost.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/NamedPipeServerChannel.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/NamedPipeServerListener.cs
Some clients have blocking File I/O API, thus it is not possible for them to use single named pipe for reading and writing asynchronously. 
E.g. this is [needed](https://github.com/ant-druha/PowerShell/issues/6) for my PowerShell plugin for IntelliJ IDEs. 
For communication protocol I'm using [lsp4j](https://github.com/eclipse/lsp4j) library which has no issues with tcp protocol but it [does not support named pipes](https://github.com/eclipse/lsp4j/issues/250). So the proposed solution was to use two separate pipes. 
This request adds the ability to use separate pipes for reading and writing when the client specifies the "-SplitInOutPipes" switch for the startup script.
Tested that two pipes approach with my plugin (on OS X and Win7) works fine. Also tested with VS Code on OS X and Win7 …
> Adds ability to use separate pipes for reading and writing

- src/PowerShellEditorServices.Host/BuildInfo/BuildInfo.cs
- src/PowerShellEditorServices/Utility/Logging.cs
- src/PowerShellEditorServices/Utility/PsesLogger.cs
- src/PowerShellEditorServices/Workspace/Workspace.cs
Aims to fix https://github.com/PowerShell/vscode-powershell/issues/1613.
Rather than using method recursion to process recursive directories, we now use a while loop and a stack and stop recursing at a depth of 64.
It's a naive solution to the problem, but I didn't want to do any sophisticated expensive checks like building a hashmap of paths or testing for symlinks in case that would cause a performance hit (although it might not be very important).
I also added a new logging method to log exceptions in the log that aren't really fatal.
> Fix file recursion overflow problems

- src/PowerShellEditorServices.Protocol/LanguageServer/GetCommandRequest.cs
- src/PowerShellEditorServices.Protocol/LanguageServer/GetCommandsRequest.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
This is changes required to accommodate the functionality of [VS Code Feature Request 1405](https://github.com/PowerShell/vscode-powershell/issues/1405)
> Add functionality to allow a Show-Command like panel in VS Code

- src/PowerShellEditorServices.Protocol/LanguageServer/Folding.cs
- src/PowerShellEditorServices.Protocol/LanguageServer/ServerCapabilities.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServerSettings.cs
- src/PowerShellEditorServices/Language/FoldingReference.cs
- src/PowerShellEditorServices/Language/TokenOperations.cs
- test/PowerShellEditorServices.Test/Language/TokenOperationsTests.cs
This commit adds the the code to return folding ranges when the server receives
a FoldingRangeRequest.  This commit;
* Uses a similar method to that implemented in the VS Code extension [1]
* Uses the PowerShell tokeniser instead of the AST.  This is due to the AST
ignoring comment sections.  Without the comment parsing folding for #region
etc. will not work
* Translates the tests in VS Code [1] into equivalent C# tests
[1] PowerShell/vscode-powershell#1355
---
Note that I cannot use the AST for detecting folding regions as the AST drops the comments in the tree.  So I have to use the tokens from the lexer instead (sad-panda)
> (GH-793) Add syntax folding

- src/PowerShellEditorServices/Workspace/Workspace.cs
@rkeithhill Saw that I'd implemented the recursion depth checking incorrectly (I was checking the stack size, which included all the files in parent directories).
I've rewritten this in the simpler recursive function form, which should actually be more efficient (in some ways), although there are pros and cons.
The other thing I noticed tracing this is that we create files for everything in the `.git` directory. We should really implement a file-ignore config and make it default to all files beginning with `.` or something.
> [Ignore] Fix recursion count bug

- src/PowerShellEditorServices/Session/RunspaceDetails.cs
Before, if you did:
```powershell
Enter-PSSession .
Enter-PSSession -HostName tyler@localhost:4321
```
or any variation that uses localhost... this would get marked as a "Local" session and psedit would not get registered (other bad things could have been happening too...).
This fix makes all PSRP sessions "Remote" sessions so that psedit registers correctly.
This also allows a user to start ssh server in WSL or a container and use:
```powershell
Enter-PSSession -Hostname tyler@localhost:4321
```
to get remote editing & debugging in PSES
> Fix local remoting

- NuGet.Config
These sources aren't needed because now that 2.0.0 pulls in PSStandard, it can fetch it from nuget.org which is the default.
And I don't think we need the dotnet-core one.
Also, as a result of this change, I can successfully build PSES offline finally 😄
@rkeithhill do you know if we need the disableSourceControlIntegration at all? We could possibly get rid of this file all together.
> No need for package sources

- module/PowerShellEditorServices/Start-EditorServices.ps1
- src/PowerShellEditorServices.Host/EditorServicesHost.cs
Avoids calling the System.Runtime.InteropServices.RuntimeInformation API that crashes in Win7.
See https://github.com/PowerShell/vscode-powershell/issues/1633.
> Win7 OSArchitecture crash workaround

- PowerShellEditorServices.build.ps1
- src/PowerShellEditorServices.Host/BuildInfo/BuildInfo.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/NamedPipeServerListener.cs
This fixes https://github.com/PowerShell/vscode-powershell/issues/1634
I moved the calls to WaitForConnectionAsync into the thread that they will be awaited on.
> Fix debugging deadlock

- src/PowerShellEditorServices/Language/TokenOperations.cs
- test/PowerShellEditorServices.Test/Language/TokenOperationsTests.cs
From https://github.com/PowerShell/vscode-powershell/issues/1631
Fixes #811
---
In the use case above the following code snippet is confusing the folder;
Bad folder
``` powershell
foreach ($1 in $2) {     <----- STARTS MATCH HERE (1)
$x = @{  <-----   STARTS MATCH HERE (2)
'abc' = 'def'
}        <----- ENDS   MATCH HERE (1) (2)
}
```
Good folder
``` powershell
foreach ($1 in $2) {     <----- STARTS MATCH HERE (1)
$x = @{  <-----   STARTS MATCH HERE (2)
'abc' = 'def'
}        <----- ENDS  MATCH HERE (2)
}        <----- ENDS  MATCH HERE (1)
```
The old grammar based folder knew the difference between a `}` terminating a hash vs a script block.  The PowerShell Tokeniser does not.
Note I found this is also the case for  `@( ... )`, `( ... )`, and `$( ... )`
> (GH-811) Fix folding with spanning regions

- src/PowerShellEditorServices/Workspace/ScriptFile.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/1649.
Finding dot-sourced references when we parse script files currently relies on the file having a directory, which is not true for untitled files.
This is a simple fix for the crash that occurs as a result.
If there's interest, I could try and improve the situation by changing the visitor to have a null PSScriptRoot mean ignore PSScriptRoot paths, or even try to make an untitled dir... (1st feels like it has merit, second maybe not).
> Fix crash when untitled files are opened as PowerShell

- src/PowerShellEditorServices/Language/LanguageService.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/1652 by making the OrderedDictionaries more resilient
> fix references crash

- PowerShellEditorServices.build.ps1
Previously when running tests all tests would need to be run, however when developing this
can take a while.  This commit adds an option to add a trait filter to XUnit
as per the Xunit documentation [1]. Later commits may add the actual trait
attributes to the tests.
[1] https://docs.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests
> (maint) Add Xunit Trait Filter

- test/PowerShellEditorServices.Test/Language/TokenOperationsTests.cs
This commit adds trait attributes to the Code Folding tests, to make development
faster by making it possible to run only a subset of tests.
> (maint) Add traits for folding tests

- src/PowerShellEditorServices/Workspace/ScriptFile.cs
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
This happens because the ScriptFile ctor does not initialize all its
public props.  I added initialization for the other public props
except for the ScriptAst prop.  I don't see an empty Ast.  Perhaps null
is OK for this prop?
This address vscode-powershell bug https://github.com/PowerShell/vscode-powershell/issues/1675
No real need for ScriptTokens to have a backing field. Make it auto like the other props.
Also, for the 2.0.0 branch, we should see if we can use Array.Empty<>()
for initialization.  It isn't availble to net45x.  :-(
> Fix NullRefEx bug when accessing scriptFile.ReferencedFiles

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Workspace/Workspace.cs
Fix https://github.com/PowerShell/vscode-powershell/issues/1676
One change here that makes me a bit nervous is the added `IsPathInMemory()` test to the `GetFile()` method.  However, I observed `GetFile()` crashing when it was passed an `untitled:` path as part of the repro for vscode 1676:
```
System.AggregateException: One or more errors occurred. (Could not find file 'C:\Users\Keith\GitHub\PowerShell\Plaster\untitled:Untitled-2'.) ---> System.IO.FileNotFoundException: Could not find file 'C:\Users\Keith\GitHub\PowerShell\Plaster\untitled:Untitled-2'.
at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess …
```
> Fix FileNotFoundEx crash when Fold happens on untitled: scheme doc

- module/docs/Find-Ast.md
Simplify the parameter descriptions and fix typos.
> Simplify the parameter descriptions and fix typos

- module/PowerShellEditorServices/Commands/Public/Import-EditorCommand.ps1
Change $Strings.EditorCommandRegistering to $Strings.EditorCommandImporting to be in sync with the key name in the Strings.psd1 file.
> Fix an empty verbose message when importing an editor command

- PowerShellEditorServices.build.ps1
- README.md
- module/PowerShellEditorServices/Start-EditorServices.ps1
- src/PowerShellEditorServices.Channel.WebSocket/PowerShellEditorServices.Channel.WebSocket.csproj
- src/PowerShellEditorServices.Host/App.config
- src/PowerShellEditorServices.Host/PowerShellEditorServices.Host.csproj
- src/PowerShellEditorServices.Protocol/PowerShellEditorServices.Protocol.csproj
- src/PowerShellEditorServices.VSCode/PowerShellEditorServices.VSCode.csproj
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- tools/releaseBuild/Image/DockerFile
Technically, `net452` is an in-place upgrade anyway that does not need recompilation but for best practices, PSES should compile against the lowest support .Net Framework so that it works on each Windows machine (as long as they are sufficiently patched), more details are here: https://support.microsoft.com/en-us/help/17455/lifecycle-faq-net-framework
Similarly, after that we should move away from `netcoreapp2.0`, which is also not supported any more
> Compile against net452 because net451 is not supported any more

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Language/FoldingReference.cs
- src/PowerShellEditorServices/Language/TokenOperations.cs
- test/PowerShellEditorServices.Test/Language/TokenOperationsTests.cs
Previously there were no tests for PowerShell classes.  This commit adds a simple
test for this scenario to ensure future changes do not break folding.
Previously the folding provider created many intermediate arrays and lists and
required post-processing.  This commit changes the behaviour to use an
accumlator patter with an extended Dictionary class.  This new class adds a
`SafeAdd` method to add FoldingRanges, which then has the logic to determine if
the range should indeed be added, for example, passing nulls or pre-existing
larger ranges.
By passing around this list using ByReference we can avoid creating many objects
which are just then thrown away.
Previously each token type detection was separated into discrete blocks
to make reading the code easier. However this meant there were …
> (GH-824)(GH-812) Improve code folding speed

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
Fix for one of the issues documented in https://github.com/PowerShell/vscode-powershell/issues/1683
This is a quick fix, still need to make a pass through and look at all uses of `GetFile()`.
> Fix VSCODE 1683 - HelpCommentReqHdlr crash on GetFile

- src/PowerShellEditorServices/Symbols/PesterDocumentSymbolProvider.cs
This update will return null to indicate that the TestName arg was
present but not something we could evaluate.  The extension will see the
null value and pop a dialog box.
> Fix #827 Pester TestName w/expandable str returns nothing

- PowerShellEditorServices.build.ps1
- tools/releaseBuild/Image/DockerFile
- tools/releaseBuild/signing.xml
This enables the release process to work again for the 2.0 changes. Mostly due to things using .NET Standard now.
Also #855 is fixed by warning the user that they need PowerShellGet 1.6.0 or higher due to needing `-AllowPrerelease`
fixes #855
> 🔧 update signing file tidy up build scripts

- CHANGELOG.md
- PowerShellEditorServices.Common.props
- module/PowerShellEditorServices/PowerShellEditorServices.psd1
This PR is mostly for documentation purposes. After this, I'll change the version back to just `2.0.0`.
Note that this PR doesn't have the following changes:
- appveyor.yml: might as well leave this at 2.0.0 if it's just for doc purposes
- PowerShellEditorServices.psd1: PowerShell manifest files only support the version as 2.0.0, no SemVer suffix.
related PR: https://github.com/PowerShell/vscode-powershell/pull/1716
> [Ignore] Prep for 2.0.0-preview.1 release

- src/PowerShellEditorServices/Workspace/Workspace.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/1704 (not the original issue, but that's tracked elsewhere).
This should also go into `legacy/1.x`
> Handle arbitrary exceptions when recursing workspace

- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
- test/PowerShellEditorServices.Test.Protocol/Server/OutputDebouncerTests.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
- test/PowerShellEditorServices.Test/Extensions/ExtensionServiceTests.cs
- test/PowerShellEditorServices.Test/Language/LanguageServiceTests.cs
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
- test/PowerShellEditorServices.Test/Utility/AsyncQueueTests.cs
This also cleans up the build log
> Fix XUnit warnings that better assertion operators should be used.

- PowerShellEditorServices.build.ps1
Previously in commit b13bef14d7771d6ee86c399868a the ability to filter
which tests were run in order to speed up development.  However in commit
449cc21d30ccfc0a7 this was removed. This commit resinstates the test
filtering and uses the new command line arguemnt --filter instead of
the old xunit command.
> (maint) Reinstate test filtering

- src/PowerShellEditorServices/Workspace/Workspace.cs
The 7 exceptions that are caught now are doc'd in:
https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream.-ctor?view=netframework-4.7.2#System_IO_FileStream__ctor_System_String_System_IO_FileMode_System_IO_FileAccess_
Another fix for https://github.com/PowerShell/vscode-powershell/issues/1676
> Catch NotSupportedException which can be thrown by FilleStream ctor

- .travis.yml
This makes the build nearly 1 minute faster. It is a trick that I already added to the PowerShell build [here](https://github.com/PowerShell/PowerShell/blob/master/.vsts-ci/windows.yml) last year
> Speed up travis builds by skipping the .net core initialisation optimisation

- module/PowerShellEditorServices/Commands/Public/Out-CurrentFile.ps1
Also, if a file is not open, it creates a new one
> Added `AsNewFile` switch to Out-CurrentFile

- src/PowerShellEditorServices.Host/CodeLens/PesterCodeLensProvider.cs
Supports PR 1776 in vscode-powershell
> Return the start line number for Describe block

- src/PowerShellEditorServices/Debugging/StackFrameDetails.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/1750
> Temporarily disable deemphasized stack frames to fix VSCode-powershell issue 1750

- src/PowerShellEditorServices.Protocol/DebugAdapter/AttachRequest.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
In PowerShell 6.2 RC we will introduce `-CustomPipeName`. The work is in this PR:
https://github.com/PowerShell/PowerShell/pull/8889
This, along with https://github.com/PowerShell/vscode-powershell/pull/1775 will add support for this parameter in the debug config that is passed to 
```powershell
Enter-PSHostProcess -CustomPipeName $foo
```
~marking this as a Draft PR until RC is released.~
> Support -CustomPipeName

- src/PowerShellEditorServices.Host/CodeLens/CodeLensFeature.cs
- src/PowerShellEditorServices.Host/CodeLens/PesterCodeLensProvider.cs
- src/PowerShellEditorServices.Host/CodeLens/ReferencesCodeLensProvider.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Workspace/ScriptFile.cs
- src/PowerShellEditorServices/Workspace/Workspace.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
This is due to PSES not properly storing a language client path in the
ClientFilePath property of ScriptFile.  This change ensures that a
ClientFilePath is always stored in the text document Uri that a LSP
client expects.  This code has mostly been provided by
@seeminglyScience. Thanks for the reference to your code.
This fixes issue [1732 in the vscode-powershell repo](https://github.com/PowerShell/vscode-powershell/issues/1732).
BTW I've also verified that there are issues when you use the reference code lens where refs to other files that you haven't loaded, will not load when you click on the file in the peek window.
> Fix unable to open files in problems/peek windows issue

- src/PowerShellEditorServices.Host/CodeLens/PesterCodeLensProvider.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/AttachRequest.cs
- src/PowerShellEditorServices.Protocol/LanguageServer/GetRunspaceRequest.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
Adds support for attaching to a local runspace. This extends the existing support for attaching to a runspace in a remote process. This enables debugging for modules that create additional runspaces such as ThreadJob, PoshRSJob and UnivesalDashboard.
> Add attach to local runspace.

- .travis.yml
- module/PowerShellEditorServices/Commands/Public/Out-CurrentFile.ps1
- src/PowerShellEditorServices.Host/CodeLens/PesterCodeLensProvider.cs
- src/PowerShellEditorServices.Protocol/DebugAdapter/AttachRequest.cs
- src/PowerShellEditorServices.Protocol/LanguageServer/GetRunspaceRequest.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Debugging/StackFrameDetails.cs
- src/PowerShellEditorServices/Workspace/Workspace.cs
> WIP Cherry pick for legacy

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
cc @adamdriscoll 
Before, we relied on Enter-PSHostProcess... I noticed that this wasn't working and instead the GeRunspace function would return results from the _current_ runspace instead.
This switches to using `NamedPipeConnectionInfo` API way of invoking something on a remote runspace.
> NamedPipeConnectionInfo <= Enter-PSHostProcess

- src/PowerShellEditorServices.Protocol/Server/LanguageServerSettings.cs
This wires up new PSSA settings from this [PR ](https://github.com/PowerShell/PSScriptAnalyzer/pull/1117)with new vscode-powershell settings [here](https://github.com/PowerShell/vscode-powershell/pull/1687)
> Map new powershell.codeFormatting settings for new rule in PSSA 1.18: PSUseCorrectCasing

- src/PowerShellEditorServices.Protocol/Server/LanguageServerSettings.cs
This wires up new PSSA settings from this [PR ](https://github.com/PowerShell/PSScriptAnalyzer/pull/1092)with new vscode-powershell settings [here](https://github.com/PowerShell/vscode-powershell/pull/1668)
> Map new powershell.codeFormatting settings for new options in PSSA 1.18: WhitespaceInsideBrace and WhitespaceAroundPipe

- src/PowerShellEditorServices.Protocol/Server/LanguageServerSettings.cs
Wire up the new `PipelineIndentationStyle` option that will be added in PSSA PR [here](https://github.com/PowerShell/PSScriptAnalyzer/pull/1102) with the new powershell.codeFormatting setting in the vscode extension to be added by this [PR](https://github.com/PowerShell/vscode-powershell/pull/1669)
This PR can only be merged once PSSA 1.18 has released
> Map new powershell.codeFormatting settings for new options in PSSA 1.18: PipelineIndentationStyle

- src/PowerShellEditorServices.Host/CodeLens/CodeLensFeature.cs
- src/PowerShellEditorServices.Host/CodeLens/PesterCodeLensProvider.cs
- src/PowerShellEditorServices.Host/CodeLens/ReferencesCodeLensProvider.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Workspace/ScriptFile.cs
- src/PowerShellEditorServices/Workspace/Workspace.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
I think I've worked around the compilation issue by replacing `HttpUtility.EncodePath()` with `Uri.EscapeDataPath()`.  The latter API is a much closer match to the RFC 3986 spec that VSCode uses.
Also fixed another bug in the ReferenceCodeLensProvider where it was not properly creating a DocumentUri based on my abusive file name of `foo's_~#-[@] +,;=%.ps1`.  That filename now works when using the symbol ref code lens.
> Cherry pick PR 1750 to legacy/1.x branch, fix more issues 

- src/PowerShellEditorServices.Protocol/Server/LanguageServerSettings.cs
Backport PR #836, #835 (which was no squash-merged!,hence the `-m` option) and #845 (in the same order below):
```sh
git cherry-pick 40cacf64ae7dada8dc5c04c2ad27186a2d001cf6
git cherry-pick -m 1 2316b35c4c05388111c4c2ef02d781c3c4551220
git cherry-pick d8e76fba5be5c792bca34e690c58a502ebdbc2a7
```
> Backport PSSA 1.18.0 PRs

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
Since legacy still supports v3/4, we don't have access to the `NamedPipeConnectionInfo` type.
This will grab that and call `CreateRunspace` via reflection.
This change is only going into legacy... in master it was implemented without reflection in #881.
> backport #881 in a different way

- src/PowerShellEditorServices.Host/CodeLens/ReferencesCodeLensProvider.cs
- src/PowerShellEditorServices/Workspace/Workspace.cs
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
This PR merges the original PR 1750 cherry-pick merge down to the legacy/v1.x branch.  Turns out that merge had an additional fix to the reference code lens provider and better conversion to RFC 3986 URIs.
> Cherry pick PR 1750 merge commit to legacy/v1.x, has additional fixes

- module/PowerShellEditorServices/PowerShellEditorServices.psm1
- src/PowerShellEditorServices.Host/EditorServicesHost.cs
- src/PowerShellEditorServices/Console/ConsoleProxy.cs
- src/PowerShellEditorServices/Console/ConsoleReadLine.cs
- src/PowerShellEditorServices/Console/IConsoleOperations.cs
- src/PowerShellEditorServices/Console/UnixConsoleOperations.cs
- src/PowerShellEditorServices/Console/WindowsConsoleOperations.cs
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Session/Host/EditorServicesPSHostUserInterface.cs
- src/PowerShellEditorServices/Session/Host/TerminalPSHostRawUserInterface.cs
- src/PowerShellEditorServices/Session/Host/TerminalPSHostUserInterface.cs
`ConsoleHost` from `powershell.exe`/`pwsh` still exists within the runspace created at process start. This change grabs the public reference to that host while initializing EditorServicesHost. We can then leverage that host so we can have a much closer to "default" experience.
Resolves #865, #384, PowerShell/vscode-powershell#140, PowerShell/vscode-powershell#1403
This adds support for the following host members:
- WriteProgress (including `Write-Progress`)
- CursorSize (still doesn't work in xterm.js though)
- WindowTitle
- MaxPhysicalWindowSize
- MaxWindowSize
- ReadKey
- GetBufferContents
- ScrollBufferContents
- SetBufferContents
> Use public InternalHost from origin runspace

- .vscode/launch.json
- tools/PsesLogAnalyzer/Analyze.ps1
This is more of an FYI on updates to this log file analysis module.
> Enhance Get-PsesRpcNotificationMessage/MessageResponseTimes to allow filtering by message name

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Workspace/ScriptFile.cs
- src/PowerShellEditorServices/Workspace/ScriptFileMarker.cs
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
In PSScriptAnalyzer 1.18, they've added parse errors to the diagnostic records that get sent back from PSSA.
This broke us because they come in as a different `ScriptFileMarkerLevel` called `ParseError` that we didn't handle. 
This PR adds that additional enum member and also stops PSES sending its own Parse errors as Diagnostics for vscode in favor of PSSA doing all of the diagnostic sending.
cc @bergmeister
> Add new ParseError level to ScriptFileMarkerLevel and only have it send parse errors

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Workspace/ScriptFile.cs
- src/PowerShellEditorServices/Workspace/ScriptFileMarker.cs
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
> cherry pick #888 Add new ParseError level to ScriptFileMarkerLevel and only have it send parse errors

- src/PowerShellEditorServices/Session/PowerShellContext.cs
Previously, when you used the `attach` launch config, if you killed the process that you were attaching to while PSES was attached to it, PSES would go into a bad state and hang forever.
This was because the Runspace wasn't getting cleaned up properly when the connection between the two processes broke.
This change checks for the bad runspace state, cleans up, and pops the bad runspace.
Here's what you see:
```
[DBG]: [Process:42420]: [Runspace1]: PS /Users/tyler/Downloads/anothertestfunc>> 
Command or script completed.
To end the debugging session type the 'Detach' command at the debugger prompt, or type 'Ctrl+C' otherwise.
Leaving debugged runspace on local machine Tylers-MacBook-Pro
The background process reported an error with the following message: "The named pipe target process has …
```
> Clean up and pop dead runspace when using 'attach'

- src/PowerShellEditorServices/Session/PowerShell5Operations.cs
- src/PowerShellEditorServices/Session/PowerShellContext.cs
Previously, when you used the `attach` launch config, if you killed the process that you were attaching to while PSES was attached to it, PSES would go into a bad state and hang forever.
This was because the Runspace wasn't getting cleaned up properly when the connection between the two processes broke.
This change checks for the bad runspace state, cleans up, and pops the bad runspace.
Here's what you see:
```
[DBG]: [Process:42420]: [Runspace1]: PS /Users/tyler/Downloads/anothertestfunc>> 
Command or script completed.
To end the debugging session type the 'Detach' command at the debugger prompt, or type 'Ctrl+C' otherwise.
Leaving debugged runspace on local machine Tylers-MacBook-Pro
The background process reported an error with the following message: "The named pipe target process has …
```
> Clean up and pop dead runspace when using 'attach' for V2

- .vscode/extensions.json
A couple of our recommended extensions are now listed on the marketplace with all lowercase names. Switch to the official name casing as currently displayed in the marketplace.
> Switch to current lowercase names for powershell and mdlint exts

- .gitignore
- PowerShellEditorServices.build.ps1
Ideally, we should avoid this business and just use NuGet's global cache for that but this is a quickfix for not having to delete those folders in AppData that cause build errors when rebuilding. Now, a clean of the repo will sort this out (which is usually run when building the extension or PSES) to make those annoying local build errors disappear
> Move temp folder into repo to avoid state that causes build errors from time to time when rebuilding locally (and packages have updated)

- src/PowerShellEditorServices.Protocol/LanguageServer/Completion.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- test/PowerShellEditorServices.Test.Host/LanguageServerTests.cs
- test/PowerShellEditorServices.Test.Host/TestFiles/CompleteFunctionName.ps1
Need to determine if there are other quote scenarios where we could improve auto-completion.
Fixes https://github.com/PowerShell/vscode-powershell/issues/1398
> Improve path auto-completion

- module/PowerShellEditorServices/Commands/Public/CmdletInterface.ps1
Without this, the file that gets passed in is relative... When it's relative, it hits this piece of code:
https://github.com/PowerShell/vscode-powershell/blob/d02adc54b1f20d2da7cd5efddae3c0a8400ffe2d/src/features/ExtensionCommands.ts#L533-L536
When it does and there is not Folder or File open in the editor, `vscode.workspace.rootPath` is set to `undefined` and thus causes something like `New-EditorFile -Path ./foo.txt` to fail.
With this change, we resolve any filepaths passed in first before sending them to the client.
fixes #905
> Fix New-EditorFile with no folder or no files open

- src/PowerShellEditorServices/Session/PowerShellContext.cs
- src/PowerShellEditorServices/Utility/ExecutionTimer.cs
- src/PowerShellEditorServices/Utility/Logging.cs
- src/PowerShellEditorServices/Utility/PsesLogger.cs
- src/PowerShellEditorServices/Utility/Utils.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/1571.
Also provides a neater API to check Core vs Desktop.
If we ever have a bug with this, we can also use `typeof(object).Assembly.GetName().Name != "mscorlib"`...
> Fix faulty netfx check

- src/PowerShellEditorServices/Utility/Utils.cs
Adds an API for runtime checks to see if we're on .NET Core.
> Add API for runtime CoreCLR check

- src/PowerShellEditorServices/Workspace/Workspace.cs
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
Fixes a few of the failure modes (related to UNC paths) for https://github.com/PowerShell/vscode-powershell/issues/1830
> Fix issue with reference code lens not working with UNC paths

- src/PowerShellEditorServices/Workspace/Workspace.cs
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
* Fix issue with reference code lens not working with UNC paths
* Refactor to avoid extra Insert ops. Simplifies macOS/Linux code path.
* Still need to unescape / on macOs & Linux
* Replace compile-time check for .NET Core with runtime check
> Backport: Fix issue with reference code lens not working with UNC paths (#908)

- tools/PsesLogAnalyzer/Analyze.ps1
- tools/PsesLogAnalyzer/Parse-PsesLog.ps1
Add progress percentage to parse command.
Add textDocument/completion to ValidaeSet of MesssageNameparam 
on Get-PsesRpcMessageResponseTime command.
> Update parse log to handle Read/WrteMessageAsync

- src/PowerShellEditorServices.VSCode/CustomViews/CustomViewFeature.cs
I want to be clear that this is _only_ fixing a bug where:
```powershell
$v = New-VSCodeHtmlContentView -Title foo
$v = New-VSCodeHtmlContentView -Title foo
```
the first time would be an object we expect, the second time, `$v` would be `null` because `.Add` throws if the key already exists. After switching it to use `Id`, there should be no collision.
Ideally this feature could use a `Get-VSCodeHtmlContentView` that pulls from that Dictionary... but that's out of scope.
> Fix silent failure by using Id for dictionary since multiple pages could have the same title

- module/PowerShellEditorServices/Start-EditorServices.ps1
- src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/NamedPipeClientChannel.cs
- src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/NamedPipeServerListener.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
Now that PowerShell Core 6.0 is EOL, all PowerShell Core versions are built on .NET Core 2.1!
This means that we can take advantage of things added to 2.1, namely the CurrentUserOnly flag on PipeOptions which sets up your named pipes so that only the current user can access them.
Because of this, we can remove the Native Pipe implementation that we took from PowerShell Core.
This needs a PR over to vscode-powershell that says PowerShell Core 6.0 is not supported... but the important change is in this PR.
> Remove native named pipes implementation

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
Fix https://github.com/PowerShell/vscode-powershell/issues/1933.
Checks that the workspace path exists before trying to set it as the working directory.
> Stop crash when workspace doesn't exist

- PowerShellEditorServices.build.ps1
- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
- src/PowerShellEditorServices.Protocol/Server/LanguageServerSettings.cs
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Workspace/Workspace.cs
- src/PowerShellEditorServices/Workspace/WorkspaceFileSystemWrapper.cs
- test/PowerShellEditorServices.Test/Fixtures/Workspace/nested/donotfind.ps1
- test/PowerShellEditorServices.Test/Fixtures/Workspace/nested/donotfind.txt
- test/PowerShellEditorServices.Test/Fixtures/Workspace/nested/nestedmodule.psd1
- test/PowerShellEditorServices.Test/Fixtures/Workspace/nested/nestedmodule.psm1
- test/PowerShellEditorServices.Test/Fixtures/Workspace/other/other.cdxml
- test/PowerShellEditorServices.Test/Fixtures/Workspace/other/other.ps1xml
- test/PowerShellEditorServices.Test/Fixtures/Workspace/other/other.psrc
- test/PowerShellEditorServices.Test/Fixtures/Workspace/other/other.pssc
- test/PowerShellEditorServices.Test/Fixtures/Workspace/rootfile.ps1
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
- test/PowerShellEditorServices.Test/Session/WorkspaceTests.cs
Fixes #879 
`LanguageSevice.cs` : `HandleDefinitionRequestAsync` (DefinitionRequest Handler)
`LanguageSevice.cs` : `GetDefinitionOfSymbolAsync`
- Calls `EnumeratePSFiles` AFTER it parses currently loaded files
`LanguageSevice.cs` : `HandleReferencesRequestAsync` (ReferencesRequest Handler)
`LanguageSevice.cs` : `FindReferencesOfSymbolAsync`
- Calls `EnumeratePSFiles`
This is used in the CodeLensFeature, PesterCodeLensProvider and ReferencesCodeLensProvider
`ReferencesCodeLensProvider.cs` : `ResolveCodeLensAsync`
`LanguageSevice.cs` : `FindReferencesOfSymbolAsync`
- Calls `EnumeratePSFiles`
`LanguageSevice.cs` : `HandleWorkspaceSymbolRequestAsync` (WorkspaceSymbolRequest Handler)
- This is weird.  It only looks for symbols in the workspace OPENED files, not ALL files
in the workspace. …
> (GH-879) Add filtering for CodeLens and References

- src/PowerShellEditorServices.Protocol/MessageProtocol/Channel/NamedPipeServerListener.cs
Fixes https://github.com/PowerShell/PowerShellEditorServices/issues/954.
There was a small missing assignment in the startup under the .NET Framework branch.
~~WIP because I'm going to make some style changes :)~~
Merging this will also make #944 pass its Windows PS test!
> Ensure NamedPipeServerStream is assigned in Windows PowerShell

- src/PowerShellEditorServices.Protocol/DebugAdapter/AttachRequest.cs
- src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
Paired with https://github.com/PowerShell/vscode-powershell/pull/1954
Folks will be able to specify a `runspaceName` in their `launch.json`. For example:
```json
{
"type": "powershell",
"request": "attach",
"runspaceName":"PowerShellManager",
"customPipeName":"AzureFunctionsPSWorker"
}
```
Some actually informative `launch.json`s instead of `runspaceId: 1`!
> Allow passing RunspaceName

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2007.
Formatting doesn't check to see if the AnalysisService is null before a method invocation.
> Defend against crash when no PSSA

- src/PowerShellEditorServices.Protocol/PowerShellEditorServices.Protocol.csproj
- tools/PsesPsClient/PsesPsClient.csproj
Update NewtonSoft.Json dependency to 11.02 since PowerShell 6.0 has been deprecated. This version of Newtonsoft is the one shipped with PS 6.1, see source code [here](https://github.com/PowerShell/PowerShell/blob/v6.1.0/src/System.Management.Automation/System.Management.Automation.csproj#L12). It's  version cannot be higher than the one shipped in PowerShell due to DLL unloading not being possible.
Context: At the moment, I am experimenting with attaching PSSA as a .Net NuGet library directly to it and it fails because it detects the package downgrade (PSSA already updated Newtonsoft directly after PS 6.0 had been deprecated)
This is a candidate for 1.x as well but the might need to be done manually in that branch itself as its csproj layout is probably too different.
> Update NewtonSoft.Json dependency from 10.0.3 to 11.02 since PS 6.0 has been deprecated

- PowerShellEditorServices.build.ps1
Fixes https://github.com/PowerShell/vscode-powershell/issues/2027
This PR refactors part of the build logic in `PowerShellEditorServices.build.ps1`, to avoid saving the modules defined in modules.json in versioned subfolders. This allows the modules (currently Plaster and PSScriptAnalyzer) to be loaded when running on PowerShell 3 and 4.
It also moves the modules out of a subfolder in case they're already present and saved from a previous build (wasn't sure if I could assume a clean build).
The build script itself also works in PowerShell 3 and up.
Build and extension both tested on Windows PowerShell 3 and 5.1 & PowerShell 7-preview.
> Refactor build logic to avoid saving modules in subfolders

- src/PowerShellEditorServices.Host/PowerShellEditorServices.Host.csproj
- src/PowerShellEditorServices.Protocol/PowerShellEditorServices.Protocol.csproj
- test/PowerShellEditorServices.Test.Protocol/PowerShellEditorServices.Test.Protocol.csproj
v1.x: Update NewtonSoft.Json dependency from 10.0.3 to 11.02 since PS 6.0 has been deprecated. Backport of #981
> v1.x: Update NewtonSoft.Json dependency from 10.0.3 to 11.02 since PS 6.0 has been deprecated. Backport of #981

- README.md
- docs/guide/using_the_dotnet_api.md
Update the ReadMe and delete documentation that is no longer relevant/up-to-date.
> Doc updates

- src/PowerShellEditorServices.Engine/LanguageServer/OmnisharpLanguageServer.cs
- src/PowerShellEditorServices.Engine/PowerShellEditorServices.Engine.csproj
- src/PowerShellEditorServices.Engine/Services/CodeLens/CodeLensData.cs
- src/PowerShellEditorServices.Engine/Services/CodeLens/ICodeLensProvider.cs
- src/PowerShellEditorServices.Engine/Services/CodeLens/ICodeLenses.cs
- src/PowerShellEditorServices.Engine/Services/CodeLens/IScriptExtentExtensions.cs
- src/PowerShellEditorServices.Engine/Services/CodeLens/PesterCodeLensProvider.cs
- src/PowerShellEditorServices.Engine/Services/CodeLens/ReferencesCodeLensProvider.cs
- src/PowerShellEditorServices.Engine/Services/Symbols/SymbolsService.cs
- src/PowerShellEditorServices.Engine/Services/TextDocument/Handlers/CodeLensHandlers.cs
- src/PowerShellEditorServices.Engine/Services/TextDocument/ScriptRegion.cs
- test/Pester/EditorServices.Integration.Tests.ps1
- tools/PsesPsClient/PsesPsClient.psd1
- tools/PsesPsClient/PsesPsClient.psm1
totally async and doesn't depend on the pipeline thread 😃
> codelens support

- src/PowerShellEditorServices.Engine/LanguageServer/OmnisharpLanguageServer.cs
- src/PowerShellEditorServices.Engine/Services/PowerShellContext/Handlers/IGetPSHostProcessesHandler.cs
- src/PowerShellEditorServices.Engine/Services/PowerShellContext/Handlers/IGetRunspaceHandler.cs
- src/PowerShellEditorServices.Engine/Services/PowerShellContext/Handlers/PSHostProcessAndRunspaceHandlers.cs
- test/Pester/EditorServices.Integration.Tests.ps1
- tools/PsesPsClient/PsesPsClient.psd1
- tools/PsesPsClient/PsesPsClient.psm1
love the consistent casing lol
NOTE: this needed a change to vscode-powershell due to a limitation in the omnisharp lib.
They don't support sending just string messages, they have to be a json body. As such, I've changed the parameters for the `getRunspace` request from just a `string` representing the ProcessId to:
```csharp
public class GetRunspaceParams : IRequest<RunspaceResponse[]>
{
public string ProcessId {get; set; }
}
```
Nothing else should be impacted because I don't think any other editor supports debugging... but this is the FYI.
> powerShell/getPSHostProcesses & powerShell/getRunspace

- src/PowerShellEditorServices/Workspace/Workspace.cs
Backport of https://github.com/PowerShell/PowerShellEditorServices/pull/1000
> Fix crash when setBreakpoint from VSCode sends a git:/ URI... (#1000)

- scripts/azurePipelinesBuild.ps1
- src/PowerShellEditorServices.Engine/LanguageServer/OmnisharpLanguageServer.cs
- src/PowerShellEditorServices.Engine/Services/PowerShellContext/Utilities/CommandHelpers.cs
- src/PowerShellEditorServices.Engine/Services/Symbols/Vistors/AstOperations.cs
- src/PowerShellEditorServices.Engine/Services/TextDocument/CompletionResults.cs
- src/PowerShellEditorServices.Engine/Services/TextDocument/Handlers/CodeActionHandler.cs
- src/PowerShellEditorServices.Engine/Services/TextDocument/Handlers/CodeLensHandlers.cs
- src/PowerShellEditorServices.Engine/Services/TextDocument/Handlers/CompletionHandler.cs
- src/PowerShellEditorServices.Engine/Services/TextDocument/Handlers/DocumentHighlightHandler.cs
- src/PowerShellEditorServices.Engine/Services/TextDocument/Handlers/DocumentSymbolHandler.cs
- src/PowerShellEditorServices.Engine/Services/TextDocument/Handlers/FoldingRangeHandler.cs
- src/PowerShellEditorServices.Engine/Services/TextDocument/Handlers/FormattingHandlers.cs
- src/PowerShellEditorServices.Engine/Services/TextDocument/Handlers/ReferencesHandler.cs
- src/PowerShellEditorServices.Engine/Services/TextDocument/Handlers/TextDocumentHandler.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
- test/PowerShellEditorServices.Test.E2E/TestsFixture.cs
Comes after #1007 
This adds support for `completionItem/resolve`
> completionresolve support

- src/PowerShellEditorServices.Engine/LanguageServer/OmnisharpLanguageServer.cs
- src/PowerShellEditorServices.Engine/Services/Symbols/SymbolDetails.cs
- src/PowerShellEditorServices.Engine/Services/Symbols/SymbolsService.cs
- src/PowerShellEditorServices.Engine/Services/TextDocument/Handlers/HoverHandler.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
- test/PowerShellEditorServices.Test.E2E/TestsFixture.cs
After #1009 
Supports `textDocument/hover`
> hover support

- src/PowerShellEditorServices.Engine/LanguageServer/OmnisharpLanguageServer.cs
- src/PowerShellEditorServices.Engine/Services/Symbols/ParameterSetSignatures.cs
- src/PowerShellEditorServices.Engine/Services/Symbols/SymbolsService.cs
- src/PowerShellEditorServices.Engine/Services/TextDocument/Handlers/SignatureHelpHandler.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
- test/PowerShellEditorServices.Test.E2E/TestsFixture.cs
After #1010 
This supports the `textDocument/signatureHelp`
> Omni signaturehelp

- src/PowerShellEditorServices.Engine/Hosting/EditorServicesHost.cs
- src/PowerShellEditorServices.Engine/LanguageServer/OmnisharpLanguageServer.cs
- src/PowerShellEditorServices.Engine/Services/PowerShellContext/PowerShellContextService.cs
- src/PowerShellEditorServices.Engine/Services/Symbols/SymbolsService.cs
- src/PowerShellEditorServices.Engine/Services/TextDocument/Handlers/DefinitionHandler.cs
- src/PowerShellEditorServices.Engine/Services/TextDocument/Handlers/SignatureHelpHandler.cs
- src/PowerShellEditorServices.Engine/Utility/PathUtils.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
The supports the `textDocument/definition` request.
P.S. I also snuck in what fires the `powerShell/executionStatusChanged` message.
> Add definition handler

- src/PowerShellEditorServices.Engine/Hosting/EditorServicesHost.cs
- src/PowerShellEditorServices.Engine/LanguageServer/OmnisharpLanguageServer.cs
- src/PowerShellEditorServices.Engine/Services/PowerShellContext/Handlers/ITemplateHandlers.cs
- src/PowerShellEditorServices.Engine/Services/PowerShellContext/Handlers/TemplateHandlers.cs
- src/PowerShellEditorServices.Engine/Services/PowerShellContext/TemplateService.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
This supports:
`powerShell/getProjectTemplates`
and
`powerShell/newProjectFromTemplate`
note: I couldn't really add a test for `powerShell/newProjectFromTemplate` because it requires interaction over the console, but `powerShell/getProjectTemplates` is tested.
> Add Plaster messages

- src/PowerShellEditorServices.Engine/LanguageServer/OmnisharpLanguageServer.cs
- src/PowerShellEditorServices.Engine/Services/Analysis/AnalysisService.cs
- src/PowerShellEditorServices.Engine/Services/PowerShellContext/Handlers/EvaluateHandler.cs
- src/PowerShellEditorServices.Engine/Services/PowerShellContext/Handlers/GetCommentHelpHandler.cs
- src/PowerShellEditorServices.Engine/Services/PowerShellContext/Handlers/IEvaluateHandler.cs
- src/PowerShellEditorServices.Engine/Services/PowerShellContext/Handlers/IGetCommentHelpHandler.cs
- src/PowerShellEditorServices.Engine/Services/Symbols/SymbolsService.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
First review #1014
This supports `powerShell/getCommentHelp` request which is used to generate the nice comment based help and `evaluate` which is the F8 experience.
> Comment Help and Evaluate

- src/PowerShellEditorServices.Protocol/MessageProtocol/MessageWriter.cs
This helps protect from a crash we were seeing with the "Start without debugging" feature in VS Code.
> Catch stream exceptions for some Debug Adapter stability.

- modules.json
because PSGet was giving us beta4 instead of beta5 for PSReadLine.
> update modules for PSScriptAnalyzer and PSReadLine.

- src/PowerShellEditorServices.Protocol/Server/LanguageServerSettings.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2214
The backport PR #1024 did a correct cherry-pick but git did not merge the code change correctly and undid a line that was added in an earlier PR.
Locally verified.
> legacy/1.x: Fix 'git cherry-pick' merge error causing pipelineIndentationStyle setting to not be correctly wired up

- modules.json
This does not change anything (because it already pulls 1.18.3 down by default) but makes it consistent with the master branch to keep the difference between the 2 branches minimal to avoid future conflicts.
> legacy/1.x: Update minimum PSSA version to 1.18.3

- src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
fixes https://github.com/PowerShell/vscode-powershell/issues/2116
This escapes all `\` `}` and `$` so that the intellisense is properly escaped for Textmate to render it.
(yes, we don't need to escape `{`)
> Fix UNC intellisense backslash

- src/PowerShellEditorServices/Server/PsesDebugServer.cs
- src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
This adds back support for the `powerShell/startDebugger` message with the added feature of being able to start the debugger even on a fresh open of vscode.
I couldn't find the issue, but there's a limitation in PSES currently where you have to start debugging at least once before the `startDebugger` message gets fired. This PR fixes that.
> implement powerShell/startDebugger

- src/PowerShellEditorServices/Services/Workspace/LanguageServerSettings.cs
Port of https://github.com/PowerShell/PowerShellEditorServices/pull/1021 to the omnisharp port
> Enable alias corrections

- README.md
fixes #1057
Note, this is not exhaustive but I wanted to write _something_ down to at least give folks a place to start.
In theory a more exhaustive doc should be elsewhere (like on docs.microsoft.com) but this will do for now.
> Quick start doc in README

- PowerShellEditorServices.build.ps1
- src/PowerShellEditorServices/Hosting/EditorServicesHost.cs
- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/LaunchAndAttachHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/ExpandAliasHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/GetCommandHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/IEvaluateHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/IGetCommentHelpHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/IGetPSHostProcessesHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/IGetRunspaceHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/IGetVersionHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/IInvokeExtensionCommandHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/ITemplateHandlers.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/InvokeExtensionCommandHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/ShowHelpHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/TextDocumentHandler.cs
- src/PowerShellEditorServices/Services/Workspace/Handlers/ConfigurationHandler.cs
the title says it all... 3 cheers for the .NET builder pattern.
Here's what our logs look like.
[EditorServices.log](https://github.com/PowerShell/PowerShellEditorServices/files/3725937/EditorServices.log)
Note, we still need [this issue](https://github.com/OmniSharp/csharp-language-server-protocol/issues/181) to be resolved to get logs of the payload... but we can get the payloads... just not in the file logs... the user can add:
```
"powershell editor services.trace.server":"verbose"
```
in their settings which will give them an Output window in vscode that contains the payloads that is compliant with the [lsp inspector](https://microsoft.github.io/language-server-protocol/inspector/).
It's an extra process.. but it's the best we've got so far. It will get better.
Note this also updates …
> Rework log builder to support logging to files

- src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
This brings #1044 into the omnisharp work. It fixes UNC path completions.
> Forwardport 1044 fixing UNC path completions

- src/PowerShellEditorServices/Services/PowerShellContext/Console/ConsoleProxy.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/PSReadLinePromptContext.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/1753
What this does is has PSRL override its ReadKey with ours on Windows as well so we can properly cancel the ReadKey when we need to for things like when you F8 a `Read-Host`.
> Override PSRL ReadKey on Windows as well

- module/PowerShellEditorServices/PowerShellEditorServices.psm1
- src/PowerShellEditorServices/Hosting/EditorServicesHost.cs
- src/PowerShellEditorServices/Server/PsesDebugServer.cs
- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
- src/PowerShellEditorServices/Server/PsesServiceCollection.cs
- src/PowerShellEditorServices/Server/PsesServiceCollectionExtensions.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
This isn't quite ready yet. But I wanted to share what it took.
> Fix TEMP debugging

- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
- src/PowerShellEditorServices/Services/CodeLens/ReferencesCodeLensProvider.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/GetVersionHandler.cs
- src/PowerShellEditorServices/Services/Symbols/ScriptDocumentSymbolProvider.cs
- src/PowerShellEditorServices/Services/Symbols/SymbolsService.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DocumentSymbolHandler.cs
- src/PowerShellEditorServices/Utility/VersionUtils.cs
PSVersion is only a `Version` type so it has no information on prerelease tag. This caused an issue in vscode-powershell while trying to determine the version for the Update PowerShell feature.
This change will now expose a `PSVersionString` that will first check `PSCurrentVersion` if it's available and then fallback to `Version` if not.
I also removed some references to `VersionUtils.PSVersion` that were not needed.
Also, this includes a small change due to a breaking change in Omnisharp.
> Grab prerelease if it's available from PSCurrentVersion

- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/EditorServicesPSHost.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/EditorServicesPSHostUserInterface.cs
Add FormatAccentColor and ErrorAccentColor used by PS7 for new ConciseView and Resolve-ErrorRecord cmdlets (and likely tables and list formatting)
> New colors supported by PS7

- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj
Lock OmniSharp LSP and DAP dependencies to 0.14.0
> Lock OmniSharp dependencies

- PowerShellEditorServices.build.ps1
- src/PowerShellEditorServices/Session/Host/EditorServicesPSHost.cs
- src/PowerShellEditorServices/Session/Host/EditorServicesPSHostUserInterface.cs
Backport of https://github.com/PowerShell/PowerShellEditorServices/pull/1064.
> New colors supported by PS7 (#1064)

- src/PowerShellEditorServices/Services/TextDocument/Handlers/TextDocumentHandler.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
I discovered that duplicate diagnostics were being sent to vscode because we iterated through the _ContentChanges_ and asked for diagnostics in that loop, even though, the changes pertained to the same file.
You can see the bug if you type really fast or use like the `##` comment generator and stuff like that because it will include multiple _ContentChanges_ to the _same file_ in 1 textDocument/DidChange event.
This properly runs diagnostics _after_ all code changes are applied.
Discovered this originally in #1078 (which has a similar change in it as well... thought it might affect us today and sure enough, it did!)
comes with a test too!
> Fix duplicate diagnostics caused by DidChange handler

- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/GetCommentHelpHandler.cs
The ## comment generation feature has started putting a new line between the comment and the function... That doesn't seem right.
This trims that extra newline in PSES.
> Remove extra newline in GetComment feature

- src/PowerShellEditorServices.Protocol/Server/LanguageServerSettings.cs
Somehow the commit from https://github.com/PowerShell/PowerShellEditorServices/pull/1050 is no longer in the legacy/1.x branch.
This PR reinstates that change.
> Fix issue where PipelineIndentationStyle setting is ignored

- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
fixes https://github.com/PowerShell/vscode-powershell/issues/1850
After reading the code, I realized that this was much simpler than I initially thought. No newline was written when a breakpoint was hit and so no prompt was being written because the cursor position was in the same location.
I'm not sure if this also fixes the mixed output... I don't think it does.
> Fixes no prompt showing up

- src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Services/Symbols/ScriptDocumentSymbolProvider.cs
fixes https://github.com/PowerShell/vscode-powershell/issues/2290
It's both a fix (Diagnostics showing up in Untitled files again)
and a feature (CodeLens showing up in Untitled files now)
It does ask a greater question of - can `scriptFile`s have a reference to their `Uri` object now since O# does an awesome job at giving us the `Uri`s for files already.
Also I feel like the tests might have covered this regression... I really need to sit down and bring those back.
> Fix diagnostics not showing in untitled files and now also show CodeLens

- src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
See docs below for info. The rule warns only on read-only, automatic variables where assignment would cause an error to be thrown at runtime, therefore there is no scope for false positives.
https://github.com/PowerShell/PSScriptAnalyzer/blob/master/RuleDocumentation/AvoidAssignmentToAutomaticVariable.md
Example of what  would happen at runtime in the console if one ignored such a violation:
```
> $error = 42
WriteError: Cannot overwrite variable Error because it is read-only or constant.
```
We should back-port this change
> Add PSAvoidAssignmentToAutomaticVariable to the default set of PSSA rules

- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
Fixes #1093
Fixes https://github.com/PowerShell/vscode-powershell/issues/2288
`RootPath` is shorthand for `RootUri.AbsolutePath` which comes in the wrong format on Windows. This should use the correct `\` and the likes.
Also `RootPath` is deprecated.
cc @SeeminglyScience
> Use RootUri.LocalPath for workspace path

- src/PowerShellEditorServices/Services/PowerShellContext/Console/ConsoleProxy.cs
Changes the key we return to PSRL when the prompt is cancelled to a down arrow.
This resolves https://github.com/PowerShell/vscode-powershell/issues/2274.
> Fix '@' appearing in console

- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2311
As you can see, when WorkspacePath is null, it's handled on the next line and this is [consistent with the behavior of the legacy code](https://github.com/PowerShell/PowerShellEditorServices/blob/legacy/1.x/src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs#L226-L235).
> Protect against no RootUri (no open workspace)

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
See below link for instructions but basically one just needs to have Docker running in Linux mode with file sharing enabled, install the `ms-vscode-remote.remote-containers` and then just open VS-Code in that folder and use the command to re-open the folder in a container. Because it is early days, one cannot set the default shell to PowerShell yet, but one can define the following user setting to have the shell that is attached to the container starting with PowerShell instead of bash.
`"terminal.integrated.shell.linux": "/usr/bin/pwsh",`
https://code.visualstudio.com/docs/remote/containers
> Add devcontainer support for building in container

- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
- src/PowerShellEditorServices/Services/CodeLens/ReferencesCodeLensProvider.cs
fixes https://github.com/PowerShell/vscode-powershell/issues/2306
The WorkspacePath change I made in #1094 was almost the right change for Windows... but not quite.
This will set the WorkspacePath to an _actual_ path - verified on Windows.
This also fixes a bug I discovered when a symbol reference and a definition were on the same line number but different files (they weren't being counted as a reference).
> Fix references on Windows due to bad WorkspacePath

- src/PowerShellEditorServices/Services/DebugAdapter/DebugEventHandlerService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/DebugStateService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/BreakpointHandlers.cs
We were using a boolean as a check for if something was currently happening... and when we moved to Omnisharp lib it was kinda being used as a lock :)
This caused a deadlock. Proper thread safety has prevented the deadlock.
> Fix breakpoint setting deadlock

- module/PowerShellEditorServices/Commands/Public/Import-EditorCommand.ps1
It appears that PR #1056 involved renaming the `extensionService` field to `_extensionService` but this wasn't changed in the `Import-EditorCommand` function causing an error when trying to use it.
Following a discussion with @TylerLeonhardt on the PowerShell Discord server I've submitted this PR to fix the error by updating the field name in `Import-EditorCommand`.
I didn't see any tests or anything that needed to be changed but let me know if you need me to do anything else in order for this to be accepted 🙂
> Fix Import-EditorCommand bug

- src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
Previously for every `SetBreakpoints` request we would invoke `ExecuteCommandAsync` once for every single breakpoint. This change reduces that to a single call per request.
Before this change, if I followed the repro steps for PowerShell/vscode-powershell#2319, setting 10 breakpoints in File2 and File3, I couldn't even get it to launch once.  With this change I can consistently launch every time.
There's definitely some race conditions in how runspace handles are queued, and the way this request handler was set up was really pushing that to it's limits.  Those race conditions still need to be fixed, but this should help significantly in the mean time.
> Run one invocation per SetBreakpoints request

- module/PowerShellEditorServices/Commands/PowerShellEditorServices.Commands.psd1
- module/PowerShellEditorServices/Commands/Public/Clear-Host.ps1
- src/PowerShellEditorServices/Services/PowerShellContext/EditorOperationsService.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Extensions/EditorTerminal.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Extensions/EditorWindow.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Extensions/IEditorOperations.cs
This fixes an "issue" that comes up a lot that when you `Clear-Host` and are still able to scroll up.
On non-Windows this is the typical behavior of `Clear-Host` but on Windows the expectation is that the console is truly cleared out. This sends a message to the client to say "hey clear the terminal" and if the terminal properly supports a "true clear" in can register a handler for this notification.
Pairs with: https://github.com/PowerShell/vscode-powershell/pull/2316
> Clear the terminal via the LSP

- module/PowerShellEditorServices/Commands/Public/Clear-Host.ps1
Fixes https://github.com/PowerShell/vscode-powershell/issues/2379
Adds `-Option AllScope` to `Set-Alias` to fix an error Windows PowerShell was spitting out.
> use -Option AllScope to fix Windows PowerShell error

- src/PowerShellEditorServices/Services/CodeLens/ReferencesCodeLensProvider.cs
fixes https://github.com/PowerShell/vscode-powershell/issues/2374
Before, I had the logic backwards and the CodeLens would only show 1 reference (the reference definition!).
After, now we only check file path and line number. Simpler logic.
I added a TODO to think about what would happen if we find two of the same named function definitions:
fileA
```
function Test-Foo { }
```
fileB
```
function Test-Foo { }
```
The references will probably show up... but I think there's not much we can do since the symbol reference doesn't seem to give us anything on whether it's a definition or not which is really a shame.
> Simplify logic of determining Reference definition

- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/VariableDetails.cs
- test/PowerShellEditorServices.Test.Shared/Debugging/VariableTest.ps1
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2386
Some values return `null` from `.ToString()`. This PR makes sure we check for null and return the type information if it is null.
A simple way to test this out is to store a var like `$var = [NullString]::Value` and debug the script with breakpoints. The powershell extension will error out.
> Fix uncaught exception when SafeToString returns null

- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
- src/PowerShellEditorServices/Services/PowerShellContext/EditorOperationsService.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeActionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeLensHandlers.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DefinitionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DocumentHighlightHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DocumentSymbolHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/FoldingRangeHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/FormattingHandlers.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/HoverHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/ReferencesHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/SignatureHelpHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/TextDocumentHandler.cs
- src/PowerShellEditorServices/Services/Workspace/Handlers/WorkspaceSymbolsHandler.cs
- src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs
- src/PowerShellEditorServices/Utility/PathUtils.cs
- src/PowerShellEditorServices/Utility/VersionUtils.cs
- test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj
Fixes https://github.com/PowerShell/vscode-powershell/issues/2324
This removes  any usage of `Uri.ToString()` and creates a `worspaceService.GetFile(` that takes a `Uri` to better abstract this away.
This also revs the Omnisharp lib that contains my fix that also removes usages of `Uri.ToString()`
> Fix unicode character uri bug

- module/PowerShellEditorServices/Commands/Public/CmdletInterface.ps1
- src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
- src/PowerShellEditorServices/Hosting/EditorServicesServerFactory.cs
- src/PowerShellEditorServices/Services/PowerShellContext/EditorOperationsService.cs
- src/PowerShellEditorServices/Services/PowerShellContext/ExtensionService.cs
- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2402
Apparently, when I added `$psEditor` back in, I broke Temp debugging again...
Now it works. The main changes are:
* Add a null `ILanguageServer` to the service collection so that the `EditorOperationsService` has something to retrieve
* If the languageServer is null, warn the user to use the main PowerShell Integrated Console
* Bring in @rjmholt 's change in #1148 
* Actually have `$psEditor` be available in the console by triggering the creation of the service that sets the psvariable
> Fix temp debugging after it broke bringing in $psEditor

- src/PowerShellEditorServices/Server/PsesDebugServer.cs
- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/ThreadController.cs
- src/PowerShellEditorServices/Utility/AsyncQueue.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2352.
Dequeuing work to execute on the pipeline thread used to be async/await without using `ConfigureAwait(false)`. This meant that introducing a thread synchronisation context (like WinForms does) could break our thread architecture.
Particularly in the WinForms case, the work dequeuing delegate would be marshalled back to the pipeline thread, which was blocked by the stopped debugger, so unable to execute.
Now we use `ConfigureAwait(false)` so that the lock delegate's execution is not influenced by the synchronisation context.
> Fix lock up that occurs when WinForms is executed on the pipeline thread

- src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2393.
Allows loading of netstandard.dll on downlevel .NET Framework versions.
We falsely assumed that getting PowerShell to load an assembly module would automatically resolve dependencies in the same directory, but this is actually a property of PowerShell 6+ rather than .NET.
Now we look in the .NET Framework dir on an assembly resolve event before looking in the shared dependencies directory.
> Probe .NET Framework dir for dependencies

- src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
Moved it to a switch so it's easier to read. This will show the tooltips for `ParameterValue`
fixes https://github.com/PowerShell/vscode-powershell/issues/2405
> Add tooltip to completions ParameterValue

- .dependabot/config.yml
Since we're doing the (hopefully) final release out of the legacy, we should disable dependabot.
> [Ignore] disable dependabot for legacy branch

- PowerShellEditorServices.build.ps1
- Change `Build` to remove bin directories that must always be refreshed in the output binary
- Change `Clean` to also wash away the downloaded bundled modules
Also fixes https://github.com/PowerShell/PowerShellEditorServices/issues/1135.
> Improve Clean and Build tasks

- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
fixes https://github.com/PowerShell/vscode-powershell/issues/2421
The WorkspacePath should be a _path_ not a _uri_. This changes that back so that things like `Directory.Exists(...)` works and the likes.
I made sure this still works with non-ascii characters and unix & Windows path styles:
```
❯❯❯ [Uri]::new("file:///C:/a/%E6%B5%8B.ps1").LocalPath
C:\a\测.ps1
❯❯❯ [Uri]::new("file:///C:/a/%E6%B5%8B.ps1").LocalPath
C:\a\测.ps1
❯❯❯ [Uri]::new("file:///C:/a/blah.ps1").LocalPath
C:\a\blah.ps1
❯❯❯ [Uri]::new("file:///Users/a/blah.ps1").LocalPath
/Users/a/blah.ps1
❯❯❯ [Uri]::new("file:///Users/a/%E6%B5%8B.ps1").LocalPath
/Users/a/测.ps1
```
> Use LocalPath instead of OriginalString

- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/EditorServicesPSHostUserInterface.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/ProtocolPSHostUserInterface.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/TerminalPSHostUserInterface.cs
This fixes a lot of the prompt/output issues that we've been seeing.
fixes https://github.com/PowerShell/vscode-powershell/issues/2372
fixes https://github.com/PowerShell/vscode-powershell/issues/2407
fixes https://github.com/PowerShell/vscode-powershell/issues/2408
* It removes a useless `this.WriteOutput` when instead `ExecuteCommandAsync` could just do it
* The `WriteOutput` in the finally block now only runs in the legacy readline experience
There's still a weird thing happening with prompts on F5... but that existed before this change so I'll try to address that in another PR.
> Fix debugging output location

- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
There was a race condition where the fact that we'd execute each profile individually would be too fast for the PowerShell runspace and would throw this hideous error:
```
2020-01-27 15:18:50.254 -08:00 [FTL] Failed to handle request workspace/didChangeConfiguration
System.InvalidOperationException: A PowerShell object cannot be created that uses the current runspace because there is no current runspace available.  The current runspace might be starting, such as when it is created with an Initial Session State.
at System.Management.Automation.PowerShell.Create(RunspaceMode runspace)
at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.<>c.<GetSessionDetailsInNestedPipeline>b__153_0(PSCommand command) in D:\a\1\s\src\PowerShellEditorServices\Services\PowerShellContext\Po …
```
> run profile paths together

- src/PowerShellEditorServices/Services/PowerShellContext/Session/PSReadLinePromptContext.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2420.
As @daxian-dbw explained, PSReadLine fires off its ReadKey call on a different thread to be asynchronous. This means the PSReadLine call can return before the ReadKey delegate has been called, leading to a condition where the `finally` block had set the cancellation token to `null` but our `ReadKey` delegate hadn't been run yet.
It turns out we don't need to set the cancellation token source to null; it will get reset on the next call anyway.
> Fix crash on paste

- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/EditorServicesPSHostUserInterface.cs
fixes https://github.com/PowerShell/vscode-powershell/issues/1790
Changes the default to `string.Empty` to be constant with ConsoleHost.
This also means that `Read-Host` and `Read-Host -Prompt` have the same behavior when the user just hits `<ENTER>` on a prompt.
> switch to string.empty

- src/PowerShellEditorServices/Services/TextDocument/ScriptFile.cs
- src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs
This optimizes the `ScriptFile` constructor and also fixed an issue where in-memory files wouldn't be able to get CodeLens.
I want to get to a point where `DocumentUri` on the `ScriptFile` class is a reference to `System.Uri` but I'm gonna call that out of scope due to time constraints.
I believe this change is needed for #1119 as well
> Fix untitled file references

- src/PowerShellEditorServices.Hosting/Configuration/HostLogger.cs
- src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Console/WindowsConsoleOperations.cs
- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/EditorServicesPSHostUserInterface.cs
Makes the following changes:
- Changes `Task.Factory.StartNew` invocations to `Task.Run` to simplify the child attach semantics (invoking tasks won't hang around for new threads to finish now, since in the places where we use it, it seems we really wanted to kick off a new thread)
- Removes `async`/`await` from methods that just do some setup and run another task
- Adds a `TaskOptions.LongRunning` hint to the logger thread so that it's less likely to impact the thread pool. The other option here is to use a new `Thread` and bypass the thread pool altogether. Happy to do either (but this one represents a smaller change).
> Improve Task usage

- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/EditorServicesPSHostUserInterface.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/ProtocolPSHostUserInterface.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/TerminalPSHostUserInterface.cs
I needed to remove the check of PSReadLine because in the PSRL experience, whether you used ENTER or Ctrl-C, we'd still only get empty string...
This means that it would work with ENTER as ENTER would cause the cursor to go down... but Ctrl-C didn't.
I'm not sure if this is a PSRL bug that only we are exposing or actually our bug... but this makes it less ugly for sure.
The downside is that once the screen starts scrolling, an extra new line shows up.
cc @daxian-dbw if you're curious.
> mitigate prompt issue

- src/PowerShellEditorServices/Server/PsesServiceCollectionExtensions.cs
- src/PowerShellEditorServices/Services/DebugAdapter/BreakpointService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/DebugStateService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/BreakpointApiUtils.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/BreakpointDetails.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/CommandBreakpointDetails.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/BreakpointHandlers.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/InitializeHandler.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/LaunchAndAttachHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/Capabilities/DscBreakpointCapability.cs
- src/PowerShellEditorServices/Utility/LspDebugUtils.cs
- src/PowerShellEditorServices/Utility/VersionUtils.cs
This moves to the new breakpoint APIs in PS 7 which enables the ability to debug actual untitled files!
This will also allow things like Azure Functions to not need a Wait-Debugger in their script.
I also accidentally supported Log Points!
To do this, I created a new service `BreakpointService` that helps manage this.
I took a bunch of the reflection code from @rjmholt's branch of a similar feature.
NOTE: We should probably discuss the Function breakpoints feature... Today, it works in _all_ versions of PowerShell by creating a temp file on the fly and using that for debugging. That doesn't seem like the best approach... because temp files could go south. Ideally we should use same strategy that I'm doing here for function breakpoints as well... but I feel like that's out of scope for …
> Initial switch to breakpoint APIs

- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeActionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/ScriptRegion.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
- test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj
Fixes https://github.com/PowerShell/PowerShellEditorServices/issues/1191
This allows us to show up here:
cc @mjbvz
> Move to CodeAction

- src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
When you're on macOS or Linux using PS6, we default to using the Legacy Console experience.
However, this exposed a bug where the PSRL static constructor was still being run in debug sessions because the check for non-Windows PS6 was happening later.
This moves that logic up so that it's correct when debug sessions are created.
> Move PSRL decision option to be in Hosting

- CHANGELOG.md
- PowerShellEditorServices.Common.props
Going to leave the main changelog notes for the VSCode changelog, since that's where the version scheme has bifurcated.
> Update CHANGELOG and version for preview.9 release

- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/EditorServicesPSHostUserInterface.cs
@daxian-dbw found a strange behavior in the Console's PSHost [where empty lines are skipped](https://github.com/PowerShell/PowerShell/blob/8e683972284a5a7f773ea6d027d9aac14d7e7524/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L1334-L1337) in `WriteErrorLine`.
He also discovered that errors were not going into the Error stream unless they have the `WriteStream` property set to `Error`.. which sadly can only be done via reflection.
This leverages that so that errors are printed out correctly instead of with this ugly line:
Also actually uses PowerShell to format parse errors correctly.
> Make sure ErrorRecords go to Error stream

- src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
- src/PowerShellEditorServices.Hosting/Configuration/HostLogger.cs
- src/PowerShellEditorServices.Hosting/Configuration/TransportConfig.cs
- src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
- src/PowerShellEditorServices.Hosting/Internal/EditorServicesRunner.cs
- Makes disposal logic simpler
- Passes tasks through rather than awaiting them internally
- Fixes a bug where the logger was catching the wrong exception type
- Always kick the PSES start logic onto a new thread
> Startup task tweaks

- src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Services/Analysis/PssaCmdletAnalysisEngine.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2489.
> Fix PSSA settings discovery + pick up changes to settings file

- src/PowerShellEditorServices/Server/PsesDebugServer.cs
fixes https://github.com/PowerShell/vscode-powershell/issues/2291
So this class constructor is needed to run for temp sessions but it's not needed for regular sessions.
I confirmed the following worked properly:
* Temp session with script: "Read-Host"
* Regular session with script: "Read-Host"
* Regular session with script: "'hi'"
Temp session with script: "'hi'"
Eventually we want to get rid of this `ExecuteScriptStringAsync` for Constrained language mode support but this change gets us the expected behavior.
> Fix Read-Host behavior which mangles input

- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/EvaluateHandler.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2424
When you hit F8 in an interactive session that kicked the debugger on and stopped at a breakpoint, F8 would no longer work. This is because we were waiting for the original F8 to finish.
This changes the evaluate message to fire and forget which allows F8 to be run after the breakpoint is stopped.
> Fire and forget evaluate

- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/EditorServicesPSHostUserInterface.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2404.
Now, on startup, we do our best to inherit the correct execution policy.
> Fix how we set execution policy

- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2504.
We were setting the execution policy before importing PSReadLine. Now we set it afterward.
Not sure what happens with PSSA here.
Ideally we could solve this by linking against those libraries rather than importing them as modules.
EDIT: It also turns out that Execution Policy scope order wasn't what we thought it would be, so we were setting a lower scope first. We now set the CurrentUser scope ahead of the LocalMachine scope.
> Fix startup in AllSigned execution policy

- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2364.
Fixes https://github.com/PowerShell/vscode-powershell/issues/2488.
May fix https://github.com/PowerShell/vscode-powershell/issues/2396.
After debugging is stopped, the PowerShellContextService was being marked as being in session state aborted. Now we set the state to ready.
This fix isn't ideal, since it's made without a full understanding of the conceptual state machine of the PowerShellContextService, but it does fix the issues for the coming release while we sift through the actual architectural cause of the problem (and ideally fix it down the line)
> Fix bad context state after debugging

- module/PowerShellEditorServices/Commands/PowerShellEditorServices.Commands.psd1
- module/PowerShellEditorServices/Commands/Private/BuiltInCommands.ps1
- module/PowerShellEditorServices/Commands/Public/CmdletInterface.ps1
- module/PowerShellEditorServices/Commands/Public/ConvertFrom-ScriptExtent.ps1
- module/PowerShellEditorServices/Commands/Public/ConvertTo-ScriptExtent.ps1
- module/PowerShellEditorServices/Commands/Public/Import-EditorCommand.ps1
- module/PowerShellEditorServices/Commands/Public/Set-ScriptExtent.ps1
- src/PowerShellEditorServices/Extensions/EditorFileRanges.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2495
> Fix PSES Commands module

- CHANGELOG.md
- src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2516
We weren't specifically telling PSSA to only run the one rule so other diagnostics were coming back. I would guess that this fix would also have some perf impact as well which is nice.
an example bad function that works with this change:
```pwsh
function CanSendGetCommentHelpRequest {
param(
$myParam,
$myOtherParam,
$yetAnotherParam
)
gci
}
```
The test change failed before the code change and passed after the code change.
> Fix CommentHelp for when a function has other problems with it

- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
ExecuteCommandAsync was deadlocking itself when we were doing untitled file debugging.
Using a counter, this customises the lock behaviour to stop this issue.
> Fix untitled debugging by making session-state lock task-reentrant

- src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeActionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeLensHandlers.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DefinitionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DocumentHighlightHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DocumentSymbolHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/FoldingRangeHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/FormattingHandlers.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/HoverHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/ReferencesHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/SignatureHelpHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/TextDocumentHandler.cs
- src/PowerShellEditorServices/Utility/LspUtils.cs
Trying to get the vim extension working, I noticed that the `filetype` for PowerShell files was `ps1` instead of `powershell`.
This adds `ps1` and a few others to our document selector.
I really should get the vim extension using `powershell` but it's harder than it sounds because any vim plugin can change this.
> Switch to better document selecting

- .devcontainer/devcontainer.json
- .vscode/extensions.json
C# extension has changed its name from "ms-vscode.csharp" to "ms-dotnettools.csharp", this means all extensions depending on it needs to be updated and i.e. all repositories with extension.json containing
```json
"recommendations": [
"ms-vscode.csharp"
]
```
or you get errors like
> ms-vscode.csharp to ms-dotnettools.csharp

- src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
The vim extension ran into this issue where because it didn't create the log dir, PSES wouldn't startup properly.
This makes PSES more resilient.
> Ensure log directory is created

- src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
Switch over to using `Assembly.LoadFile()` instead of `Assembly.LoadFrom()` to load dependency assemblies in WinPS to avoid clobbering module dependencies.
Fixes https://github.com/PowerShell/vscode-powershell/issues/2397
Fixes https://github.com/PowerShell/vscode-powershell/issues/2545
> Use Assembly.LoadFile in WinPS

- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2534.
The PowerShell thread writing errors was never awaited and was being starved it seems. We now wait for the error writing to finish
> Ensure that errors are written to the console when debugging

- src/PowerShellEditorServices/Services/CodeLens/PesterCodeLensProvider.cs
- src/PowerShellEditorServices/Services/Symbols/SymbolsService.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeLensHandlers.cs
- src/PowerShellEditorServices/Services/Workspace/LanguageServerSettings.cs
- test/PowerShellEditorServices.Test.E2E/LSPTestsFixures.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
- test/PowerShellEditorServices.Test/Language/LanguageServiceTests.cs
This shows the lense on every Describe \ Context and It. 
To test this you need Pester v5 ( branch `filter-by-lines` or once merged `v5.0`), you will also need the updated extension from vscode-powershell repo (branch same as here). Once your VSCode is started with the new version (after running the extension by F5), open a .Tests.ps1 file and load Pester v5.
```powershell
Get-Module Pester | Remove-Module ; Import-Module Projects/Pester/Pester.psd1
```
~WIP:~
~Once merged this will show the menu for all versions of Pester are we able to somehow figure out the version of Pester beforehand and only use the new approach when Pester v5 is loaded?~
~If not, should we add opt-in setting? Pester v5 is still far from ready, but I want to use this with beta which will be soon available 🙂~
Ready: …
> Run single test in Pester v5

- src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
This means that variables, paths, etc no longer use the pipeline thread to "resolve".
> Only resolve completion items from commands

- src/PowerShellEditorServices/Services/Symbols/SymbolsService.cs
Now we are certain that `GetCommandInfoAsync` will only run when we have a Function. I included Unknown as well just in case, but I could take that out.
We should no longer see these in logs:
```
2020-03-13 12:37:12.884 -07:00 [ERR] Execution of the following command(s) completed with errors:
Microsoft.PowerShell.Core\Get-Command -Name -ErrorAction Ignore
```
^ *Explanation*: `-Name` is being passed in to `Get-Command`.
> Optimize when we run GetCommandInfoAsync

- src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/ReferencesHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/TextDocumentHandler.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
fixes https://github.com/PowerShell/vscode-powershell/issues/2572
We need to not run script diagnostics if the file we get isn't a PowerShell file in VS Code but is a PowerShell file on the file system.
> Only run diagnostics on PowerShell files

- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Server/PsesDebugServer.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeActionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DefinitionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DocumentHighlightHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DocumentSymbolHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/FoldingRangeHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/FormattingHandlers.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/HoverHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/ReferencesHandler.cs
- src/PowerShellEditorServices/Services/Workspace/Handlers/WorkspaceSymbolsHandler.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
- test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj
Fixes https://github.com/PowerShell/vscode-powershell/issues/2556
possibly fixes https://github.com/PowerShell/vscode-powershell/issues/2518
possibly fixes https://github.com/PowerShell/vscode-powershell/issues/2522
Probably should wait til a stable release of Omnisharp but they've fixed cancellation and this does feel faster in @adamdriscoll's ps1 talked about here: https://github.com/PowerShell/vscode-powershell/issues/2556#issuecomment-599230479
when testing in that ps1 for a bit I received this number of requests that wanted to be cancelled:
```
Count Name
----- ----
3  completionItem/resolve
7  textDocument/codeAction
1  textDocument/codeLens
3  textDocument/completion
1  textDocument/documentSymbol
14  textDocument/foldingRange
```
This PR could cancel 14 + 7 + 3 = 24 out of 29 …
> Add cancellation for `textDocument/completion`, `textDocument/codeAction`, `textDocument/folding`

- src/PowerShellEditorServices/Services/PowerShellContext/Utilities/CommandHelpers.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
Fixes #1242 
Fixes https://github.com/PowerShell/vscode-powershell/issues/2584
This method needed a good refactor... The main change here is:
```
.AddParameter("Name", commandInfo.Name)
```
instead of
```
.AddArgument(commandInfo)
```
because `commandInfo.ToString()` gives you duplicate Prefixes... I'll link that PowerShell/PowerShell issue here when the original filer opens it.
> Refactor GetCommandSynopsisAsync method make sure cmdlets with module prefixes work

- src/PowerShellEditorServices/Services/PowerShellContext/Utilities/CommandHelpers.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/HoverHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/SignatureHelpHandler.cs
* SignatureHelp request is now cancellable - I saw this request a bunch in a user's log
* SignatureHelp request cleaned up a bit
* Cache `CmdletInfo`'s and synopsis' of `CmdletInfo`s.
* Renamed `NounExclusionList` to `s_nounExclusionList`
> Signaturehelp cancellation and some caching

- .vsts-ci/templates/ci-general.yml
From gist: https://gist.github.com/TylerLeonhardt/aeda3dbf5b1854736fe8e1ada2e143dc
> Use PowerShell Daily in CI

- module/PowerShellEditorServices/PowerShellEditorServices.psd1
- src/PowerShellEditorServices.Hosting/Commands/InvokeReadLineConstructorCommand.cs
- src/PowerShellEditorServices.Hosting/Commands/InvokeReadLineForEditorServicesCommand.cs
- src/PowerShellEditorServices/Server/PsesDebugServer.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/PSReadLinePromptContext.cs
fixes https://github.com/PowerShell/vscode-powershell/issues/2623
This _should_ enable the ability to _start up_ with ConstrainedLanguage mode (though I didn't remove the check because I wasn't sure if I could set it on non-Windows). There are features that won't work though - expand alias, remoting, Command explorer, etc.
> Move PSReadLine logic to cmdlets

- module/PowerShellEditorServices/PowerShellEditorServices.psd1
- src/PowerShellEditorServices.Hosting/Commands/InvokeReadLineConstructorCommand.cs
- src/PowerShellEditorServices.Hosting/Commands/InvokeReadLineForEditorServicesCommand.cs
- src/PowerShellEditorServices/Server/PsesDebugServer.cs
- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/PSReadLinePromptContext.cs
- src/PowerShellEditorServices/Utility/PSCommandExtensions.cs
fixes https://github.com/PowerShell/vscode-powershell/issues/2626
This no longer exposes the cmdlets and instead creates a `CmdletInfo` object with the implementing type.
Unfortunately, we have to work around 2 PowerShell issues:
https://github.com/PowerShell/PowerShell/issues/12295
https://github.com/PowerShell/PowerShell/issues/12297
> No warning about module being imported

- CHANGELOG.md
- PowerShellEditorServices.Common.props
- 🐛📟 [PowerShellEditorServices #1258](https://github.com/PowerShell/PowerShellEditorServices/pull/1258) -
No more warning about PowerShellEditorServices module being imported with unapproved verb.
> Rev version to v2.1.0-preview.6 and update CHANGELOG

- src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Services/Analysis/PssaCmdletAnalysisEngine.cs
fixes https://github.com/PowerShell/vscode-powershell/issues/2543
With ScriptAnalysis turned off...
```
"powershell.scriptAnalysis.enable": false,
```
this disables PSScriptAnalyzer capabilities in the extension including:
* "Problems" in your open editor file
* Formatting
Since that was off, formatting wasn't working for users (and would throw a weird null ref due to returning `null` instead of `Task.FromResult(null)`).
With that said, I don't see _why_ this needs to be the case. You should be able to run the formatter and have "Problems" turned off. This PR pushes the ScriptAnalysis enabled test up a layer while allowing the Formatting path to trigger the creation of the `AnalysisEngine`.
> Allow formatting when ScriptAnalysis is off

- PowerShellEditorServices.build.ps1
- modules.json
Fixes https://github.com/PowerShell/vscode-powershell/issues/2637
(well really mitigates...)
Now that we have a stable version of PSReadLine that works with the extension, we should only ship stables in the Stable extension.
This allows for previews in Preview builds and stables in Stable builds.
cc @daxian-dbw
> AllowPrerelease when building Preview build

- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/EditorServicesPSHostUserInterface.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/TerminalPSHostUserInterface.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2637
Fixes https://github.com/PowerShell/vscode-powershell/issues/2640
A user can be using PowerShell 5.1 or greater on Windows Server 2012 R2.
We can leverage the internal host to get the value already computed by ConsoleHost.
I haven't tested this... I'd need to break out a 2012 R2 VM 😢
> Leverage internal HostUI for VT100 check

- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/BreakpointApiUtils.cs
Fix https://github.com/PowerShell/vscode-powershell/issues/2654
When this works you can do some fancy stuff like timing loops:
This uses messages:
```powershell
Init loop var: $($global:prevTS = Get-Date; $prevTS)
Loop time: $($currTS = Get-Date; ($currTS - $prevTS).TotalMilliseconds; $global:prevTS = $currTS) ms
```
> Fix interpolation in Log points, switch to double quotes

- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/GetCommandHandler.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
Refactor GetCommandHandler to not use dynamic.
This includes a test change that was needed because a PowerShell type didn't serialize correctly.
cc @corbob
> Refactor GetCommandHandler to not use dynamic

- PowerShellEditorServices.build.ps1
- module/PowerShellEditorServices/Commands/Public/Clear-Host.ps1
- src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
- src/PowerShellEditorServices.Hosting/Configuration/EditorServicesConfig.cs
- src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
- src/PowerShellEditorServices.Hosting/Internal/EditorServicesRunner.cs
- src/PowerShellEditorServices/Hosting/HostStartupInfo.cs
- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/Capabilities/DscBreakpointCapability.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/ExecutionOptions.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/PSReadLinePromptContext.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/PowerShellVersionDetails.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/RunspaceDetails.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/SessionDetails.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
- test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj
- test/PowerShellEditorServices.Test.E2E/TestsFixture.cs
- test/PowerShellEditorServices.Test/PowerShellContextFactory.cs
With this PR, we have some support of `ConstrainedLanguage` mode. The `LanguageMode` is inherited from the initial runspace that starts `Start-EditorServices`
Windows PowerShell is started without PSRL and it is working... but there's more work that will need to be done here. Here are notes I've made from this:
* Fixed by only calling `$psEditor.....Clear()` on FullLanguage
* ISE has same problem... aka by-design
* PSSA is being loaded with ConstrainedLanguage mode in Windows PowerShell to this proves my theory.
* NOTE: idk why but PSReadLine doesn't show up in `Get-Module -list` in Windows PowerShell
* Since we won't offer PSRL for ConstrainedLanguage mode initially, this isn't a problem atm
* For now, I'm offering the legacy readline for ConstrainedLanguage mode.
* The file is run, but …
> Support ConstrainedLanguage mode

- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/EditorServicesPSHostUserInterface.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/TerminalPSHostUserInterface.cs
If you look at the first commit, you'll see that it allows us to inherit the setting and getting of the Progress colors from the internal host.
The second+ commits are purely cosmetic since I was touching the file.
> Allow progress colors to be settable and gettable from the internal host

- src/PowerShellEditorServices/Services/PowerShellContext/Utilities/CommandHelpers.cs
Before this PSES drops an exception in the log. It's "handled" so the extension doesn't break down... but we don't want the stacktrace in the log.
The behavior is still the same, this just prevents when `Get-Command` returns nothing.
> Fix when no CommandInfo comes back

- src/PowerShellEditorServices/Services/Symbols/Vistors/FindReferencesVisitor.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
- test/PowerShellEditorServices.Test/Console/ChoicePromptHandlerTests.cs
- test/PowerShellEditorServices.Test/Services/Symbols/AstOperationsTests.cs
fixes https://github.com/PowerShell/vscode-powershell/issues/305
We were originally computing the location by doing:
`ast.Extent.Text.IndexOf(ast.Name)`
but this is horrible because of cases like `function func { }` which break it... and not to mention it doesn't include the space before the definition... aka indentation.
Since the AST doesn't tell us where the actual name of the function starts, we need to compute it.
> Fix document highlight column

- modules.json
- src/PowerShellEditorServices/Services/Workspace/LanguageServerSettings.cs
See the `vscode-powershell` PR for details: https://github.com/PowerShell/vscode-powershell/pull/2674
> PSSA 1.19.0 settings

- src/PowerShellEditorServices/Extensions/Api/EditorContextService.cs
- src/PowerShellEditorServices/Extensions/Api/EditorUIService.cs
- src/PowerShellEditorServices/Extensions/Api/LanguageServerService.cs
- src/PowerShellEditorServices/Extensions/EditorFileRanges.cs
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
- src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Services/CodeLens/ReferencesCodeLensProvider.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/BreakpointHandlers.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/EditorOperationsService.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/GetCommentHelpHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/PromptHandlers.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeActionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DefinitionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DocumentHighlightHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/FormattingHandlers.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/HoverHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/ReferencesHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/SignatureHelpHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/TextDocumentHandler.cs
- src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
- test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj
- test/PowerShellEditorServices.Test/Services/Symbols/AstOperationsTests.cs
main changes:
`Uri` -> `DocumentUri`
`long`s -> `int`s
and requests now have a `.Returning<resultType>(CancellationToken)` and `.ReturningNull(CancellationToken)` instead of doing like `SendRequest<Params,Result>(....)`
~Just waiting on https://github.com/OmniSharp/csharp-language-server-protocol/pull/237~ done
> move to omnisharp 0.17.0

- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
I'm hoping this resolves the issue in #1221 with F5.
> Use API on ScriptBlock to generate PSCommand

- .vscode/snippets.code-snippets
- CHANGELOG.md
- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
I wasn't protecting against null, unfortunately...
This also adds useful snippets for our repo.
> Fix startup on empty workspace

- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/GetVersionHandler.cs
Fixes #1278 
We can't assume PackageManagement update will work... so just say go run it yourself.
> Don't update PackageManagement on ConstrainedLanguage mode

- src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
fixes https://github.com/PowerShell/vscode-powershell/issues/2706
The comparison operators (-eq, -not, -gt, etc) unfortunately fall into the `CompletionType` `ParameterName` (thanks PowerShell) but they don't have a type associated to them like actual parameters so nothing was being stored.
> Show tooltip for comparison operators

- src/PowerShellEditorServices/Services/CodeLens/PesterCodeLensProvider.cs
- src/PowerShellEditorServices/Services/CodeLens/ReferencesCodeLensProvider.cs
- src/PowerShellEditorServices/Services/Symbols/SymbolReference.cs
- src/PowerShellEditorServices/Services/Symbols/Vistors/FindReferencesVisitor.cs
- src/PowerShellEditorServices/Services/Symbols/Vistors/FindSymbolVisitor.cs
- src/PowerShellEditorServices/Services/Symbols/Vistors/FindSymbolsVisitor.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DefinitionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DocumentSymbolHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/ReferencesHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/ScriptFile.cs
- src/PowerShellEditorServices/Services/Workspace/Handlers/WorkspaceSymbolsHandler.cs
- src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs
- src/PowerShellEditorServices/Utility/PathUtils.cs
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
- test/PowerShellEditorServices.Test/Session/WorkspaceTests.cs
This needs a change in vscode-powershell as well but now we have `DocumentUri` types everywhere and don't need a lot of code :)
cc @david-driscoll
> Depend on DocumentUri for handing vscode Uri's

- src/PowerShellEditorServices/Services/CodeLens/ReferencesCodeLensProvider.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DefinitionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DocumentSymbolHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/ReferencesHandler.cs
- src/PowerShellEditorServices/Services/Workspace/Handlers/WorkspaceSymbolsHandler.cs
I forgot that these are `Uri`'s - for example: `Untitled:Untitled-1`
I tested this on Windows and macOS.
> Use From instead of FromFileSystem

- PowerShellEditorServices.build.ps1
- modules.json
- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/EditorServicesPSHostUserInterface.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/PSReadLinePromptContext.cs
This is pending a 2.0.2 release of PSRL that has [a fix for CLM](https://github.com/PowerShell/PSReadLine/pull/1527).
On Windows PowerShell, for some reason... when PSReadLine is not a trusted module, `gmo -list` does not show it. As a workaround, we attempt to load PSRL from our module path.
This ensures PSRL will be loaded when the PSRL feature is used.
> Additional changes to allow PSReadLine to work in CLM

- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/GetVersionHandler.cs
To download the PackageManagement module requires TLS 1.2. Many users will get an error. 
fixes #1314 
fixes https://github.com/PowerShell/vscode-powershell/issues/2763
> TLS 1.2 Support When Installing PackageManagement Module

- src/PowerShellEditorServices/Services/TextDocument/Handlers/HoverHandler.cs
Previously we returned a new **Hover** instance without initializing the `Contents` or `Range` members. At least in VS Code, this will result in the LSP client attempting to access `null` properties. As we're not returning any **Hover** data, the correct response is to simply return `null`. See the [Hover Request (Response)](https://microsoft.github.io/language-server-protocol/specification#textDocument_hover) section in the LSP spec.
To reproduce the issue in VS Code:
1. Ensure the PowerShell extension is installed and open a PowerShell script.
2. Switch the _Output_ console to _Log (Extension Host)_ or _Log (Window)_ (it seems to differ sometimes?).
3. Hover over some text with no expected hover content (e.g. a word in a string).
4. An exception is thrown on reading the uninitialized …
> Return null when Hover request is cancelled or no symbol details

- PowerShellEditorServices.build.ps1
.NET install script was failing on my machine because of whitespace in the path.
I got rid of the `iex` and replaced it with some splatting.
~~Also moved the three downloads into jobs in an attempt to parallelise them a bit, although not sure what kind of speedup there is.~~ Not reliable, back to serial
Tested this on Windows and macOS, but worth another test.
> Fix  .NET installation

- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
- src/PowerShellEditorServices/Services/Workspace/Handlers/ConfigurationHandler.cs
- src/PowerShellEditorServices/Services/Workspace/LanguageServerSettings.cs
Changes are required as part of this PR: https://github.com/PowerShell/vscode-powershell/pull/2796
> Add cwd property to settings

- src/PowerShellEditorServices/Services/CodeLens/ReferencesCodeLensProvider.cs
- src/PowerShellEditorServices/Services/TextDocument/ScriptFile.cs
- src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs
I wanted to make changes to PSES as small as possible because Notebook UI is a vscode feature, but some things had to be done.
1. For CodeLens inside of a Notebook Cell, we need to ignore any results from the actual backing file because CodeLens looks at the file system. That would be counting duplicates.
2. Had to add vscode-notebook-cell to our list of supporting schemes
3. Made the Untitled path check more robust.
> Needed changes for Notebook UI Support

- modules.json
- src/PowerShellEditorServices/Services/Workspace/LanguageServerSettings.cs
This is related to https://github.com/PowerShell/vscode-powershell/pull/2831
> Expose new rule PSAvoidUsingDoubleQuotesForConstantString added in PSSA 1.19.1

- src/PowerShellEditorServices/Services/TextDocument/Handlers/PsesSemanticTokensHandler.cs
- test/PowerShellEditorServices.Test/Language/SemanticTokenTest.cs
Property seems to be the better pick here... I imagine less languages use "member" and just use "property" instead.
Goes with https://github.com/PowerShell/vscode-powershell/pull/2844
before and after
before and after
before and after
ISE:
> Move Member to Property

- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/GetVersionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/FoldingRangeHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/PsesSemanticTokensHandler.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
PsesSemanticTokensHandler was not compatible with the Omnisharp.Extensions.LanguageServer update to 0.17.3 following the new LSP spect (v3.18). This PR fixes those issues.
Also see: https://github.com/PowerShell/vscode-powershell/pull/2861
> Updated Semantic Handler to work with new LSP 

- src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs
- test/PowerShellEditorServices.Test/Session/WorkspaceTests.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2810
So item.Path always contains forward slashes... this means that the paths returned on Windows will be mixed:
C:\\Foo/Bar/baz.ps1
This result is used in counting references in CodeLens and `C:\\Foo/Bar/baz.ps1` was being treated differently from `C:\\Foo\\Bar\\baz.ps1` because they're just strings... https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices/Services/Symbols/SymbolsService.cs#L200 
this fixes the issue by fixing the directory separator... 
... though in the future, it might be worth using FileInfo or something else in that ordered dictionary...
> Fix references on Windows due to slashes

- src/PowerShellEditorServices.Hosting/Internal/EditorServicesRunner.cs
- src/PowerShellEditorServices.Hosting/Internal/PsesLoadContext.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/2719.
We now await the server startup task, so that errors propagate properly to the caller.
This also fixes the underlying issue, where Omnisharp requires a higher version of the System.Collections.Immutable dependency than PowerShell provides.
> Fix startup assembly version loading issue in PS6

- .vsts-ci/templates/ci-general.yml
> [Ignore] Use daily build again

- src/PowerShellEditorServices/Services/Symbols/Vistors/AstOperations.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
- test/PowerShellEditorServices.Test.Shared/Completion/CompleteNamespace.cs
- test/PowerShellEditorServices.Test.Shared/Completion/CompleteTypeName.cs
- test/PowerShellEditorServices.Test.Shared/Completion/CompletionExamples.psm1
- test/PowerShellEditorServices.Test/Language/LanguageServiceTests.cs
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
Resolves https://github.com/PowerShell/vscode-powershell/issues/2898
Adds tool tips for type completions, tests for completion are included.
> Type completion with tooltips 

- src/PowerShellEditorServices/Services/PowerShellContext/Utilities/CommandHelpers.cs
If the user has overridden the Get-Help -Online parameter to always be true, then the ShowHelpHandler will always launch a new browser window to the cmdlet help.
Instead, we want it to return the full cmdlet text as intended.
fixes #1393 
fixes https://github.com/PowerShell/vscode-powershell/issues/3071
> fix #1393: Always use local help to return Full help

- src/PowerShellEditorServices/Logging/PsesTelemetryEvent.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/GetCommandHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/ITemplateHandlers.cs
- src/PowerShellEditorServices/Services/Workspace/Handlers/ConfigurationHandler.cs
- src/PowerShellEditorServices/Services/Workspace/LanguageServerSettings.cs
- test/PowerShellEditorServices.Test.E2E/LSPTestsFixures.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
needs https://github.com/PowerShell/vscode-powershell/pull/3053 for the full flow.
The LSP has a message called [telemetry event](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#telemetry_event). The omnisharp lib gives us a mechanism for sending this so this PR hooks that up.
It's important to note that this doesn't make any requests besides sending a message to the client (aka vscode) to do the work of sending a telemetry event off the box. This way PSES doesn't have to depend on any AppInsights dll or something like that.
The event that this adds is an event called `NonDefaultPsesFeatureConfiguration` that has the body of settings that have been switched off/on from the default value. For example, if the user turns off the PackageManagement …
> Hook up Telemetry LSP event and add telemetry event when users opt-out/in to features

- CHANGELOG.md
- PowerShellEditorServices.Common.props
- module/PowerShellEditorServices/PowerShellEditorServices.psd1
Updates the changelog and bumps the version for one more preview. Part of https://github.com/PowerShell/vscode-powershell/issues/3178
> Update CHANGELOG for v2.3.0-preview.3

- .markdownlint.json
- README.md
I was just doing this because I needed something to kick off the CI, but might as well merge it too.
> Fix some markdownlint errors in README

- src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
Fixes https://github.com/PowerShell/PowerShellEditorServices/issues/1176 so IntelliSense gets triggered automatically when writing variables.
> Add '$' as trigger character for completion

- module/PowerShellEditorServices/Commands/Public/CmdletInterface.ps1
Fixes PowerShell/vscode-powershell#3180
This feels janky, but short of moving the context gathering later and doing a bunch of work we can't complete because of Temp session I'm not sure of a better way.
I've also updated the help to reference the correct filename.
> Fix New-EditorFile failing when no Editor window open

- src/PowerShellEditorServices/Extensions/Api/EditorExtensionServiceProvider.cs
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ThreadsHandler.cs
- test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
Part of https://github.com/PowerShell/vscode-powershell/issues/3294, we are testing the latest beta of OmniSharp for the preview extension (with a fixed debugger).
> Bump OmniSharp package to `0.19.2-beta0001`

- .vsts-ci/azure-pipelines-release.yml
- CHANGELOG.md
- PowerShellEditorServices.Common.props
- module/PowerShellEditorServices/PowerShellEditorServices.psd1
Updates changelog and version, and fixes the release pipeline's trigger 🤷
> Release `v2.4.1-preview.1`

- src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
- src/PowerShellEditorServices.Hosting/Configuration/HostLogger.cs
- src/PowerShellEditorServices/Services/Analysis/PssaCmdletAnalysisEngine.cs
Adds small improvements to PSES that are made in https://github.com/PowerShell/PowerShellEditorServices/pull/1459, but aren't related or really required for the main work there. The intent is to be able to rebase that work onto this.
> Make code more explicit

- .dependabot/config.yml
- .github/dependabot.yml
Manually create GitHub-Native Dependabot configuration. Resolves #1462. I had to do this manually because the Dependabot website continued to fail to create the PR, and GitHub support has been unable to resolve it.
The configuration is the same as used in the extension's repository: https://github.com/PowerShell/vscode-powershell/pull/3310
> Upgrade to GitHub-Native Dependabot

- src/PowerShellEditorServices.Hosting/BuildInfo.cs
- src/PowerShellEditorServices.Hosting/Configuration/HostLogger.cs
- src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
- src/PowerShellEditorServices.Hosting/Internal/EditorServicesRunner.cs
- src/PowerShellEditorServices/Hosting/EditorServicesLoading.cs
- src/PowerShellEditorServices/Hosting/EditorServicesServerFactory.cs
- src/PowerShellEditorServices/Hosting/HostStartupInfo.cs
- src/PowerShellEditorServices/Logging/LoggerExtensions.cs
- src/PowerShellEditorServices/Logging/PsesTelemetryEvent.cs
- src/PowerShellEditorServices/Server/PsesDebugServer.cs
- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
- src/PowerShellEditorServices/Server/PsesServiceCollectionExtensions.cs
- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
- src/PowerShellEditorServices/Services/Workspace/Handlers/ConfigurationHandler.cs
Just writing up what I've learned and odd stuff I've spotted while reading through the code. Also added at least a bit more logging to help debug https://github.com/PowerShell/vscode-powershell/issues/3306.
> Add more logging and internal documentation

- src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
Fixes https://github.com/PowerShell/vscode-powershell/issues/715 by not getting command documentation unless the module has already been imported.
This should greatly help with the command IntelliSense experience
> Fix unintentional module import

- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
Replaces #1485, #1486, #1487, and #1489.
> Bump OmniSharp to `v0.19.2`

- PowerShellEditorServices.build.ps1
- src/PowerShellEditorServices.Hosting/BuildInfo.cs
- src/PowerShellEditorServices.Hosting/PowerShellEditorServices.Hosting.csproj
This fixes https://github.com/PowerShell/vscode-powershell/issues/3395
> Work around `dotnet publish` bug

- PowerShellEditorServices.build.ps1
- src/PowerShellEditorServices.Hosting/BuildInfo.cs
- src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
- src/PowerShellEditorServices/Extensions/EditorObject.cs
- src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeActionHandler.cs
- src/PowerShellEditorServices/Services/Workspace/Handlers/ConfigurationHandler.cs
- src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs
Fixes #1495, #1498, and #1476.
> Prevent some exceptions

- .vsts-ci/templates/release-general.yml
- CHANGELOG.md
- PowerShellEditorServices.Common.props
- module/PowerShellEditorServices/PowerShellEditorServices.psd1
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
We only run builds on ADO with the intent to release, therefore we need to just
always sign them. Otherwise the compliance scripts' default behavior is to sign
when the build is manually triggered, which is not our workflow. We push a
release branch and expect that automatic build to result in signing.
> Bump version to `v2.4.5`

- .editorconfig
Added 
csharp_space_before_open_square_brackets = true
csharp_space_after_keywords_in_control_flow_statements = false
to enforce the existing convention and prevent unintentional changes.
> Update `.editorconfig` to prevent unintentional whitespace changes

- module/PowerShellEditorServices/InvokePesterStub.ps1
I used `git filter-repo` to export the history and adjust the path of this script, so that I could then use `git merge --allow-unrelated-history` to merge said script in with its development history intact.
> Import `InvokePesterStub.ps1` from `vscode-powershell` (with history)

- PowerShellEditorServices.Common.props
- PowerShellEditorServices.build.ps1
- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/PSReadLinePromptContext.cs
- test/PowerShellEditorServices.Test/PowerShellContextFactory.cs
- test/PowerShellEditorServices.Test/Session/PowerShellContextTests.cs
This definitely would resolve #1493, but @rjmholt I have a hunch there's a better way to load a bundled dependency. That is: I think we were using this inline script only so we could support loading any arbitrary version of PSReadLine, and since we're deprecating that behavior, there's _probably_ a way to just straight up load it into the session without executing some script like this.
> Load only bundled `PSReadLine`

- PowerShellEditorServices.Common.props
- PowerShellEditorServices.build.ps1
- src/PowerShellEditorServices.Hosting/Internal/EditorServicesRunner.cs
- src/PowerShellEditorServices/Hosting/HostStartupInfo.cs
- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/PSReadLinePromptContext.cs
- test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj
- test/PowerShellEditorServices.Test.E2E/xunit.runner.json
- test/PowerShellEditorServices.Test/App.config
- test/PowerShellEditorServices.Test/Language/SemanticTokenTest.cs
- test/PowerShellEditorServices.Test/PowerShellContextFactory.cs
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
- test/PowerShellEditorServices.Test/Session/PowerShellContextTests.cs
- test/PowerShellEditorServices.Test/xunit.runner.json
Finishing #1514. Also replaces #1516.
> Run new PSReadLine test on Windows

- .editorconfig
- src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
- src/PowerShellEditorServices.Hosting/Configuration/EditorServicesConfig.cs
- src/PowerShellEditorServices.Hosting/Internal/EditorServicesRunner.cs
- src/PowerShellEditorServices/Hosting/HostStartupInfo.cs
- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
- test/PowerShellEditorServices.Test/PowerShellContextFactory.cs
Instead of passing values for `LanguageMode` and `ExecutionPolicy` as
fields that are set on an `InitialSessionState` object that's eventually
created, we now pass a fully initialized `InitialSessionState` object
from the start.
We also rename `SetExecutionPolicy` to `RestoreExecutionPolicy` to
reflect what it actually does: restores the user's policy after we
overrode it with `Bypass` while initializing the integrated console's
runspace. We override it because we need to be able to load `PSReadLine`
etc. without policy issues.
Finally, we fix the EditorConfig setting to enforce spaces after
control-flow keywords (such as `if`) because, while our codebase is
inconsistent, it is our preferred style going forward.
This replaces #1523.
> Initialize runspaces with `InitialSessionState` object

- src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
Allows us to work out why an assembly is being loaded in debug builds
> Add stack trace to resolve event handler on debug

- .github/CODEOWNERS
- .vsts-ci/azure-pipelines-ci.yml
- .vsts-ci/azure-pipelines-release.yml
- .vsts-ci/misc-analysis.yml
- .vsts-ci/templates/ci-general.yml
- .vsts-ci/templates/publish-general.yml
- .vsts-ci/templates/release-general.yml
- tools/azurePipelinesBuild.ps1
Has to be merged in tandem with changes to vscode-powershell.
> Update release and CI pipelines

- .editorconfig
- src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/BreakpointDetails.cs
- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
- test/PowerShellEditorServices.Test.Shared/Debugging/VariableTest.ps1
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
- test/PowerShellEditorServices.Test/Session/WorkspaceTests.cs
This resolves #1442, and sets me up to add a test around debugging code that uses an object from `System.Windows.Forms`.
This PR also:
- Fixes some NullReferenceExceptions exposed by the restored tests
- Removes some broken script path logic
- Replaces some older hard-coded empty array logic with the newer .NET Standard API
- Fixes a deadlock that occurs when debugging is aborted
> Fix tests in `Debugging/DebugServiceTests.cs` and simplify faulty script path logic

- PowerShellEditorServices.Common.props
Our build started failing this morning because .NET SDK 6 moved from Preview 6 to Preview 7 and its generated code now throws an error with language version 9.0, but is allowed with 10.0. Issue is documented upstream in https://github.com/dotnet/sdk/issues/19702
> Update C# language version to 10.0 to fix bug with .NET SDK 6 Preview 7

- src/PowerShellEditorServices/Server/PsesDebugServer.cs
- src/PowerShellEditorServices/Services/DebugAdapter/BreakpointService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/DebugEventHandlerService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/BreakpointDetails.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/LaunchAndAttachHandler.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ThreadsHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Console/ConsoleReadLine.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/ExpandAliasHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/GetCommandHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/PSHostProcessAndRunspaceHandlers.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Handlers/ShowHelpHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/EditorServicesPSHostUserInterface.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/PSReadLinePromptContext.cs
This hasn't solved the problem where the PowerShell debugger and the VS Code debugger somehow disconnect from each other when `System.Windows.Forms` is added to the PowerShell session, but it does improve the situation somewhat. The debugger can be stopped now (though it cannot be restarted yet).
> Make `ExecuteCommandAsync` cancellable 

- PowerShellEditorServices.Common.props
This also reverts us back to language version 9.0.
This reverts commit e29979c369efdcb645a681403ae5d380076a85c8.
Fixes #1544.
> Explicitly disable implicit namespace imports

- PowerShellEditorServices.build.ps1
- src/PowerShellEditorServices/Services/Analysis/PssaCmdletAnalysisEngine.cs
- test/PowerShellEditorServices.Test/PowerShellContextFactory.cs
We erroneously changed our code to use `CreateDefault` instead of `CreateDefault2`. There existed old but defunct code for testing the use of `CreateDefault` instead, but it was never intentionally moved into production. The latter function loads only `Microsoft.PowerShell.Core`, leaving us to load the exact modules we intend to load ourselves, which is the safer behavior (and the previous behavior).
> Fix creation of `InitialSessionState` to use `CreateDefault2()`

- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/DisconnectHandler.cs
- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
- src/PowerShellEditorServices/Services/PowerShellContext/Session/PSReadLinePromptContext.cs
- src/PowerShellEditorServices/Services/Symbols/Vistors/AstOperations.cs
These needed to be explicitly `None` to indicate that they should not be cancelled (for various reasons). The actual bug fix was the removal of `shell.Stop()`. Fixes https://github.com/PowerShell/vscode-powershell/issues/3513.
> Fix debugger regression where console needed input to start/continue

- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
This fixes https://github.com/PowerShell/vscode-powershell/issues/3537.
> Fix bug with `ExecuteScriptWithArgsAsync` when `script` is a command

- src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/TerminalPSHostRawUserInterface.cs
Without redirecting this call to `internalRawUI` any formatting with ANSI escapes will likely be truncated in the wrong spot.
Fixes #840
> Implement `LengthInBufferCells` to fix ANSI formatting

- .editorconfig
- src/PowerShellEditorServices.Hosting/Internal/EditorServicesRunner.cs
- src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
- test/PowerShellEditorServices.Test.E2E/DebugAdapterProtocolMessageTests.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
This is the edge case where the debug server is running because it was started by PowerShell (and not by an LSP event), and we're no longer in the debugger within PowerShell, so since we own the state we need to stop the debug server too.
Along with https://github.com/PowerShell/vscode-powershell/pull/3542, this resolves one of the main issues brought up in https://github.com/PowerShell/vscode-powershell/issues/3522.
>  Send `stopDebugger` notification when appropriate

- src/PowerShellEditorServices/Services/PowerShell/Host/EditorServicesConsolePSHostRawUserInterface.cs
Fixes #1603.
These changes were accidentally forgotten in the rewrite and needed to be added back.
@SeeminglyScience Do you know how we could add a regression test for this?
> Add `LengthInBufferCells` back to `EditorServicesConsolePSHostRawUserInterface`

- src/PowerShellEditorServices/Services/PowerShell/Utility/PowerShellExtensions.cs
- src/PowerShellEditorServices/Utility/PSCommandExtensions.cs
Fixes issues identified in: https://github.com/PowerShell/vscode-powershell/issues/3650
> Fix profile loading and `$PROFILE` variable

- PowerShellEditorServices.build.ps1
- global.json
But also install all the necessary runtimes.
Replaces #1616.
> Install a single `dotnet` SDK

- .vsts-ci/azure-pipelines-ci.yml
The image has been deprecated and will soon be removed from Azure DevOps. Furthermore Microsoft's support for Windows Server 2016 itself ends in January 2022 (less than two months away).
> Remove Windows Server 2016 from CI

- PowerShellEditorServices.build.ps1
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
The previous fix assumed PowerShell was always running in an emulated mode (i.e. running PowerShell (x64) but on an Apple M1). Now that PowerShell 7.2 has a native build for Apple M1 (arm64) the check needs to handle both cases.
We must also skip asking `dotnet-install` to install the 3.1 or 5.0 .NET Runtimes on an Apple M1 because they don't exist, but their installer tries to get them anyway. This was a non-breaking bug previously where the macOS x64 runtimes would be installed, but not used.
> Fix build for Apple M1 when running PowerShell 7.2 (arm64)

- PowerShellEditorServices.Common.props
- src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/StackFrameDetails.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/VariableContainerDetails.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/VariableDetails.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/DebugEvaluateHandler.cs
This is take two on #1620, with it rebased and commits somewhat split apart, as well as additional fixes.
Fixes https://github.com/PowerShell/vscode-powershell/issues/3667
Fixes https://github.com/PowerShell/vscode-powershell/issues/3673
> Improve debugger's variable population mechanism

- src/PowerShellEditorServices/Services/PowerShell/Console/PSReadLineProxy.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
This redoes prior work that was lost during the rewrite. Specifically
this actually respects the user configuration of `BundledModulePath`
(also used by unit tests to provide compatibililty with xUnit), and
forces the use of only our bundled PSReadLine dependency.
Essentially this redoes #1514 and #1522.
> Fix `BundledModulePath` and PSReadLine loading (redux)

- src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
This prevents PSModulePath from having BundledModulePath added each time PSES is started and shutdown in the same process.
> Added check to see if PSModulePath already contained BundledModulePath

- module/PowerShellEditorServices/Start-EditorServices.ps1
- src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
In situations where the Debug server is not necessary, it is not possible to shutdown PSES as it hangs here:
https://github.com/PowerShell/PowerShellEditorServices/blob/96a8207db0ad3d692a8429de3373e65d0fa0624b/src/PowerShellEditorServices.Hosting/Internal/EditorServicesRunner.cs#L186
> Implemented -LanguageServiceOnly switch.

- src/PowerShellEditorServices/Services/Extension/ExtensionService.cs
This prevents accidental removal (and breakage of the extension) by disallowing `Remove-Variable` from removing `$psEditor`. While it's not expected anyone would do this, glob expressions may include the variable name and when piped to `Remove-Variable` resulted in a user-reported breakage.
Fixes https://github.com/PowerShell/vscode-powershell/issues/3718.
> Create `$psEditor` as a constant

- PowerShellEditorServices.build.ps1
- src/PowerShellEditorServices/Services/DebugAdapter/DebugEventHandlerService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/DebugStateService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/DebuggerStoppedEventArgs.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/SetVariableHandler.cs
- src/PowerShellEditorServices/Services/Extension/EditorOperationsService.cs
- src/PowerShellEditorServices/Services/PowerShell/Debugging/PowerShellDebugContext.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
- src/PowerShellEditorServices/Services/PowerShell/Utility/PowerShellExtensions.cs
- src/PowerShellEditorServices/Services/TextDocument/ScriptFile.cs
- src/PowerShellEditorServices/Utility/PSCommandExtensions.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
- test/PowerShellEditorServices.Test/PsesHostFactory.cs
Please see commits for work done.
> Re-enable `DebugServiceTests` suite

- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/VariableDetails.cs
- test/PowerShellEditorServices.Test.Shared/Debugging/VariableTest.ps1
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
This PR fixes https://github.com/PowerShell/vscode-powershell/issues/3703
$true and $false now highlight correctly regardless of vscode bug, and number/string type is still preserved.
> Add magic value formatting for variable booleans

- src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
- src/PowerShellEditorServices/Utility/PSCommandExtensions.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
This also corrects the scope of the script's parameter variables to be `Local` instead of `Command` in the `DebuggerAcceptsScriptArgs` test, and `Local` instead of `Auto` for most of the rest of the tests (as they
were previous to the pipeline work). Excitingly, this even fixes the `DebuggerSetsVariablesNoConversion` test, although
`DebuggerSetsVariablesWithConversion` is still broken (for a different reason).
Fixes https://github.com/PowerShell/vscode-powershell/issues/3715.
> Fix regression with `F5` to use `.` instead of `&` operator

- src/PowerShellEditorServices/Services/Extension/ExtensionService.cs
- test/PowerShellEditorServices.Test/Extensions/ExtensionCommandTests.cs
- test/PowerShellEditorServices.Test/Session/PsesInternalHostTests.cs
These tests actually did not require the language server nor the service provider, we just had to manually initialize the extension service itself. Resolves #1444.
> Re-enable `ExtensionCommandTests.cs`

- src/PowerShellEditorServices/Services/CodeLens/ICodeLensProvider.cs
- src/PowerShellEditorServices/Services/CodeLens/PesterCodeLensProvider.cs
- src/PowerShellEditorServices/Services/CodeLens/ReferencesCodeLensProvider.cs
- src/PowerShellEditorServices/Services/PowerShell/Utility/CommandHelpers.cs
- src/PowerShellEditorServices/Services/Symbols/SymbolsService.cs
- src/PowerShellEditorServices/Services/Symbols/Vistors/AstOperations.cs
- src/PowerShellEditorServices/Services/Symbols/Vistors/FindReferencesVisitor.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeLensHandlers.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/ReferencesHandler.cs
- test/PowerShellEditorServices.Test.Shared/References/FindsReferencesOnBuiltInCommandWithAlias.cs
- test/PowerShellEditorServices.Test/Language/SymbolsServiceTests.cs
- test/PowerShellEditorServices.Test/Services/Symbols/AstOperationsTests.cs
This work was spawned by a skipped unit test that "indicated a bug in the product code." The bug was that the support was removed, but could be brought back fairly simply now that the pipeline threading work is finished.
> Resurrect support to resolve aliased references

- src/PowerShellEditorServices/Services/PowerShell/Host/EditorServicesConsolePSHostUserInterface.cs
- src/PowerShellEditorServices/Utility/PSCommandExtensions.cs
Fixes #1667, PowerShell/vscode-powershell#3651
When we merge the `Information` stream into output it causes all information messages to be written directly to the output stream. This ignores `InformationAction` and also strips `Write-Host` of it's extra color/new line metadata.
This also fixes PowerShell/vscode-powershell#3705 (I would assume anyway)
> Fix `Write-Host -NoNewLine` and `-*Color`

- src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
- test/PowerShellEditorServices.Test/PsesHostFactory.cs
- test/PowerShellEditorServices.Test/Session/PsesInternalHostTests.cs
With these two bugs fixed, we can now set variables which are strongly typed (and so need a conversion) through the debugger. This was a great unit test that indicated a bug, and it was easily reproducible.
While testing manually, the scope bug revealed itself when I attempted to set a variable in the "automatic variables" container (the test is using the local variables container). I think assuming a default scope of "0" is sane because if it's an automatic variable, it must be in the local scope, and every other container is mapped to a named scope. As we learned previously, we cannot "guess" at a scope because they do not map one-to-one with stack frames.
The conversion bug was due to `SessionStateProxy.GetVariable("ExecutionContext")` throwing …
> Fix `DebuggerSetsVariablesWithConversion` test

- src/PowerShellEditorServices/Services/PowerShell/Debugging/PowerShellDebugContext.cs
Not entirely sure why this can be the case, but a stacktrace from a null
dereference crash indicates it can be null. Since the existing logic is
only doing something if the `ResumeAction` field is not null, I assume
we similarly do nothing if the entire object is also null (since that
implies the former, too).
Fixes #1672
> Handle `debuggerResult` being null in `ProcessDebuggerResult`

- PowerShellEditorServices.build.ps1
This prevents `dotnet` from unnecessarily rebuilding the library, though we lose the precise time and instead only have the date.
> Only update `BuildInfo.cs` if changed 

- .editorconfig
- PowerShellEditorServices.Common.props
This PR will configure the various .NET projects to use the editorconfig suppression settings, and adds several to demote existing (but working) warnings to suggestions, including rosylnator.
This is just meant as a stop-gap to ensure that dotnet build in CI looks "clean", so that finding/inspecting errors takes less time. Next step is to go back and selectively remove the warnings and either fix the code or drop a selective exception in for that particular warning. "Net-New" warning categories not already present in the current code have not been demoted and will continue to be reported as such.
With this, the VSCode is no longer a sea of yellow warnings, so when working on a PR it's much easier to see where specifically *your* code has issues. All issues are still reported as …
> Use EditorConfig for dotnet build and suppress existing issues

- src/PowerShellEditorServices/Services/TextDocument/ScriptFile.cs
The incoming line number is 1-indexed (not 0-indexed), so while the
lower limit was correctly set to 1, the upper limit was set to
`FileLines.Count` which could be 0, but 0 lines implies an upper limit
of 1 with this indexing. See `ScriptFile.GetLine` for the only other use
of this 1-index range validation.
Fixes #1663.
> Fix off-by-one error in validation within `GetOffsetAtPosition`

- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/DebugEvaluateHandler.cs
- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousTask.cs
- src/PowerShellEditorServices/Services/PowerShell/Handlers/EvaluateHandler.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
This fixes https://github.com/PowerShell/vscode-powershell/issues/3685 by awaiting the task spawned by the evaluate handler (triggered by F8) and skipping the "next" prompt that actually should have been interrupted by that foreground task.
> Display prompt after `F8` finishes

- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
This fixes https://github.com/PowerShell/vscode-powershell/issues/3786 by simply printing the prompt before the input of the command run by F8. It's almost cosmetic-only, except it does invoke the user's `prompt` function again which could have side-effects. What's more, we'll still have an empty prompt before the invocation; however, I believe that to be an accurate representation of what's happening because that prompt is canceled per my explanation here: https://github.com/PowerShell/vscode-powershell/issues/3786#issuecomment-1026354061
> Print prompt and command when `WriteInputToHost` is true

- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Small regression: accidentally called `Write...Write` instead of `Write...WriteLine`.
> Fix printing of command with F5

- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
We integrated PSES into our project and noticed a considerable increase in CPU usage while PSES is running.
I downloaded the PSES project and was able to step through the code and see it is executing a `while` loop with zero throttling.
Adding a `Thread.Sleep(100)` brought down the CPU of my application considerably when PSES was running.  I did not notice any increase in latency when using PSES itself either.
Here are the parameters we are using:
```c#
powershell.AddCommand("Start-EditorServices")
.AddParameter("HostName", "monaco")
.AddParameter("HostProfileId", "0")
.AddParameter("HostVersion", "1.0.0")
.AddParameter("LogPath", Path.ChangeExtension(Path.GetTempFileName(), ".log"))
.AddParameter("LogLevel", "Normal")
.AddParameter("FeatureFlags", Array.Empty<string>()) …
```
> Add `Thread.Sleep(100)` to throttle REPL when it's non-interactive

- src/PowerShellEditorServices/Services/Extension/ExtensionService.cs
- src/PowerShellEditorServices/Services/PowerShell/Console/LegacyReadLine.cs
- src/PowerShellEditorServices/Services/PowerShell/Debugging/DscBreakpointCapability.cs
- src/PowerShellEditorServices/Services/PowerShell/Execution/ExecutionOptions.cs
- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousDelegateTask.cs
- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
- src/PowerShellEditorServices/Services/PowerShell/Utility/CommandHelpers.cs
- src/PowerShellEditorServices/Services/Workspace/RemoteFileManagerService.cs
I think this was a case of premature optimization. We're using C#
records, which should be as cheap as an object as they come, especially
when we can rely on the compiler for default values. Now we're passing
fewer objects around too.
> Replace superfluous `Default` member with default values

- .vsts-ci/templates/ci-general.yml
- .vsts-ci/templates/release-general.yml
> Add SBOM template

- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousDelegateTask.cs
- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousTask.cs
But at the `SynchronousTask` level. Now we get the best of both worlds:
the records have the correct default values on initialization, and we
only heap allocate a single static instance of `ExecutionOptions` for
the default case.
> Use `static readonly` for default `ExecutionOptions`

- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
This changes how we decide to run a given command through
`ExecuteInDebugger` or `ExecuteNormally`. It now restricts the former
such that it is only used for PowerShell's intrinsic debugger commands
(like `s`, `c`, etc.) and the latter is used for any other user command
or, more importantly, our own implementation's debugger commands (like
when we call `Get-Variable`).
> Avoid recording debugger commands in the history

- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
While we need to cancel the debugger if a debugged task is running and
Ctrl-C is issued, we explicitly are not running the debugged task when
we're stopped in a breakpoint. Instead, the user can be running
unrelated tasks and may wish to cancel them without stopping the
debugger.
Fixes https://github.com/PowerShell/vscode-powershell/issues/3832 and https://github.com/PowerShell/PowerShellEditorServices/issues/1708
> Avoid stopping the debugger when canceling other tasks in a debug session

- src/PowerShellEditorServices/Services/PowerShell/Host/EditorServicesConsolePSHost.cs
This may fix color formatting for old version of PowerShell.
Fixes #1607
> Redirect `EditorServicesConsolePSHost.PrivateData` to `_internalHost`

- .vsts-ci/azure-pipelines-release.yml
- .vsts-ci/templates/ci-general.yml
- PowerShellEditorServices.build.ps1
- tools/azurePipelinesBuild.ps1
This removes our build script's dependency on the `install-dotnet` script (which is only meant for use in CI, but we now use an ADO task for that, and so that we can rely on pre-installed versions of .NET if available). Developers will need to follow .NET Core's instructions to install .NET SDK 6.0, and the 3.1 runtime for the end-to-end tests. Fortunately, this actually eases the developer workflow by no longer being sensitive to a local installation of `dotnet`, so the C# extension in Code now "just works."
This updates the release pipeline to use the `PMMSWindows2019-Secure` for build, sign, and release.
This also updates our required and installed `InvokeBuild` and `platyPS` modules for the build, which is probably the most annoying part of this PR as devs will need to run …
> Use global `dotnet` and update build dependencies

- src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeActionHandler.cs
Currently, PSSA's `SuggestCorrections` property of the
`DiagnosticRecord` object already is an array, but no built-in rules
return more than one suggested correction, which led to
`PowerShellEditorServices` not correctly translating this array before
returning it as an code action as it only ever displayed one. This fixes
it by making it generic again so it returns a code action for each
suggest correction. It's basically just performing a `foreach` loop and
calling `ToTextEdit` just once.
This is a pre-requisite for an implementation of this, where a built-in
rule will return multiple suggest corrections:
https://github.com/PowerShell/PSScriptAnalyzer/issues/1767
I've manually tested this with a modified version of PSScriptAnalyzer
where I return two suggested corrections. The …
> Return a code action for each diagnostic record

- src/PowerShellEditorServices/Services/PowerShell/Host/EditorServicesConsolePSHostUserInterface.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
This seems to work. We needed to hold onto processed progress records,
and then at the end of the REPL mark each as completed and re-write it
(which uses the underlying host and effectively clears it).
Fixes https://github.com/PowerShell/vscode-powershell/issues/3807
> Reset progress messages at end of REPL

- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
- src/PowerShellEditorServices/Utility/PSCommandExtensions.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
We managed to make the previous hack work while continuing to support
passing the users' arguments. As there was demand for this feature to
continue working, despite being a hack, we're keeping it.
> Re-enable line breakpoints for untitled scripts

- src/PowerShellEditorServices/Services/Workspace/Handlers/ConfigurationHandler.cs
- src/PowerShellEditorServices/Services/Workspace/LanguageServerSettings.cs
At this point it just ignores the entries that are clauses instead of a straight boolean, but hey now it doesn't crash 😄 
Fixes https://github.com/PowerShell/vscode-powershell/issues/2658
> Avoid error when `exclude` entry is a clause

- src/PowerShellEditorServices/Extensions/Api/ExtensionCommandService.cs
- src/PowerShellEditorServices/Services/Extension/ExtensionService.cs
- src/PowerShellEditorServices/Services/Extension/Handlers/InvokeExtensionCommandHandler.cs
- src/PowerShellEditorServices/Services/PowerShell/Handlers/EvaluateHandler.cs
Also refactored it slightly to accept the existing `cancellationToken` send to the handler, and removed an unused logger service. This fixes https://github.com/PowerShell/vscode-powershell/issues/3691.
> Fix editor commands to interrupt current prompt

- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
> Redirect `PSHost.Notify*Application` methods

- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
We missed the middle layer: public host redirected to internal host, but
then internal host needed to redirect to `_hostInfo.PSHost`. Now that it
does, `$Host.PrivateData` actually shows the correct console color
values, and so `Write-Error 'something'` shows up in the correct color.
Also applied Roslynator suggestions to clean some things up.
> Finish redirection of `$Host.PrivateData`

- src/PowerShellEditorServices/Services/PowerShell/Handlers/GetVersionHandler.cs
- src/PowerShellEditorServices/Services/Workspace/Handlers/ConfigurationHandler.cs
- src/PowerShellEditorServices/Services/Workspace/LanguageServerSettings.cs
> Remove `PackageManagement` module update prompt

- src/PowerShellEditorServices/Services/PowerShell/Host/EditorServicesConsolePSHostUserInterface.cs
And stop using reflection to find `_externalUI`. This is not necessary in order to reuse PowerShell's built-in prompt logic (which was its original goal). Unfortunately this doesn't fix the issues it was written in an attempt to fix, but it does remove unnecessary reflection logic.
> Replace `_consoleHostUI` with `_underlyingHostUI`

- src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeActionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/ScriptFileMarker.cs
With the recent fix in PR #1718, PSES processes now all Correction objects from PSSA but the message specifically was just taken from the last correction [here](https://github.com/PowerShell/PowerShellEditorServices/blob/e555dc050d3ef36272ba6f84925086cb7abc048a/src/PowerShellEditorServices/Services/TextDocument/ScriptFileMarker.cs#L150). I did not notice this at first because I thought I had to tweak my rule first to emit two different messages until I realized it was another bug in PSES.
Related: https://github.com/PowerShell/PSScriptAnalyzer/pull/1782
Proof here that the message of each correction is associated to it as well (the actual code fix already was)
BEFORE
AFTER
> Correctly map `SuggestedCorrection` to `MarkerCorrection`

- .editorconfig
- PowerShellEditorServices.Common.props
- src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
- src/PowerShellEditorServices.Hosting/Configuration/EditorServicesConfig.cs
- src/PowerShellEditorServices.Hosting/Configuration/TransportConfig.cs
- src/PowerShellEditorServices.Hosting/Internal/NamedPipeUtils.cs
- src/PowerShellEditorServices/Hosting/EditorServicesServerFactory.cs
- src/PowerShellEditorServices/Server/PsesDebugServer.cs
- src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Services/Analysis/PssaCmdletAnalysisEngine.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/DisconnectHandler.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/LaunchAndAttachHandler.cs
- src/PowerShellEditorServices/Services/PowerShell/Utility/ErrorRecordExtensions.cs
- src/PowerShellEditorServices/Services/TextDocument/FoldingReference.cs
- src/PowerShellEditorServices/Services/TextDocument/TokenOperations.cs
- src/PowerShellEditorServices/Services/Workspace/Handlers/ConfigurationHandler.cs
- src/PowerShellEditorServices/Services/Workspace/LanguageServerSettings.cs
- test/PowerShellEditorServices.Test.E2E/Processes/StdioServerProcess.cs
- test/PowerShellEditorServices.Test.Shared/Completion/CompleteCommandFromModule.cs
- test/PowerShellEditorServices.Test.Shared/TestUtilities/TestUtilities.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
- test/PowerShellEditorServices.Test/Session/PathEscapingTests.cs
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
By upgrading these from `warning` to `error` we get the equivalent of `dotnet format --verify-no-changes` without having to call it twice (which slowed down the build, and was unnecessary since the compiler is already running all the rules). Also enabled _yet more_ rules 😅
> Enable code analysis and formatting as errors on build

- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
This should make default prompt spam significantly less likely or impossible. Also fixes a scenario here if the REPL loop is evaluating and in an attached process, closing the attachee would dead lock.
Also fixed a logic bug that probably caused some not yet seen issues.
> Fix prompt spam and general debugger reliability improvements

- src/PowerShellEditorServices/Services/Analysis/PssaCmdletAnalysisEngine.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/FormattingHandlers.cs
Now we return `null` per the LSP specification if the formatting request was canceled (such as will happen if the document is modified since the request was sent), and we only load our bundled PSScriptAnalzyer module. Similar to PSReadLine, we should not support loading an arbitrary version of the module, as that leads to difficult to fix bugs and complicates the code.
Should fix https://github.com/PowerShell/vscode-powershell/issues/3928 and https://github.com/PowerShell/vscode-powershell/issues/3926.
> Fix formatting handlers and PSScriptAnalyzer loading

- PowerShellEditorServices.build.ps1
- src/PowerShellEditorServices.Hosting/PowerShellEditorServices.Hosting.csproj
- test/PowerShellEditorServices.Test.Shared/TestUtilities/TestUtilities.cs
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
See [announcement](https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/).
Resolves #1761
> Bump `net461` to `net462` due to upcoming end of support

- .editorconfig
- PowerShellEditorServices.Common.props
- src/PowerShellEditorServices.Hosting/Configuration/HostLogger.cs
- src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
- src/PowerShellEditorServices/Extensions/Api/EditorExtensionServiceProvider.cs
- src/PowerShellEditorServices/Extensions/EditorObject.cs
- src/PowerShellEditorServices/Extensions/FileContext.cs
- src/PowerShellEditorServices/Hosting/EditorServicesServerFactory.cs
- src/PowerShellEditorServices/Hosting/HostStartupInfo.cs
- src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/BreakpointApiUtils.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/BreakpointDetails.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/DebuggerStoppedEventArgs.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/StackFrameDetails.cs
- src/PowerShellEditorServices/Services/Extension/ExtensionService.cs
- src/PowerShellEditorServices/Services/PowerShell/Context/PowerShellContextFrame.cs
- src/PowerShellEditorServices/Services/PowerShell/Context/PowerShellVersionDetails.cs
- src/PowerShellEditorServices/Services/PowerShell/Runspace/SessionDetails.cs
- src/PowerShellEditorServices/Services/PowerShell/Utility/CommandHelpers.cs
- src/PowerShellEditorServices/Services/Symbols/ScriptDocumentSymbolProvider.cs
- src/PowerShellEditorServices/Services/Symbols/Vistors/AstOperations.cs
- src/PowerShellEditorServices/Services/Template/TemplateService.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
- src/PowerShellEditorServices/Services/Workspace/LanguageServerSettings.cs
- src/PowerShellEditorServices/Services/Workspace/RemoteFileManagerService.cs
- src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs
Due to a quirk in how `msbuild` runs rules, documentation generation
must be enabled for this rule (and presumably others) to be respected.
See https://github.com/dotnet/roslyn/issues/22579.
Fixes https://github.com/PowerShell/PowerShellEditorServices/issues/1479.
> Enable IDE0005 (unneccessary using statements) as error

- modules.json
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Which wasn't reliable anyway, because it could be translated to different things depending on the system and encodings in use. PSReadLine now just discards any key input after cancellation.
Requires https://github.com/PowerShell/PSReadLine/pull/3274 and fixes https://github.com/PowerShell/PowerShellEditorServices/issues/1754.
> With a fix in PSReadLine, we don't have to return a "null" key press

- module/PowerShellEditorServices/PowerShellEditorServices.psd1
- src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
> Fix missed .NET 4.6.2 code

- src/PowerShellEditorServices/Services/PowerShell/Utility/CancellationContext.cs
This eliminates an extra cancellation on tokens that are getting disposed.
> Don't cancel on disposal of `CancellationScope`

- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
- src/PowerShellEditorServices/Services/Extension/ExtensionService.cs
- src/PowerShellEditorServices/Services/PowerShell/Console/PsrlReadLine.cs
- src/PowerShellEditorServices/Services/PowerShell/Execution/BlockingConcurrentDeque.cs
- src/PowerShellEditorServices/Services/PowerShell/Execution/ExecutionOptions.cs
- src/PowerShellEditorServices/Services/PowerShell/Handlers/EvaluateHandler.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
- src/PowerShellEditorServices/Services/Template/TemplateService.cs
And set them consistently. If the task needs to interrupt or run in the foreground, it really needs to do both. Also fixes some indentation.
> Consolidate `InterruptCurrentForeground` and `MustRunInForeground`

- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/LaunchAndAttachHandler.cs
- src/PowerShellEditorServices/Services/PowerShell/Debugging/PowerShellDebugContext.cs
- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
This requires that we set the REPL to exit correctly. Note that we don't
have a notion of "disconnect" so we removed that logic. We are assuming
the debugger is "active" a little earlier now, that is, also when we've
received an LSP notification to start it (via a launch or attach
handler). Because we receive a notification on "disconnect" even for a
script just finishing, we need to know that the server is not active and
so not cancel the current prompt.
> Fix extra prompting and manual debugger commands

- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
We were running into a situation where we'd print the prompt on the same line that we had previously printed it. This was especially noticable when stepping through the debugger.
This change ensures that we always write a new line if that situation occurs.
Examples:
> Bring back `WriteWithPrompt()`

- src/PowerShellEditorServices/Services/Extension/ExtensionService.cs
- src/PowerShellEditorServices/Services/PowerShell/Execution/ExecutionOptions.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
- src/PowerShellEditorServices/Services/Workspace/Handlers/ConfigurationHandler.cs
- src/PowerShellEditorServices/Services/Workspace/RemoteFileManagerService.cs
The thing is, `RequiresForeground` necessarily implies an execution
priority of `Next`. So instead we set that priority explicitly for
`psEditor` and mark none of the startup tasks as requiring foreground,
because they're all started before we enter the REPL where that matters.
> Fix ordering of startup tasks so `psEditor` is defined before profiles are loaded

- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Fixes PowerShell/vscode-powershell#3944
This fixes an issue reported by @PrzemyslawKlys on discord:
https://cdn.discordapp.com/attachments/447579065877266454/970295608797704212/F8_continue.gif)
> Do not exit from `DebuggerStop` unless resuming

- src/PowerShellEditorServices/Services/PowerShell/Host/EditorServicesConsolePSHostUserInterface.cs
Without this, `InternalHostUserInterface` will try to emulate support, potentially leading to different runtime behavior.
> Add `IHostUISupportsMultipleChoiceSelection` implementation

- src/PowerShellEditorServices/Hosting/EditorServicesServerFactory.cs
- src/PowerShellEditorServices/Server/PsesDebugServer.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
This is kind of messy, but it fixes https://github.com/PowerShell/vscode-powershell/issues/3950.
> Send `sendKeyPress` event across DAP for temporary integrated consoles

- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Sets the Thread max stack size to use the same value that is normally used in console host. This gives PowerShell code more room for execution, so recursive calls, or calls that are wrapped in Pester (which itself is stack-hungry), won't fail with: 
```
System.Management.Automation.ScriptCallDepthException: The script failed due to call depth overflow.
```
Fix https://github.com/PowerShell/vscode-powershell/issues/3962
> Increase stack size for PowerShell 5

- src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
- src/PowerShellEditorServices/Hosting/EditorServicesServerFactory.cs
- src/PowerShellEditorServices/Server/PsesDebugServer.cs
- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
- src/PowerShellEditorServices/Server/PsesServiceCollectionExtensions.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/NullPSHostRawUI.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/NullPSHostUI.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
- src/PowerShellEditorServices/Services/Symbols/Vistors/AstOperations.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeLensHandlers.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DocumentHighlightHandler.cs
- src/PowerShellEditorServices/Services/Workspace/Handlers/ConfigurationHandler.cs
- test/PowerShellEditorServices.Test.Shared/Completion/CompleteAttributeValue.cs
- test/PowerShellEditorServices.Test.Shared/Completion/CompleteCommandFromModule.cs
- test/PowerShellEditorServices.Test.Shared/Completion/CompleteCommandInFile.cs
- test/PowerShellEditorServices.Test.Shared/Completion/CompleteNamespace.cs
- test/PowerShellEditorServices.Test.Shared/Completion/CompleteTypeName.cs
- test/PowerShellEditorServices.Test.Shared/Completion/CompleteVariableInFile.cs
In addition to a few clean-ups, the primary fix here is to start the PowerShell host in the `initialize` request handler, instead of the `onDidChangeConfiguration` handler, which only worked as it relied on a quirk of the VS Code client. In order to do this, we now expect to receive the settings `EnableProfileLoading: bool` and `InitialWorkingDirectory: string` as initialization parameters.
Fixes https://github.com/PowerShell/PowerShellEditorServices/issues/1695.
> Re-enable stdio clients by fixing initialization sequence

- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
- src/PowerShellEditorServices/Services/CodeLens/ICodeLensProvider.cs
- src/PowerShellEditorServices/Services/CodeLens/PesterCodeLensProvider.cs
- src/PowerShellEditorServices/Services/CodeLens/ReferencesCodeLensProvider.cs
- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousTask.cs
- src/PowerShellEditorServices/Services/PowerShell/Utility/CommandHelpers.cs
- src/PowerShellEditorServices/Services/Symbols/SymbolsService.cs
- src/PowerShellEditorServices/Services/Symbols/Vistors/AstOperations.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeLensHandlers.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/ReferencesHandler.cs
- src/PowerShellEditorServices/Services/Workspace/Handlers/WorkspaceSymbolsHandler.cs
- test/PowerShellEditorServices.Test/Language/CompletionHandlerTests.cs
(each section is it's own commit for easier review)
This stops completion from being cancelled whenever a `DidChangeTextDocument` notification is sent. So previously, if you typed `Get-` very quickly, you'd get no results at all. It also lets completion cancel some other expensive requests like code lens.
**Note:** the one *not fantastic* down side of this is it makes "missing" code lenses more likely. By missing I mean:
I have not yet figured out a way to tell VSCode to just try again next time it's able. Also we were already getting this sometimes, but this change does make it at least a bit more likely.
We were exiting `SynchronousTask.ExecuteSynchronously` early if the cancellation was already requested. This was not setting our tcs state correctly, causing the caller to just fall off …
> Fix a lot of IntelliSense issues

- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
Thanks to a brilliant idea from Patrick, this simplifies how we choose which commands to execute through PowerShell's debugger API, and also fixes an issue where a user's custom prompt function wasn't aware that it was in the debugger.
This fixes https://github.com/PowerShell/vscode-powershell/issues/3980.
> Fix execution of debug prompt commands

- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
- test/PowerShellEditorServices.Test.E2E/LSPTestsFixures.cs
So it can be turned off if needed, but otherwise has a sane default.
> Set `EnableProfileLoading` default to `true`

- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
- src/PowerShellEditorServices/Services/PowerShell/Utility/PowerShellExtensions.cs
- src/PowerShellEditorServices/Utility/PSCommandExtensions.cs
The service would fail to fully start if zero profiles were present, because that meant we attempted to invoke an empty command, which then threw `PSInvalidOperationException: No commands are specified`. This wasn't caught by our task executor, since it happened in a delegate which directly invoked the command.
> Fix startup bug when zero profiles are present

- src/PowerShellEditorServices/Services/Symbols/Vistors/AstOperations.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
- src/PowerShellEditorServices/Utility/Extensions.cs
- src/PowerShellEditorServices/Utility/FormatUtils.cs
- test/PowerShellEditorServices.Test/Language/CompletionHandlerTests.cs
- Update intellisense logging (Now shows the word to complete and match count instead of the literal type name for `SMA.CommandCompletion`).
- Fix type name completion when utilizing `using namespace` statements
- Add support for completing paths with `$PSScriptRoot` and retaining it in the result (requires PowerShell/PowerShell#17376)
> Additional IntelliSense fixes and ToolTip overhaul

- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/LaunchAndAttachHandler.cs
Since we're not setting `DebugContext.IsActive` sooner, we also need to set `IsDebuggingRemoteRunspace` early as well. Otherwise `DoOneRepl` sees `IsActive`, but not in a breakpoint, and stops debugging.
> Set `IsDebuggingRemoteRunspace` sooner for attach

- src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
Pressing a quote character at the start of a string and committing to a
path accidently is really annoying.
> Remove bad UX of commit characters for paths

- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
If the `ErrorActionPreference` is set to `Break` and the user hits the
Stop button in the UI, then we need to exit early on reentrance of
`OnDebuggerStop`. Currently we deadlock until they hit stop again.
Fixes PowerShell/vscode-powershell#4010
> Exit debugger stop early if cause is PSE

- .github/workflows/emacs-test.yml
- test/emacs-test.el
This adds regression tests written in Emacs to validate that PSES can be connected (and reports diagnostics) with a client that isn't VS Code, namely [Eglot](https://github.com/joaotavora/eglot), and Emacs LSP client.
> Add Emacs regression tests for PSES

- src/PowerShellEditorServices/Services/PowerShell/Console/IReadLine.cs
- src/PowerShellEditorServices/Services/PowerShell/Console/PsrlReadLine.cs
- src/PowerShellEditorServices/Services/PowerShell/Console/TerminalReadLine.cs
- src/PowerShellEditorServices/Services/PowerShell/Execution/ExecutionOptions.cs
- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Fixes PowerShell/vscode-powershell#3683
This PR just fixes the regression of history not including <kbd>F5</kbd>/<kbd>F8</kbd>. Opened #1822 to track making this configurable
> Utilize the `AddToHistory` delegate from PSRL proxy

- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
- src/PowerShellEditorServices/Services/Symbols/SymbolsService.cs
- src/PowerShellEditorServices/Services/Symbols/Vistors/AstOperations.cs
- src/PowerShellEditorServices/Services/TextDocument/ScriptFile.cs
- src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs
- test/PowerShellEditorServices.Test.E2E/DebugAdapterClientExtensions.cs
- test/PowerShellEditorServices.Test.E2E/DebugAdapterProtocolMessageTests.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
- test/PowerShellEditorServices.Test.E2E/Processes/PsesStdioProcess.cs
- test/PowerShellEditorServices.Test/Language/SymbolsServiceTests.cs
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
Specifically targeting the edge case where the last line of the script is a comment. Covers https://github.com/PowerShell/vscode-powershell/issues/3965
> Add regression test for untitled scripts in Windows PowerShell

- test/PowerShellEditorServices.Test.Shared/Profile/Test.PowerShellEditorServices_profile.ps1
- test/PowerShellEditorServices.Test/Session/PsesInternalHostTests.cs
Now we actually check that it is well-formed.
> Improve `$PROFILE` variable and profile loading test

- src/PowerShellEditorServices/Services/PowerShell/Console/README.md
Resolves #1831.
Folks who may find this interesting: @SteveL-MSFT @daxian-dbw @TylerLeonhardt @jrieken @stephentoub @daviwil 👋
> Add readme about `ReadKey` workarounds

- PowerShellEditorServices.build.ps1
Windows 11 updated and got smarter, this can now also be ARM64 (which is
more precise).
> Update processor architecture check in build script

- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousTask.cs
Fixes PowerShell/vscode-powershell#4038
It's not a good sign that this slowed everything down, but at least it's
easy to revert. More investigation is required.
> Don't use `RunContinuationsAsynchronously` for our `TaskCompletionSource`

- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
This was much more easily accomplished by checking if what we were given
exists as a file path, in which case we use it as-is (a file path, that
must exist, since we launch it directly). Otherwise we can assume that
it's a raw script block, or a URI from the client that probably
represents an untitled file.
> Fix logic checking for untitled or raw scripts

- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Otherwise PSReadLine thinks it's supposed to re-insert it in the buffer after execution.
This is an extension of https://github.com/PowerShell/PowerShellEditorServices/pull/1823 which fixes https://github.com/PowerShell/vscode-powershell/issues/3683, but fixes https://github.com/PowerShell/vscode-powershell/issues/4041 too.
> Add command to PSReadLine history before cancellation

- PowerShellEditorServices.build.ps1
- src/PowerShellEditorServices/Server/PsesServiceCollectionExtensions.cs
- src/PowerShellEditorServices/Services/DebugAdapter/DebugEventHandlerService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/LaunchAndAttachHandler.cs
- src/PowerShellEditorServices/Services/PowerShell/Context/PowerShellContextFrame.cs
- src/PowerShellEditorServices/Services/PowerShell/Context/PowerShellVersionDetails.cs
- src/PowerShellEditorServices/Services/PowerShell/Debugging/PowerShellDebugContext.cs
- src/PowerShellEditorServices/Services/PowerShell/Handlers/IGetPSHostProcessesHandler.cs
- src/PowerShellEditorServices/Services/PowerShell/Handlers/PSHostProcessAndRunspaceHandlers.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
- src/PowerShellEditorServices/Services/PowerShell/Utility/CancellationContext.cs
- test/PowerShellEditorServices.Test.E2E/DebugAdapterClientExtensions.cs
- test/PowerShellEditorServices.Test.E2E/DebugAdapterProtocolMessageTests.cs
- test/PowerShellEditorServices.Test.E2E/LSPTestsFixures.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
- test/PowerShellEditorServices.Test.E2E/Processes/ServerProcess.cs
- test/PowerShellEditorServices.Test.Shared/Completion/CompleteAttributeValue.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
- test/PowerShellEditorServices.Test/Extensions/ExtensionCommandTests.cs
- test/PowerShellEditorServices.Test/Language/CompletionHandlerTests.cs
- test/PowerShellEditorServices.Test/Language/SymbolsServiceTests.cs
- test/PowerShellEditorServices.Test/Session/PsesInternalHostTests.cs
- test/PowerShellEditorServices.Test/Session/WorkspaceTests.cs
By removing arbitrary timeouts, fixing disposal bugs, and cleaning up tests. Resolves #1793.
> Improve CI stability

- test/PowerShellEditorServices.Test.E2E/DebugAdapterProtocolMessageTests.cs
I couldn't actually get https://github.com/PowerShell/PowerShellEditorServices/issues/1672 to repro, but I did add a comprehensive end-to-end test for running a Pester test file.
> Add end-to-end Pester unit test

- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
- test/PowerShellEditorServices.Test/Session/PsesInternalHostTests.cs
There was an edge case where, after setting and un-setting the `powershell.cwd` property in the VS Code client, instead of being `null` the setting would be the empty string `""`. The client did not care about this, and so left the server to silently crash on startup. We previously assumed that by the time the server started, the directory would be validated by the client, but this was wrong. So now we check its existence first.
Resolves #1849 (with a regression test too).
> Add `Directory.Exists()` check to `SetInitialWorkingDirectoryAsync()`

- src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
- test/PowerShellEditorServices.Test/Extensions/ExtensionCommandTests.cs
Our flaky extension command test seems to be flaky because sometimes another task gets queued, and since it runs in the foreground it cancels that task. Interactively, this happens in the first loop (with `DoOneRepl`) which catches the cancellation exception; but when under tests that is a no-op, so it happens in the second loop. Hence we should duplicate the same logic and so catch that exception.
> Catch `OperationCanceledException` in both command loops

- test/PowerShellEditorServices.Test.Shared/Debugging/PSDebugContextTest.ps1
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
This covers the regression reported in https://github.com/PowerShell/vscode-powershell/issues/3980 and fixed in https://github.com/PowerShell/PowerShellEditorServices/pull/1803, part of https://github.com/PowerShell/PowerShellEditorServices/issues/1733.
> Add regression test for `$PSDebugContext` in `prompt` function

- test/PowerShellEditorServices.Test.E2E/DebugAdapterProtocolMessageTests.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
Covers regression in https://github.com/PowerShell/vscode-powershell/issues/3715.
> Add regression test for debugging script with dot-source operator

- .vsts-ci/azure-pipelines-ci.yml
Now includes Windows Server 2022 and macOS 11 Big Sur.
Necessary per https://github.com/actions/virtual-environments/issues/5583.
> Update and extend CI matrix

- README.md
- src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
- src/PowerShellEditorServices.Hosting/Configuration/EditorServicesConfig.cs
- src/PowerShellEditorServices.Hosting/Internal/EditorServicesRunner.cs
- src/PowerShellEditorServices/Hosting/EditorServicesServerFactory.cs
- src/PowerShellEditorServices/Hosting/HostStartupInfo.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/LaunchAndAttachHandler.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
- test/PowerShellEditorServices.Test.E2E/DebugAdapterProtocolMessageTests.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
- test/emacs-test.el
Except the startup banner as its the default, and may not be for the VS Code extension but for any client that connects to PSES and supports a terminal.
Part of https://github.com/PowerShell/vscode-powershell/issues/4053.
> Rename "Integrated Console" to "Extension Terminal"

- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
- test/PowerShellEditorServices.Test.E2E/DebugAdapterProtocolMessageTests.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
This is a regression test for https://github.com/PowerShell/vscode-powershell/issues/3655.
> Add `DebuggerBreaksInUntitledScript` unit test

- src/PowerShellEditorServices/Hosting/HostStartupInfo.cs
- src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Services/Analysis/PssaCmdletAnalysisEngine.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
- test/PowerShellEditorServices.Test/Extensions/ExtensionCommandTests.cs
- test/PowerShellEditorServices.Test/Language/CompletionHandlerTests.cs
- test/PowerShellEditorServices.Test/Language/SemanticTokenTest.cs
- test/PowerShellEditorServices.Test/Language/SymbolsServiceTests.cs
- test/PowerShellEditorServices.Test/Language/TokenOperationsTests.cs
- test/PowerShellEditorServices.Test/Services/Symbols/AstOperationsTests.cs
- test/PowerShellEditorServices.Test/Services/Symbols/PSScriptAnalyzerTests.cs
- test/PowerShellEditorServices.Test/Session/PathEscapingTests.cs
- test/PowerShellEditorServices.Test/Session/PsesInternalHostTests.cs
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
- test/PowerShellEditorServices.Test/Session/WorkspaceTests.cs
Also refactor a bit so we're not triplicating this logic.
Resolves https://github.com/PowerShell/vscode-powershell/issues/2697.
I need to add some tests which just ensure PSSA loads and has rules.
> Use `HostInfo.BundledModulePath` to find PSScriptAnalyzer

- test/PowerShellEditorServices.Test/Session/PsesInternalHostTests.cs
Also improve regression test for when it throws.
Regression test for https://github.com/PowerShell/PowerShellEditorServices/issues/1699.
> Add regression test for when `prompt` is undefined

- src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
Clears the cached DiagnosticsMarkers for a file before adding new results from full script analysis.
Reopening a file with PSSA-findings will be duplicated each time the file is closed and reopened.
Fix PowerShell/vscode-powershell#3252
> Fix duplicate DiagnosticMarkers when reopening a file

- src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
- test/PowerShellEditorServices.Test/Extensions/ExtensionCommandTests.cs
- test/PowerShellEditorServices.Test/Services/Symbols/PSScriptAnalyzerTests.cs
This is a regression test for https://github.com/PowerShell/PowerShellEditorServices/pull/1869.
> Add `DoesNotDuplicateScriptMarkersAsync` regression test

- test/PowerShellEditorServices.Test/Services/Symbols/PSScriptAnalyzerTests.cs
- test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
Regression tests to verify diagnostic markers for parse errors are:
- Registered on file open (first time)
- Updated on file change
- Not overwritten by AnalysisService (PSSA)
No tests for this feature AFAIK.
Broke this momentarily while working on #1869
> Add regression tests for parse error DiagnosticMarkers

- src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Services/Analysis/PssaCmdletAnalysisEngine.cs
- test/PowerShellEditorServices.Test/Services/Symbols/PSScriptAnalyzerTests.cs
When we swapped a ternary for a null-coalescing operator we ran into a problem because the two constructor overloads took `string[]` and `object`, and we were now calling the constructor first, which meant the `object` version was always being called. This erroneously sent the rule list to the settings object parameter.
Fixes https://github.com/PowerShell/vscode-powershell/issues/4112.
> Fix (and test) regression with PSScriptAnalyzer default rules

- .github/workflows/emacs-test.yml
- .github/workflows/vim-test.yml
- test/.themisrc
- test/vim-test.ps1
- test/vim-test.vim
> Add end-to-end integration test with Vim

- .vsts-ci/templates/ci-general.yml
The latest update has blocked the CI/CD pipeline, and so while we investigate that, we'll pin to the last known working version.
Works around https://github.com/PowerShell/PowerShellEditorServices/issues/1877 for now.
> Pin .NET to 6.0.302 and 3.1.27

- PowerShellEditorServices.build.ps1
And only PowerShell Core on CI with `pwsh.exe`, and re-enable the PowerShell 7.0 tests (oops).
> Only run Windows PowerShell 5.1 tests on CI with `powershell.exe`

- src/PowerShellEditorServices/Services/Symbols/PesterDocumentSymbolProvider.cs
- test/PowerShellEditorServices.Test/Language/SymbolsServiceTests.cs
Trims leading whitespace in Pester symbol name. Also implements scaffolded regression test.
Fix #1891
> Fix whitespace in Pester symbol and add test

- src/PowerShellEditorServices/Services/Symbols/Vistors/FindReferencesVisitor.cs
- src/PowerShellEditorServices/Services/Symbols/Vistors/FindSymbolVisitor.cs
- src/PowerShellEditorServices/Utility/VisitorUtils.cs
- test/PowerShellEditorServices.Test/Services/Symbols/AstOperationsTests.cs
Fixes:
- Hovering a function name does not work properly when function is indented
- Highlight-range when hovering function name. Currently includes the scriptblock when it's not supposed to.
Fix #1887
Fix #1888
> Fix symbol highlight when hovering function name

- src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
- src/PowerShellEditorServices/Services/PowerShell/Debugging/PowerShellDebugContext.cs
- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
Trying to step when any nested command that wasn't PSRL was running caused us to essentially ignore the request. This caused VSCode to think we were "running" while we didn't actually cancel anything.
> Fix stepping while watch expressions or interactive pipeline is running

- .vsts-ci/templates/ci-general.yml
- test/PowerShellEditorServices.Test/Language/CompletionHandlerTests.cs
This reverts commit 8b6c2b9b853f888e37e075dc472b410f844725a1.
> Revert "Pin .NET to 6.0.302 and 3.1.27 (#1878)"

- src/PowerShellEditorServices/Services/CodeLens/PesterCodeLensProvider.cs
- src/PowerShellEditorServices/Services/Symbols/PesterDocumentSymbolProvider.cs
- src/PowerShellEditorServices/Services/Workspace/Handlers/WorkspaceSymbolsHandler.cs
- test/PowerShellEditorServices.Test.Shared/Symbols/PesterFile.tests.ps1
- test/PowerShellEditorServices.Test/Language/SymbolsServiceTests.cs
Adds document symbols for setup and teardown blocks used in Pester to improve navigation using outline and sticky scroll (experimental VSCode feature).
Sticky scroll and breadcrumbs:
Outline:
Setup/teardown symbols are excluded from workspace symbol search to avoid filling it up with thousand identical symbols like "BeforeAll { }".
Fix #1892
> Add symbols for Pester setup and teardown blocks

- src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs
- test/PowerShellEditorServices.Test/Session/WorkspaceTests.cs
Use a consistent dictionary key for CRUD operations in `WorkspaceService.workspaceFiles`
Fix #1901
> Fix file close in workspace service for Linux

- src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/StackFrameDetails.cs
- src/PowerShellEditorServices/Utility/PathUtils.cs
Fixes #1897 
Fixes PowerShell/vscode-powershell#4103
When stepping into certain contexts like a `param` block's default value expression, the engine does not provide a call stack frame to represent it. In this scenario we want to create an artificial call stack frame to represent the context we've stepped into.
> Add artificial stack frame to represent contexts without one

- src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
> Remove `null` markers to avoid `NullReferenceException`

- README.md
See title
Development has ceased in https://github.com/kiennq/lsp-powershell, and the README there now points to [`lsp-pwsh.el`](https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-pwsh.el) in the Emacs-LSP project.
> Update link to emacs-lsp lsp-pwsh plugin

- src/PowerShellEditorServices/Services/PowerShell/Console/ReadLineProvider.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
This tests both the PowerShell history and the PSReadLine history via a stub, since we can't load PSReadLine itself in these tests.
Covers https://github.com/PowerShell/vscode-powershell/issues/3683 and https://github.com/PowerShell/PowerShellEditorServices/pull/1823.
> Add regression tests for F5 and F8 saving to history

- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
So that events registered with the `OnIdle` engine event handler will always work.
Resolves https://github.com/PowerShell/vscode-powershell/issues/4048
I added the following code to my profile:
```powershell
Register-EngineEvent -SourceIdentifier PowerShell.OnIdle -MaxTriggerCount 10 -Action {
Write-Host "OnIdle"
}
```
and was able to repro the linked issue before this change, and cannot repro it afterwards.
There may be other ramifications that we're not seeing though, and I'd be curious about a regression test for this.
> Created a nested PowerShell for the top-level loop

- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
- src/PowerShellEditorServices/Services/PowerShell/Utility/CommandHelpers.cs
- src/PowerShellEditorServices/Services/Symbols/ReferenceTable.cs
- src/PowerShellEditorServices/Services/Symbols/SymbolsService.cs
- src/PowerShellEditorServices/Services/Symbols/Vistors/AstOperations.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DidChangeWatchedFilesHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/TextDocumentHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/ScriptFile.cs
- src/PowerShellEditorServices/Services/Workspace/LanguageServerSettings.cs
- src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
- test/PowerShellEditorServices.Test/Language/SymbolsServiceTests.cs
Dependent on PowerShell/vscode-powershell#4170
Significantly reduce performance overhead of reference finding in large workspaces.
This PR has the following changes:
1. Adds a reference cache to every `ScriptFile`
2. Workspace scan is performed only once on first request
3. An LSP file system watcher provides updates for files not changed via `Did*TextDocument` notifications
4. Adds a setting to only search "open documents" for references. This disables both the initial workspace scan and the file system watcher, relying only on `Did*TextDocument` notifications.
---
As a stress test I opened up my profile directory (which has ~3k script files in total in the `Modules` directory) and created a file with a function definition on every line. I then tabbed to a different file, and then tabbed …
> Overhaul workspace search for symbol references

- modules.json
- src/PowerShellEditorServices/Services/Workspace/LanguageServerSettings.cs
Bump version and expose new setting related to new `AvoidSemicolonsAsLineTerminators` rule.
Impediment of https://github.com/PowerShell/vscode-powershell/pull/4164
PSSA 1.21.0 will release soon.
> Upgrade PSScriptAnalyzer to 1.21.0

- src/PowerShellEditorServices/Services/Extension/ExtensionService.cs
- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
We generalized the "execution busy status" from just editor commands to any running PowerShell task.
> Generalize the execution busy status to all PowerShell tasks

- README.md
Executing pwsh with the original command (the older one on top) from the readme causes shells to hang.
Not script or automation friendly.
The arguments list is also long enough to scroll off the screen on most devices.
Spacing them out over an array is a screen-friendly alternative.
- However, keeping the old one is good for users who just want a quick copy-and-paste one-liner.
Added an automation-friendly powershell script for starting the service that doesn't hang the shell.
The original command is long (longer than the width of most device screens), so it's not great in documentation, since it needs to be readable. The old one is being left there, so that users have access to a quick and easy copy-and-paste one-liner.
It also hangs the shell. If you run it from the command line, you …
> Add example of starting PSES in a script to readme

- .vsts-ci/templates/ci-general.yml
Add assertion to build that bits are built in release configuration and invoke tests in release configuration. Resolves https://github.com/PowerShell/vscode-powershell/issues/4218 by (correctly and how it was expected in the first place) preventing the developer option to wait for debugger to be in the binary.
> Fix release build

- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
- test/PowerShellEditorServices.Test.Shared/Profile/Test.PowerShellEditorServices_profile.ps1
- test/PowerShellEditorServices.Test/PsesHostFactory.cs
- test/PowerShellEditorServices.Test/Session/PsesInternalHostTests.cs
Unfortunately the (admittedly hairy) change made in https://github.com/PowerShell/PowerShellEditorServices/pull/1918 to fix:
> System.Management.Automation.PSInvalidOperationException: The pipeline was not run because a pipeline is already running. Pipelines cannot be run concurrently.
has resulted in https://github.com/PowerShell/vscode-powershell/issues/4219:
> System.Management.Automation.PSInvalidOperationException: You should only run a nested pipeline from within a running pipeline.
because we had hacked in that _all_ our pipelines are nested (to allow the concurrency check to pass), but when loading profiles, we do not actually have a running pipeline, so our  lie about being nested fails another check.
So I think what happened was that …
> Fix regression around `OnIdle` handler

- src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
- test/PowerShellEditorServices.Test.E2E/LSPTestsFixures.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
We'll still see the same error in the log, but as a warning and not as an exception bubbled up over LSP that causes some clients, like Kate, to crash. We can't do anything about PowerShell's completion failing.
Fixes #1926.
> Catch exceptions within completion handler

- PowerShellEditorServices.build.ps1
This was introduced in f234a8e to workaround an upstream bug in `dotnet`. That issue has since been fixed and released (so this flag is auto-injected), hence we can remove it.
> Remove `/p:UseSharedCompilation=false` injection

- src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
- test/PowerShellEditorServices.Test.E2E/DebugAdapterProtocolMessageTests.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
In order to support funny path names with dollar signs. Also this is what PowerShell does by default (e.g. through tab-completion).
Resolves https://github.com/PowerShell/vscode-powershell/issues/4238.
> Wrap script paths with single instead of double quotes

- src/PowerShellEditorServices/PowerShellEditorServices.csproj
Since PowerShell pulls this dependency in, and says "or higher" but NuGet doesn't explicitly update it unless we do so manually.
> Manually update `Newtonsoft.Json`

- PowerShellEditorServices.Common.props
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj
- test/PowerShellEditorServices.Test.Shared/PowerShellEditorServices.Test.Shared.csproj
- test/PowerShellEditorServices.Test/Language/CompletionHandlerTests.cs
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
- test/PowerShellEditorServices.Test/Services/Symbols/PSScriptAnalyzerTests.cs
This update includes https://github.com/OmniSharp/csharp-language-server-protocol/pull/892 which fixes https://github.com/PowerShell/vscode-powershell/issues/4175.
> Bump OmniSharp to `v0.19.6`

- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj
This reverts commit 7277b2d6e44d602690408f096d864a34fdbdbbde.
It's not compatible with `netcoreapp3.1`.
> Revert "Bump Microsoft.Extensions.Logging from 6.0.0 to 7.0.0 (#1948)"

- .github/workflows/codeql-analysis.yml
- .github/workflows/emacs-test.yml
- .github/workflows/vim-test.yml
- .vsts-ci/templates/ci-general.yml
- PowerShellEditorServices.build.ps1
- global.json
- src/PowerShellEditorServices/Utility/FormatUtils.cs
- test/PowerShellEditorServices.Test.E2E/Processes/LoggingStream.cs
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
And in a few weeks we'll remove PowerShell 7.0 (and thus `netcoreapp3.1`).
> Add PowerShell 7.3 to test matrix

- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/HostStartOptions.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
It seems to work, but needs more testing.
I don't particularly like copy/pasting https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/terminal/browser/media/shellIntegration.ps1 with modifications to embed it, but not sure what else to do here.
Resolves https://github.com/PowerShell/vscode-powershell/issues/3901 along with https://github.com/PowerShell/vscode-powershell/pull/4271.
> Enable VS Code's shell integration

- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
By replacing backtick-e with `$([char]0x1b)`, we allow shell integration to work with Windows PowerShell, as the only problem seemed to be use of backtick-e, which was an escape character added only to PowerShell Core, but the `[char]` equivalent works fine.
Same change as proposed upstream in https://github.com/microsoft/vscode/pull/167023, resolves https://github.com/PowerShell/vscode-powershell/issues/4279.
> Replace backtick-e with `$([char]0x1b)`

- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Server/PsesDebugServer.cs
- src/PowerShellEditorServices/Services/CodeLens/ReferencesCodeLensProvider.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeActionHandler.cs
- src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs
Pinning this in https://github.com/PowerShell/PowerShellEditorServices/pull/1947 before getting our transitive dependencies in order seems to be the root cause of https://github.com/PowerShell/vscode-powershell/issues/4278 and possibly also https://github.com/PowerShell/vscode-powershell/issues/4283. We're going to revert until we get OmniSharp's dependency sorted, and test in preview with users if those issues are resolved.
> Revert manual pin of Newtonsoft.Json

- src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
- src/PowerShellEditorServices/Services/PowerShell/Context/PowerShellVersionDetails.cs
- src/PowerShellEditorServices/Services/PowerShell/Handlers/GetVersionHandler.cs
- src/PowerShellEditorServices/Services/PowerShell/Handlers/IGetVersionHandler.cs
- src/PowerShellEditorServices/Utility/VersionUtils.cs
This simply wasn't being used and was overly complicated. The only time we want the architecture is when queried via LSP so that the VS Code client can determine which installer to download for its auto-update feature. If we can, we should deduplicate version logic in the loader and the `VersionUtils` class.
Simplification found when investigating https://github.com/PowerShell/vscode-powershell/issues/3435.
> Remove unnecessary `PowerShellProcessArchitecture`

- .vsts-ci/templates/ci-general.yml
- PowerShellEditorServices.build.ps1
- src/PowerShellEditorServices.Hosting/PowerShellEditorServices.Hosting.csproj
- test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
Which more importantly means we can drop `netcoreapp3.1`. Resolves https://github.com/PowerShell/PowerShellEditorServices/issues/1879.
> Drop support for end-of-life PowerShell 7.0

- src/PowerShellEditorServices/Services/PowerShell/Handlers/ShowHelpHandler.cs
This was broken after the rewrite because we'd forgotten to specify that it needs the foreground (which implies too that it must run immediately). Now the script actually executes, either showing the help in the Extension Terminal (or...I guess nowhere for clients without it) or opening the URL it found. This should still be rewritten properly to return the help over LSP and do something better with it, but at least it's no longer broken.
Fixes https://github.com/PowerShell/vscode-powershell/issues/4212.
> Fix `ShowHelpHandler` by running with `RequiresForeground`

- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
This should let us take the update with a temporary workaround suggested by @TravisEz13 in https://github.com/PowerShell/PowerShell/issues/18782.
> Update `Microsoft.PowerShell.SDK` with workaround

- src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
- src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/VariableDetails.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/VariableDetailsBase.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/DebugEvaluateHandler.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/VariablesHandler.cs
- src/PowerShellEditorServices/Services/PowerShell/Debugging/PowerShellDebugContext.cs
- test/PowerShellEditorServices.Test.Shared/Debugging/GetChildItemTest.ps1
- test/PowerShellEditorServices.Test.Shared/Debugging/VariableTest.ps1
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
- test/PowerShellEditorServices.Test/Session/PsesInternalHostTests.cs
This resolves https://github.com/PowerShell/vscode-powershell/issues/4174, https://github.com/PowerShell/vscode-powershell/issues/4314, https://github.com/PowerShell/PowerShellEditorServices/issues/1863 and https://github.com/PowerShell/PowerShellEditorServices/issues/1686.
> Fix several bugs in the debugger

- module/PowerShellEditorServices/Commands/Public/Set-ScriptExtent.ps1
This was some of the first code I ever contributed...and it shows. It's actually really easy to solve the problem of "when editing many parts of the same document, offsets no longer match up". You just go in reverse, and then you don't have that problem anymore.
So this gets rid of the "waiting for the document" to update which takes forever.
> Make `Set-ScriptExtent` not slow

- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Updates our embedded copy with changes made upstream, see https://github.com/microsoft/vscode/pull/170516.
Fixes https://github.com/PowerShell/vscode-powershell/issues/4343.
> Update VS Code shell integration script

- src/PowerShellEditorServices/Services/Symbols/ReferenceTable.cs
- test/PowerShellEditorServices.Test.Shared/References/SimpleFile.ps1
- test/PowerShellEditorServices.Test/Language/SymbolsServiceTests.cs
As noted by @fflaten in https://github.com/PowerShell/vscode-powershell/issues/1465#issuecomment-1421401557, our initial logic counted _every_ assignment as a declaration. While there's no true way to determine which is _really_ the declaration, we can make a relatively safe assumption that the first encountered declaration is it. This is efficient, easy, and seems to work quite well.
> Keep only first assignment as declaration

- module/PowerShellEditorServices/InvokePesterStub.ps1
- src/PowerShellEditorServices/Services/Symbols/PesterDocumentSymbolProvider.cs
- test/PowerShellEditorServices.Test.Shared/Symbols/FindSymbolsInPSKoansFile.cs
- test/PowerShellEditorServices.Test.Shared/Symbols/PesterFile.Koans.ps1
- test/PowerShellEditorServices.Test/Language/SymbolsServiceTests.cs
Adds support for using Run/Debug Tests codelens and Run/Debug Pester Tests commands with `*.Koans.ps1`-files used by [PSKoans](https://github.com/vexx32/PSKoans).
Manually testing only for `InvokePesterStub.ps1` to avoid extra dependency for a simple feature.
Fix PowerShell/vscode-powershell#4363
> Support Run/Debug tests in PSKoans-files

- src/PowerShellEditorServices/Services/Symbols/Visitors/SymbolVisitor.cs
- src/PowerShellEditorServices/Utility/VisitorUtils.cs
- test/PowerShellEditorServices.Test.Shared/Symbols/MultipleSymbols.ps1
- test/PowerShellEditorServices.Test/Language/SymbolsServiceTests.cs
Like methods we just bucket them as overloads, which means that it works better than before despite not being perfect.
Resolves https://github.com/PowerShell/vscode-powershell/issues/1089.
> Strip scope from function references

- src/PowerShellEditorServices/Utility/VisitorUtils.cs
I forgot that C# won't just optimize away static arrays.
> Declare scope prefixes array as static readonly

- src/PowerShellEditorServices/Extensions/Api/WorkspaceService.cs
- src/PowerShellEditorServices/Extensions/EditorWorkspace.cs
- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
- src/PowerShellEditorServices/Services/Extension/EditorOperationsService.cs
- src/PowerShellEditorServices/Services/Symbols/SymbolReference.cs
- src/PowerShellEditorServices/Services/Workspace/Handlers/ConfigurationHandler.cs
- src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs
- test/PowerShellEditorServices.Test/Language/SymbolsServiceTests.cs
- test/PowerShellEditorServices.Test/Session/WorkspaceTests.cs
Resolves https://github.com/PowerShell/vscode-powershell/issues/2112. Should probably write a test for it, does _not_ yet include updates to the API to handle getting the correct workspace for an open editor.
> Add `WorkspaceFolders` and use it when enumerating files

- module/PowerShellEditorServices/Commands/Public/CmdletInterface.ps1
- module/PowerShellEditorServices/Commands/Public/Out-CurrentFile.ps1
Updates `New-EditorFile` to insert text in the newly created editor as intended.
Also took the liberty to silent the `EditorContext`-object currently being returned from `Out-CurrentFile` after #869. I'm 99% sure that's unintended 🙂 /cc @dfinke 
Fix https://github.com/PowerShell/vscode-powershell/issues/3192
> Fix New-EditorFile adding content in current file

- src/PowerShellEditorServices/Services/Symbols/PesterDocumentSymbolProvider.cs
Support Pester features when using module-qualified commands.
Fix PowerShell/vscode-powershell#928
> Support module-qualified calls for Pester keywords

- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
- src/PowerShellEditorServices/Services/Analysis/PssaCmdletAnalysisEngine.cs
- src/PowerShellEditorServices/Services/CodeLens/ICodeLensProvider.cs
- src/PowerShellEditorServices/Services/CodeLens/PesterCodeLensProvider.cs
- src/PowerShellEditorServices/Services/CodeLens/ReferencesCodeLensProvider.cs
- src/PowerShellEditorServices/Services/PowerShell/Utility/CommandHelpers.cs
- src/PowerShellEditorServices/Services/Symbols/PesterDocumentSymbolProvider.cs
- src/PowerShellEditorServices/Services/Symbols/RegionDocumentSymbolProvider.cs
- src/PowerShellEditorServices/Services/Symbols/SymbolDetails.cs
- src/PowerShellEditorServices/Services/Symbols/SymbolType.cs
- src/PowerShellEditorServices/Services/Symbols/SymbolsService.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeActionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeLensHandlers.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DefinitionHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DocumentHighlightHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/DocumentSymbolHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/FoldingRangeHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/FormattingHandlers.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/HoverHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/Handlers/ReferencesHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/TokenOperations.cs
- src/PowerShellEditorServices/Services/Workspace/Handlers/WorkspaceSymbolsHandler.cs
- test/PowerShellEditorServices.Test.Shared/Symbols/MultipleSymbols.ps1
- test/PowerShellEditorServices.Test/Language/SymbolsServiceTests.cs
And some technical debt clean-ups.
Replaces (and re-uses!) @fflaten's https://github.com/PowerShell/PowerShellEditorServices/pull/1911.
Resolves https://github.com/PowerShell/vscode-powershell/issues/3604 and https://github.com/PowerShell/vscode-powershell/issues/3210.
> Add document symbols for `#region`

- src/PowerShellEditorServices/Services/Symbols/Visitors/SymbolVisitor.cs
- test/PowerShellEditorServices.Test.Shared/Definition/FindsTypedVariableDefinition.cs
- test/PowerShellEditorServices.Test.Shared/References/SimpleFile.ps1
- test/PowerShellEditorServices.Test/Language/SymbolsServiceTests.cs
Resolves https://github.com/PowerShell/vscode-powershell/issues/4443.
> Fix declaration detection for variables with type constraints

- .github/workflows/emacs-test.yml
- .gitignore
- PowerShellEditorServices.build.ps1
- README.md
- test/emacs-test.el
Since it's always used post-build to generate the documentation, we have a `#requires` for it but forgot to add it to the documentation.
Also suppress stderr for sysctl when checking if macOS is an Intel or Arm processor. On the former, it doesn't know what field we're querying.
> Update build documentation to include platyPS requirement

- docs/guide/getting_started.md
Added a getting started guide to setup and configure PowerShell Editor Services with Neovim.
The setup documentation for non-VS Code editors is not present.  Adding this getting started guide will help users setup and configure the LSP server for use with those editors.
> Add guide to configure Neovim

- .github/dependabot.yml
There seems to be a bug in the backend that thinks we're hitting the default limit of 5 even when no PRs are open.
Also switch to weekly like the client.
> Fix Dependabot pull requests limit

- src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
- src/PowerShellEditorServices.Hosting/Configuration/SessionFileWriter.cs
- src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
This updates our session failure logic (we were no longer ever sending a "failed" status back, hence the awful experience in the client). If PowerShell does start, but detects that it's not going to work due to unsupported PowerShell or .NET Framework versions (applicable only to Windows PowerShell), we set the session status to failed and actually report the PowerShell version for use by the client's error reporting.
Note that as far as we know, our minimum .NET Framework support for Windows PowerShell is now 4.8, per https://github.com/PowerShell/vscode-powershell/issues/4483.
Resolves https://github.com/PowerShell/vscode-powershell/issues/4509.
> Set session failure with reason when applicable

- src/PowerShellEditorServices/Services/DebugAdapter/BreakpointService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/BreakpointHandlers.cs
- src/PowerShellEditorServices/Services/PowerShell/Debugging/DscBreakpointCapability.cs
- src/PowerShellEditorServices/Services/PowerShell/Debugging/IPowerShellDebugContext.cs
- src/PowerShellEditorServices/Services/PowerShell/Debugging/PowerShellDebugContext.cs
- src/PowerShellEditorServices/Services/PowerShell/Runspace/RunspaceInfo.cs
- src/PowerShellEditorServices/Services/Template/TemplateService.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
- test/emacs-test.el
While debugging the `Write-Output` bug (hence the branch name) I came across another bug where the server was attempting to load the DSC module repeatedly. The `SetLineBreakpoint` logic queries for DSC breakpoint capability, which was importing the module, catching the failure to import as an error, and then trying again every single time. Instead we should import (or fail to import) only the first time we try. Also, we don't need to transform the `BreakpointDetails` list into an array and back, just leave it as `IEnumerable`.
> Fix repeated failure to load DSC module

- src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
- src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/DebugEvaluateHandler.cs
- src/PowerShellEditorServices/Services/PowerShell/Context/PowerShellVersionDetails.cs
- src/PowerShellEditorServices/Services/PowerShell/Handlers/ExpandAliasHandler.cs
- src/PowerShellEditorServices/Services/PowerShell/Handlers/ShowHelpHandler.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/EditorServicesConsolePSHostUserInterface.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
- src/PowerShellEditorServices/Services/PowerShell/Runspace/SessionDetails.cs
- src/PowerShellEditorServices/Services/Symbols/SymbolsService.cs
What a bug! In PowerShell 5.1 our artificial pipeline for event handling (among other possible PowerShell tasks) could cause the output to just disappear. Turns out a [bug in 5.1](https://github.com/PowerShell/PowerShell/pull/3436) with the transcript was being triggered. Scripts without `Out-Default` would get it appended with `-TranscribeOnly True` in order for the transcription to happen...but the `TranscribeOnly` field could erroneously not be set back to `false`! This would cause all output to just "disappear." It was fixed in PowerShell 7, but we still have to work around it for PowerShell 5.1 by resetting it.
Resolves https://github.com/PowerShell/vscode-powershell/issues/3991, and fixes a few other things too.
Unfortunately due to the implementation of PowerShell 5.1's transcript, …
> Fix disappearing output in PowerShell 5.1

- .editorconfig
- src/PowerShellEditorServices.Hosting/PowerShellEditorServices.Hosting.csproj
- src/PowerShellEditorServices.VSCode/PowerShellEditorServices.VSCode.csproj
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/EditorServicesConsolePSHostUserInterface.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
- test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
We were using our own UI, not the byzantine internal UI where it actually needed to be fixed.
This is https://github.com/PowerShell/PowerShellEditorServices/pull/2023 but again, with the right UI.
And not only have we tracked this down, we were finally able to reproduce it (and so test this fix).
Resolves https://github.com/PowerShell/vscode-powershell/issues/3991.
> Fix the `TranscribeOnly` bug (take two)

- src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
Resolves https://github.com/PowerShell/vscode-powershell/issues/4582
> Ignore cancellation of completion requests

- src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
- src/PowerShellEditorServices.VSCode/PowerShellEditorServices.VSCode.csproj
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
- src/PowerShellEditorServices/Utility/VersionUtils.cs
- test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj
Yet again fixing compiler constants, just go this plain wrong last time. Also caught in testing that we need to disable `TranscribeOnly` in the `finally` of `ExecuteDebugger` too, so that the original `Out-Default` (from the invocation of the debugged script) isn't broken.
> Fix the `TranscribeOnly` bug (take three)

- modules.json
We are going to test [PSReadLine v2.3.1-beta1](https://github.com/PowerShell/PSReadLine/releases/tag/v2.3.1-beta1) in the extension pre-release, and if there are no reported issues, we may roll that into the extension release.
> Bump PSReadLine to beta for extension preview

- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Since `$IsWindows` doesn't exist in Windows PowerShell, with strict mode enabled and the `ErrorActionPreference` set to `Stop`, shell integration would cause the startup to crash. This was reported and fixed upstream too.
Resolves https://github.com/PowerShell/PowerShellEditorServices/issues/2050.
> Fix shell integration for PowerShell 5.1 with strict mode

- PowerShellEditorServices.build.ps1
That's all. Better resolves https://github.com/PowerShell/vscode-powershell/issues/3484.
> Move `ConstrainedLanguageMode` tests to separate task

- src/PowerShellEditorServices/Extensions/EditorRequests.cs
- src/PowerShellEditorServices/Extensions/EditorWindow.cs
- src/PowerShellEditorServices/Extensions/EditorWorkspace.cs
- src/PowerShellEditorServices/Extensions/FileContext.cs
- src/PowerShellEditorServices/Extensions/IEditorOperations.cs
- src/PowerShellEditorServices/Services/Extension/EditorOperationsService.cs
- src/PowerShellEditorServices/Services/PowerShell/Handlers/GetCommentHelpHandler.cs
- src/PowerShellEditorServices/Services/TextDocument/ScriptFile.cs
- src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs
- test/PowerShellEditorServices.Test/Session/WorkspaceTests.cs
Receive a `EditorOperationResponse` (not yet otherwise used). Delete dead code. Add optional `content` parameter to `NewFile`. Expose `CloseFile` and `SaveFile`. Fix an outdated warning message.
Part of https://github.com/PowerShell/vscode-powershell/pull/4703 so I could test it.
> Fix up extension API

- src/PowerShellEditorServices/Services/PowerShell/Debugging/DscBreakpointCapability.cs
When the user has set `ErrorActionPreference` this could cause a crash, so we have to override it. Resolves #2037.
> Ignore not finding DSC module

- src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
- src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
The code relied on running `list 1 <MaxInt>` but that wasn't being run in the debug context because we allow-list commands to prevent pollution of the history, and missed it. Like the `prompt` and interactive commands (which `list` could be but is not when we run it) we need to check for this exact `list` command and run it under the debugger.
Moreover, we also weren't locking the `debugInfoHandle`, nor were we correctly checking if `scriptListingLines` was empty (it was never null), and our shortcut to skip allocation was broken. Actually we can't skip allocation, but we can at least skip superfluous conversions.
Resolves https://github.com/PowerShell/vscode-powershell/issues/3904.
> Fix debugging script blocks that aren't in files

- src/PowerShellEditorServices/Services/Workspace/Handlers/ConfigurationHandler.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
While this implementation is useful, we are not currently doing anything with said telemetry and therefore should not be sending it. We can bring it back by reference this commit.
> Remove unused telemetry

- src/PowerShellEditorServices.Hosting/Configuration/HostLogger.cs
So that the extension can start when logging is disabled.
Fixes https://github.com/PowerShell/vscode-powershell/issues/4735.
> Add `None` to `PsesLogLevel` enum

- modules.json
And now we won't have to ship the beta.
> Bump to new PSReadLine stable release v2.3.3

- src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/BreakpointApiUtils.cs
- src/PowerShellEditorServices/Services/PowerShell/Debugging/DscBreakpointCapability.cs
- src/PowerShellEditorServices/Services/PowerShell/Utility/PowerShellExtensions.cs
And set it back afterwards. Since it has `ErrorAction = Ignore` it should always get set back correctly. This prevents the progress pane from getting stuck in certain circumstances.
> Wrap import of DSC module with `ProgressPreference = SilentlyContinue`

- src/PowerShellEditorServices/Services/PowerShell/Debugging/DscBreakpointCapability.cs
It wasn't the module import that was being noisy but the next command. It sure looked like the last commit "fixed" it in testing because the output was certainly silenced...but that was actually due to the side effect of having added an `AddScript` to the `PSCommand` causing it to no longer return the imported module at all. Without that return value, the noisy code wasn't executing either. Now the progress preference is saved, set to silent, `Get-DscResource` is run (silently) and then the preference is restored. Double-checked in the debugger.
> Silence progress output of `Get-DscResource` (take two)

- src/PowerShellEditorServices/Services/TextDocument/Handlers/TextDocumentHandler.cs
For some reason VS Code, in some repositories and configurations, will send us `DidOpenTextDocument` notifications for special documents with the `git` scheme (not `file` or `untitled`). It's probably some internal representation that VS Code is using to supply VCS information. Because we were specifically ignoring the URI in this handler these files were getting erroneously added to our workspace service's list of open files, which then caused duplicate references.
Fixes https://github.com/PowerShell/vscode-powershell/issues/4784.
> Ignore `didOpen` notifications for `git` schemed documents from VS Code

- src/PowerShellEditorServices/Services/TextDocument/Handlers/DocumentSymbolHandler.cs
This is probably what OmniSharp was doing for us. Fixes the bug introduced by #2083.
Hey, at least I didn't use LINQ. Thanks Bing Chat for the algorithm help. This should probably wait for the pre-release after the next stable release.
> Add `SortDocumentSymbols` to make the outline hierarchical (again)

- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
So that if a user runs `Set-Location` in their profile, it's not later overridden.
Fixes https://github.com/PowerShell/vscode-powershell/issues/4788
> Run `SetInitialWorkingDirectoryAsync` before `LoadProfiles`

- src/PowerShellEditorServices/Services/Extension/EditorOperationsService.cs
- src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs
- test/PowerShellEditorServices.Test/Session/WorkspaceTests.cs
We were previously adding the initial working directory as a fallback if there was no workspace. However, this led to new VS Code windows (not in a workspace) enumerating all files in the home directory (if that's what the client had to default to, without a workspace folder). And this could even spam permission requests on more secure systems such as macOS. So we just need to let be an empty enumerable.
This may resolve https://github.com/PowerShell/vscode-powershell/issues/4814 and https://github.com/PowerShell/vscode-powershell/issues/4821. Bug was introduced in https://github.com/PowerShell/PowerShellEditorServices/pull/1995.
> Allow `WorkspacePaths` to be empty if we're not in a workspace

- src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/DebugEvaluateHandler.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
No idea _why_ its value was `""`, but it was, so we special case it and return `$null` just like you get from watched variables that were assigned the built-in `$null`.
Resolves https://github.com/PowerShell/vscode-powershell/issues/4816.
> When the built-in `$null` was watched its value was incorrect

- .editorconfig
- .github/workflows/ci-test.yml
- .vsts-ci/azure-pipelines-ci.yml
- .vsts-ci/misc-analysis.yml
- .vsts-ci/templates/ci-general.yml
- PowerShellEditorServices.build.ps1
- README.md
- global.json
- src/PowerShellEditorServices/Utility/VersionUtils.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
- test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj
- test/PowerShellEditorServices.Test.E2E/Processes/PsesStdioProcess.cs
- test/PowerShellEditorServices.Test.E2E/packages.lock.json
- test/PowerShellEditorServices.Test.Shared/Completion/CompleteVariableInFile.cs
- test/PowerShellEditorServices.Test/Language/CompletionHandlerTests.cs
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
- test/PowerShellEditorServices.Test/packages.lock.json
> Add PowerShell 7.4 SDK and `net8.0` framework

- .github/workflows/ci-test.yml
- PowerShellEditorServices.build.ps1
- test/PowerShellEditorServices.Test.E2E/Processes/PsesStdioProcess.cs
This downloads the PowerShell Daily build on CI and executes the end-to-end tests with it. It's set to run on a schedule and fail to alert us to issues (but won't block PRs because it won't run on them at all).
> Test end-to-end with PowerShell Daily

- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Happy new year! Updated one year ago today, it needed it again. This has actually been broken for a while unfortunately because the last time we manually patched it to disable strict mode, we did so before capturing the exit code (and thus it was lost). Fixed now at least.
Fixes https://github.com/PowerShell/vscode-powershell/issues/4854 and https://github.com/PowerShell/vscode-powershell/issues/4864.
> Update shell integration script to fix command decorations

- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/DebuggerActionHandlers.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/LaunchAndAttachHandler.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/SetVariableHandler.cs
- src/PowerShellEditorServices/Services/PowerShell/Handlers/IGetRunspaceHandler.cs
- src/PowerShellEditorServices/Services/PowerShell/Handlers/PSHostProcessAndRunspaceHandlers.cs
- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
First off, the error messages were never actually displayed to the user because the `RpcErrorException` constructor takes three arguments. Secondly, we do not support attaching to PowerShell Editor Services. It sure looked like we did (because we had special logic for it) but once attached, nothing worked. So it was half-baked. Now we throw an error if the user is trying to do that. Thirdly, because of that half-baked implementation, the process ID field was typed as a string (to support "current" as a shortcut)but that caused a mess here and an error in the VS Code client. Now it's just always an integer. (Same for the runspace ID.) Fourthly, a big mess was cleaned up by refactoring using functions, who'd have thought? Fifth and finally, superfluous version checking around PowerShell …
> Fix up debugger attach handlers

- PowerShellEditorServices.build.ps1
- src/PowerShellEditorServices/Services/Symbols/Visitors/AstOperations.cs
Occasionally TabExpansion2 may return null. This could be due to a custom implementation of TabExpansion2 or an underlying issue with the FileSystemProvider or LocationGlobber. 
When this happens the value of commandCompletion is not assigned and remains null. This causes a NullReferenceException to be thrown when commandCompletion.ReplacementLength is accessed in the subsequent call to LogTrace.
> Added null check to `GetCompletionsAsync`

- test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
PR #2115 added a new error message when no completion is returned (such as when it was interrupted) and our test covering a specific bug with PowerShell 7.2 was not updated. Investigating how CI missed this.
> Fix PowerShell 7.2 E2E unit test for last change

- src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
- src/PowerShellEditorServices.Hosting/Configuration/EditorServicesConfig.cs
- src/PowerShellEditorServices.Hosting/Internal/EditorServicesRunner.cs
- src/PowerShellEditorServices/Hosting/HostStartupInfo.cs
- src/PowerShellEditorServices/Services/Analysis/PssaCmdletAnalysisEngine.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
- test/PowerShellEditorServices.Test/PsesHostFactory.cs
- test/PowerShellEditorServices.Test/Services/Symbols/PSScriptAnalyzerTests.cs
Meaningful output from PSES's internal PowerShell is suppressed if you don't specify -EnableConsoleRepl.
I'd like to be able to see the output from PSScriptAnalyzer but my application has a read-only terminal. 
This SwitchParameter prevents the UI from being set to NullPSHostUI without enabling Repl functionality.
Perhaps a better way to implement this would be to condition off the use of named pipes as I believe the intention of the following code is to prevent clobbering stdio since ConsoleRepl can only be used when connecting via named pipes.
```csharp
UI = hostInfo.ConsoleReplEnabled || hostInfo.UseCurrentPSHostUI
? new EditorServicesConsolePSHostUserInterface(loggerFactory, hostInfo.PSHost.UI)
: new NullPSHostUI();
```
> Add `UseNullPSHostUI` config so apps hosting PSES can disable it

- src/PowerShellEditorServices/Services/TextDocument/ScriptFile.cs
- src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs
- test/PowerShellEditorServices.Test/Extensions/ExtensionCommandTests.cs
- test/PowerShellEditorServices.Test/Language/SemanticTokenTest.cs
- test/PowerShellEditorServices.Test/Language/TokenOperationsTests.cs
- test/PowerShellEditorServices.Test/Session/WorkspaceTests.cs
Small nitpick I found when refactoring other stuff
https://stackoverflow.com/questions/2988977/passing-idisposable-objects-through-constructor-chains
> Fixed TextReader disposal

- .github/workflows/emacs-test.yml
- .github/workflows/vim-test.yml
- module/PowerShellEditorServices/Start-EditorServices.ps1
- src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
- src/PowerShellEditorServices/Hosting/EditorServicesServerFactory.cs
- test/emacs-simple-test.el
- test/vim-simple-test.vim
We do not need to require so many CLI flags.
This continues to run the existing Emacs and Vim tests utilizing those flags as a regression scenario, and adds an additional pair of tests that launch PSES with a minimal set of flags.
Resolves #1855.
Slight breaking change for CLI users of the `-LogPath` parameter. It now takes a directory name instead of a log name, which makes a lot more sense because multiple log files get written to that location.
> Add sane defaults to `Start-EditorServices`

- src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
- src/PowerShellEditorServices/Hosting/EditorServicesServerFactory.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/LaunchAndAttachHandler.cs
- src/PowerShellEditorServices/Services/PowerShell/Handlers/PSHostProcessAndRunspaceHandlers.cs
> Release build was broken because of an `#if DEBUG` for `System.Diagnostics`

- .github/workflows/ci-test.yml
- .vsts-ci/azure-pipelines-ci.yml
It is completely superfluous because the release pipeline runs the exact same CI template, and it's still really flaky.
Also run the GitHub Actions CI with the Release configuration.
> Disable Azure Pipelines CI for release branch

- README.md
- test/emacs-simple-test.el
> Update readme for simplified CLI

- README.md
Update clients that support debugging: Adding Neovim
> Update clients that support debugging: Adding Neovim

- .github/release.yml
- .pipelines/PowerShellEditorServices-Official.yml
- tools/updateVersion.ps1
Small updates made while setting up the vscode-powershell pipeline.
> Support 'preview' in version

- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/HostStartOptions.cs
- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Instead of having to maintain an edited copy (which was really annoying) I stubbed out `PSConsoleHostReadLine` to do what's expected. So now we can just use the existing shell integration script directly!
Since we can't reliably find the script using `code --locate-shell-integration-path pwsh` we now rely on it being sent by the client on initialization. Its presence implies the feature is on.
This is pretty VS Code specific, but not necessarily so.
> Use a provided shell integration script directly

- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
- test/PowerShellEditorServices.Test/packages.lock.json
Fixes a Component Governance warning (it's just tests).
> Update tests' dependency on PowerShell SDK

- README.md
Add [powershell.nvim](https://github.com/TheLeoP/powershell.nvim) to the list of LSP and DAP clients
> README update LSP and DAP clients

- .github/workflows/vim-test.yml
The current ubuntu2.19 package breaks E2E tests. Latest VIM works fine, so switching to nightly for testing.
Band-Aid for https://github.com/PowerShell/PowerShellEditorServices/issues/2182 but will not close it as we should probably find out what in that 2.19 ubuntu security update broke it, as it is currently being distributed widely and we should make sure it hasn't broken ubuntu VIM users.
> Switch VIM E2E tests to use nightly

- .github/workflows/ci-test.yml
Really, it's the installation that's failing because literally the upstream posting of new daily PowerShell builds is broken.
If it succeeds, TestFull and the daily schedule will run it. If it doesn't, they'll ignore it because the build script will skip it.
> Allow daily PowerShell test to fail

- src/PowerShellEditorServices/Services/DebugAdapter/DebugStateService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/LaunchAndAttachHandler.cs
- src/PowerShellEditorServices/Utility/PSCommandExtensions.cs
- test/PowerShellEditorServices.Test.E2E/DebugAdapterClientExtensions.cs
- test/PowerShellEditorServices.Test.E2E/DebugAdapterProtocolMessageTests.cs
Add support to change how the scripts are launched (DotSource vs Call operator).
Adds the ExecuteMode property and the corresponding method to either use the DotSource operator or the Call operator when launching scripts.
Related to this PR: ~~https://github.com/PowerShell/vscode-powershell/pull/5036~~ https://github.com/PowerShell/vscode-powershell/pull/5059
See https://github.com/PowerShell/vscode-powershell/issues/4327
It's not always desirable to alter the current scope, this PR allows the use of the Call operator when launching scripts.
> Add the ability to use either `.` or `&` when launching script

- test/PowerShellEditorServices.Test.Shared/Completion/CompleteCommandInFile.cs
- test/PowerShellEditorServices.Test.Shared/Completion/CompletionExamples.psm1
Which now includes an AWS module with a conflicting completion (`AWS.Tools.SocialMessaging.psd1`). Why GitHub Actions installed that, I don't know. Why our test made such a broad assumption, also unknown.
> Fix unit test broken by GitHub Action image update

- .github/workflows/ci-test.yml
- .gitignore
- .pipelines/PowerShellEditorServices-Official.yml
- PowerShellEditorServices.build.ps1
- tools/installPSResources.ps1
> Migrate to DeployBox for release stage

- CHANGELOG.md
- PowerShellEditorServices.Common.props
- module/PowerShellEditorServices/PowerShellEditorServices.psd1
> v3.21.0: Updates to PSScriptAnalyzer and Call-operator support

- src/PowerShellEditorServices/Services/TextDocument/Handlers/PsesSemanticTokensHandler.cs
- test/PowerShellEditorServices.Test/Language/SemanticTokenTest.cs
Updates the semantic token mapping so attributes now get the "Decorator" token type and loop labels get the "Label" type. They seem to best match the mappings listed here: https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#standard-token-types-and-modifiers
I also removed the Generic -> Function mapping as I feel it does more harm than good to provide an inaccurate mapping. Unfortunately there's no fitting token for them, but feel free to give a thumbs up here: https://github.com/microsoft/vscode/issues/97063#issuecomment-2240581375 so it may get added in the future.
I didn't change this, but I see there's this mapping:
```
case TokenKind.Parameter:
case TokenKind.Generic when token is StringLiteralToken slt && slt.Text.StartsWith("--"):
return …
```
> Update semantic tokens

- Directory.Packages.props
- PowerShellEditorServices.build.ps1
- src/PowerShellEditorServices.Hosting/PowerShellEditorServices.Hosting.csproj
- test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
Also allows us to bump Microsoft.Extensions.Logging to 9.0.0.
> Drop support for PowerShell 7.2 (net6.0) per its end-of-life

- README.md
- src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
- src/PowerShellEditorServices.Hosting/Configuration/EditorServicesConfig.cs
- src/PowerShellEditorServices.Hosting/Configuration/HostLogger.cs
- src/PowerShellEditorServices.Hosting/Configuration/SessionFileWriter.cs
- src/PowerShellEditorServices.Hosting/Configuration/TransportConfig.cs
- src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
- src/PowerShellEditorServices.Hosting/Internal/EditorServicesRunner.cs
- src/PowerShellEditorServices/Logging/HostLoggerAdapter.cs
- src/PowerShellEditorServices/Logging/LanguageServerLogger.cs
- src/PowerShellEditorServices/Server/PsesLanguageServer.cs
- Align PsesLogLevel to MEL log levels
- Adjust some logging verbosity levels for the PSES startup logging flow to move better.
- Create a new LSP Log Debug Provider to get around limitations with the CSharp Omnisharp one.
- Drop all Omnisharp logs to trace since they are just LSP related
- Address LSP bugs by wiring up log levels in-band.
Should be merged with https://github.com/PowerShell/vscode-powershell/pull/5065
> Enhanced Logging

- README.md
Include information on supported PowerShell versions and clarify the support for Windows PowerShell 5.1.
> Docs: Add PowerShell Support Statement

- PowerShellEditorServices.build.ps1
- README.md
Sister to https://github.com/PowerShell/vscode-powershell/pull/5094
> Dev: Add BuildIfChanged Task and Docs

- src/PowerShellEditorServices/Server/PsesDebugServer.cs
- src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ScopesHandler.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/StackTraceHandler.cs
- src/PowerShellEditorServices/Utility/LspDebugUtils.cs
- test/PowerShellEditorServices.Test.E2E/DebugAdapterProtocolMessageTests.cs
Implements DAP `DelayedStackTraceLoading` and returns an artificial breakpoint label frame based on the invocation info ASAP once the debugger stops. The rest of the stack trace is then returned on a future request that doesn't block the client UI.
https://github.com/user-attachments/assets/b909655b-1085-4f8e-a453-99b8af21b877
Debug stepping takes 300ms+ due to waiting for stack trace collection via the slow `Get-PSCallStack` "hack". Further improvements will come around this later.
> Add Breakpoint Label frame to optimize debug stepping performance

- CHANGELOG.md
- PowerShellEditorServices.Common.props
- module/PowerShellEditorServices/PowerShellEditorServices.psd1
> v4.1.0: Debugger optimizations and incremental build support!

- Directory.Packages.props
- src/PowerShellEditorServices.Hosting/Configuration/HostLogger.cs
- src/PowerShellEditorServices.Hosting/PowerShellEditorServices.Hosting.csproj
- src/PowerShellEditorServices/Logging/LanguageServerLogger.cs
- src/PowerShellEditorServices/PowerShellEditorServices.csproj
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/LaunchAndAttachHandler.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/StackTraceHandler.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/VariablesHandler.cs
- src/PowerShellEditorServices/Services/Workspace/Handlers/ConfigurationHandler.cs
- test/PowerShellEditorServices.Test.E2E/DebugAdapterProtocolMessageTests.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
**This requires the following packages to be added to the Build Feed**
```
Roslynator.Analyzers
Roslynator.CodeAnalysis.Analyzers
Roslynator.Formatting.Analyzers
```
Rosylnator used to be used via vscode extension but since the switch to C# Dev Kit, Support for that has been non-functional (https://github.com/dotnet/vscode-csharp/issues/6790)
The analysis packages are now made available as Nuget packages, and this PR integrates them into the non-test repositories. This is the first step to later revise EditorConfig to enforce consistent code style among repositories.
Style-related recommendations based on current editorconfig (these are info recommendations and not enforced)
```
Analyzed solution 'D:\PowerShellEditorServices\PowerShellEditorServices.sln' (in 22.4 s)
4 CA1510    Use …
```
> Enable Roslynator Analyzers via Nuget Package

- src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
- src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs
Mostly investigating https://github.com/PowerShell/vscode-powershell/issues/4743.
> Look in all workspace folders for PSSA settings file

- CHANGELOG.md
- PowerShellEditorServices.Common.props
- module/PowerShellEditorServices/PowerShellEditorServices.psd1
> v4.2.0: Support PSScriptAnalyzer config in multi-root workspaces

- .pipelines/PowerShellEditorServices-Official.yml
- tools/installPSResources.ps1
We can rely on the pre-installed PSResourceGet and we can re-enable tests!
@JustinGrote seriously we can _finally_ run tests again in the release pipeline 🤞
> OneBranch now uses PowerShell 7.4 so remove workarounds

- tools/installPSResources.ps1
> Switch to PowerShell Gallery mirror

- .git-blame-ignore-revs
Adds a [git-blame-ignore-revs](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-and-understanding-files#ignore-commits-in-the-blame-view) file to remove formatting commits from git blame to more accurately identify who made a change.
Enables future refactoring work to not clutter up git blame. Supported natively on Github
> Add git-blame-ignore-revs file for some refactor commits to make blame better.

- src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
- test/PowerShellEditorServices.Test.Shared/Completion/CompletionExamples.psm1
- test/PowerShellEditorServices.Test/Language/CompletionHandlerTests.cs
- test/PowerShellEditorServices.Test/Language/SymbolsServiceTests.cs
Fixes an issue in type parsing where, if a type is discovered, additional documentation gets trimmed off. This restores that to the `Documentation` field.
I did a little experimenting with the new LabelDetail fields in LSP 3.17, but at least in vscode there was little to no visual advantage, something to maybe explore more later.
Would be nice to not have to text parse a string like this but it's where we are at currently with PS API
Related: https://github.com/PowerShell/PowerShell/pull/25108
Related: https://github.com/PowerShell/PowerShell/pull/25112
> Surface Additional Parameter Documentation/Tooltips

- src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Per https://github.com/PowerShell/vscode-powershell/pull/5217
> Import shell integration module

- docs/guide/getting_started.md
Indentation is problem for powershell editing experience in vim/neovim since there's no dedicated indentation handler for powershell, I added a solution for this.
Not related to language server, but can improve life quality
> Add indentation solution for powershell in vim/neovim

- docs/guide/getting_started.md
Not super familiar with Neovim but this is deprecated
```lua
vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
```
and I believe this is the fix
```lua
vim.api.nvim_set_option_value("omnifunc", "v:lua.vim.lsp.omnifunc", { buf = bufnr })
```
> Update deprecated API method in docs

- docs/guide/getting_started.md
Sorry, don't know github too well so all three commits are in one pull request - I did want to do them individually. And one is in a separate PR but also in this one?
Added info for troubleshooting a colorscheme issue
Added info for troubleshooting brackets appearing when autocompleting cmdlets when using blink.cmp (I know it's not really a PSES thing, but I imagine this is where people will look for it)
Added info for configuring additional settings, I know it's from a now deprecated repo, and it's in one string instead of nice but it's better than nothing. 
I added all this as I use Powershell in Neovim and there aren't a lot of useful resources out there, so hopefully this helps other people adopt Neovim :)
> Add useful info to Getting Started

- src/PowerShellEditorServices/Services/DebugAdapter/BreakpointService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/BreakpointHandlers.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
Adds support for setting breakpoints in untitled/unsaved files for Windows PowerShell 5.1. This aligns the breakpoint validation behaviour with the PowerShell 7.x API so that a breakpoint can be set for any ScriptBlock with a filename if it aligns with the client's filename.
Fixes: https://github.com/PowerShell/PowerShellEditorServices/issues/2243
This also means that breakpoints in untitled files will work in Windows PowerShell 5.1 and not just PowerShell 7+.
> Support breakpoints in untitled files in WinPS

- module/PowerShellEditorServices/Commands/Public/Start-DebugAttachSession.ps1
- module/docs/Start-DebugAttachSession.md
Adds the parameter `-WindowActionOnEnd` that corresponds to the new VSCode attach configuration option
`temporaryConsoleWindowActionOnDebugEnd`.
PR that added the VSCode debug option https://github.com/PowerShell/vscode-powershell/pull/5255.
> Add WindowActionOnEnd for Start-DebugAttachSession

- module/PowerShellEditorServices/Start-EditorServices.ps1
This PR adds `Trace`, `Debug`, `Information`, `Critical`, and `None` to the validation set on the `LogLevel` parameter when starting PSES using `Start-EditorServices.ps1` to allow for the adoption of the newer MEL log levels (#2200), closing #2235.
The `ValidationSet` defined for `LogLevel` here: [Start-EditorServices.ps1:49](https://github.com/PowerShell/PowerShellEditorServices/blob/3a429eac5544fd7613c281c0814f94ac03fad551/module/PowerShellEditorServices/Start-EditorServices.ps1#L49) was left out during the work done to enhance logging, meaning that the only MEL levels you can practically use are the ones that are the same as the legacy log levels. I chose to add the missing ones as opposed to replacing the old with the new for compatibility reasons which matched the sentiment [conveyed …
> Add missing MEL log levels to the `LogLevel` validation (#2235)

- module/PowerShellEditorServices/Commands/Public/Start-DebugAttachSession.ps1
- module/docs/Start-DebugAttachSession.md
- src/PowerShellEditorServices/Services/DebugAdapter/BreakpointService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/BreakpointApiUtils.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Debugging/BreakpointDetails.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/BreakpointHandlers.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/DisconnectHandler.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/LaunchAndAttachHandler.cs
- src/PowerShellEditorServices/Services/DebugAdapter/Handlers/StackTraceHandler.cs
- src/PowerShellEditorServices/Services/DebugAdapter/PathMapping.cs
- src/PowerShellEditorServices/Services/PowerShell/Debugging/DscBreakpointCapability.cs
- test/PowerShellEditorServices.Test.E2E/DebugAdapterProtocolMessageTests.cs
- test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
Adds the `pathMappings` option to the debugger that can be used to map a local to remote path and vice versa. This is useful if the local environment has a checkout of the files being run on a remote target but at a different path. The mappings are used to translate the paths that will the breakpoint will be set to in the target PowerShell instance. It is also used to update the stack trace paths received from the remote.
For a launch scenario, the path mappings are also used when launching a script if the integrated terminal has entered a remote runspace.
Fixes: https://github.com/PowerShell/PowerShellEditorServices/issues/2242
> Add `pathMappings` option to debugger
